"""Steward-maintained reference grids lifted verbatim from the legacy T-SQL procedures.

Source of truth: sqlserver/reference/ref.usp_LoadCodeCrosswalk.sql, ref.usp_LoadStatusCode.sql,
ref.usp_LoadReasonCode.sql, ref.usp_LoadPostalFormatRule.sql and ref.usp_LoadRegion.sql.
"""

REGION_GRID = [{'region_code': 'NA',
  'region_name': 'North America',
  'tax_regime_code': 'SALESTAX',
  'default_currency_code': 'USD',
  'fiscal_calendar_code': 'NA_CAL',
  'fiscal_year_start_month': 7,
  'address_rule_set_code': 'NA_USPS',
  'weight_uom_code': 'LB',
  'consent_model_code': 'OPT_OUT',
  'retention_months': 84,
  'date_format_pattern': 'MM/DD/YYYY',
  'decimal_separator': '.'},
 {'region_code': 'EU',
  'region_name': 'Europe',
  'tax_regime_code': 'VAT',
  'default_currency_code': 'EUR',
  'fiscal_calendar_code': 'EU_APR',
  'fiscal_year_start_month': 1,
  'address_rule_set_code': 'EU_COUNTRY',
  'weight_uom_code': 'KG',
  'consent_model_code': 'OPT_IN',
  'retention_months': 120,
  'date_format_pattern': 'DD/MM/YYYY',
  'decimal_separator': ','},
 {'region_code': 'APAC',
  'region_name': 'Asia Pacific',
  'tax_regime_code': 'GST',
  'default_currency_code': 'AUD',
  'fiscal_calendar_code': 'APAC_JUL',
  'fiscal_year_start_month': 4,
  'address_rule_set_code': 'APAC_LOCAL',
  'weight_uom_code': 'KG',
  'consent_model_code': 'OPT_IN',
  'retention_months': 60,
  'date_format_pattern': 'YYYY-MM-DD',
  'decimal_separator': '.'}]

POSTAL_FORMAT_RULES = [{'country_code': 'US',
  'rule_set_code': 'NA_USPS',
  'rule_priority': 100,
  'strip_characters': ' -',
  'upper_case_flag': 1,
  'format_mask': '99999',
  'min_length': 5,
  'max_length': 10,
  'truncate_to_length': 5,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'ZIP5 only; the +4 extension is dropped so the ERP and the OLTP database agree.'},
 {'country_code': 'CA',
  'rule_set_code': 'NA_USPS',
  'rule_priority': 110,
  'strip_characters': '- ',
  'upper_case_flag': 1,
  'format_mask': 'A9A 9A9',
  'min_length': 6,
  'max_length': 7,
  'truncate_to_length': None,
  'insert_space_after': 3,
  'insert_character': ' ',
  'rule_note': 'Six characters with one space inserted after the forward sortation area.'},
 {'country_code': 'GB',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 200,
  'strip_characters': ' ',
  'upper_case_flag': 1,
  'format_mask': 'AA9A 9AA',
  'min_length': 5,
  'max_length': 8,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': ' ',
  'rule_note': 'Variable outward code; the inward code is always the last three characters.'},
 {'country_code': 'IE',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 210,
  'strip_characters': ' ',
  'upper_case_flag': 1,
  'format_mask': 'A99 AAAA',
  'min_length': 7,
  'max_length': 8,
  'truncate_to_length': None,
  'insert_space_after': 3,
  'insert_character': ' ',
  'rule_note': 'Eircode; rows created before 2015 have no postal code at all and are allowed through.'},
 {'country_code': 'NL',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 220,
  'strip_characters': ' ',
  'upper_case_flag': 1,
  'format_mask': '9999AA',
  'min_length': 6,
  'max_length': 7,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Four digits and two letters, upper-cased, no separator.'},
 {'country_code': 'DE',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 230,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '99999',
  'min_length': 5,
  'max_length': 5,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Five digits.'},
 {'country_code': 'FR',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 240,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '99999',
  'min_length': 5,
  'max_length': 5,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Five digits; the leading zero is significant and must not be trimmed.'},
 {'country_code': 'IT',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 250,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '99999',
  'min_length': 5,
  'max_length': 5,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Five digits.'},
 {'country_code': 'ES',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 260,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '99999',
  'min_length': 5,
  'max_length': 5,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Five digits; the first two identify the province.'},
 {'country_code': 'PL',
  'rule_set_code': 'EU_COUNTRY',
  'rule_priority': 270,
  'strip_characters': ' ',
  'upper_case_flag': 0,
  'format_mask': '99-999',
  'min_length': 5,
  'max_length': 6,
  'truncate_to_length': None,
  'insert_space_after': 2,
  'insert_character': '-',
  'rule_note': 'Two digits, a hyphen, three digits.'},
 {'country_code': 'JP',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 300,
  'strip_characters': ' ',
  'upper_case_flag': 0,
  'format_mask': '999-9999',
  'min_length': 7,
  'max_length': 8,
  'truncate_to_length': None,
  'insert_space_after': 3,
  'insert_character': '-',
  'rule_note': 'Seven digits with a hyphen after the third.'},
 {'country_code': 'AU',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 310,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '9999',
  'min_length': 4,
  'max_length': 4,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Four digits.'},
 {'country_code': 'NZ',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 320,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '9999',
  'min_length': 4,
  'max_length': 4,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Four digits.'},
 {'country_code': 'SG',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 330,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '999999',
  'min_length': 6,
  'max_length': 6,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Six digits.'},
 {'country_code': 'CN',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 340,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '999999',
  'min_length': 6,
  'max_length': 6,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Six digits.'},
 {'country_code': 'IN',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 350,
  'strip_characters': ' -',
  'upper_case_flag': 0,
  'format_mask': '999999',
  'min_length': 6,
  'max_length': 6,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Six digit PIN; older rows carry the pre-1972 six digit code unchanged.'},
 {'country_code': 'HK',
  'rule_set_code': 'APAC_LOCAL',
  'rule_priority': 360,
  'strip_characters': ' -',
  'upper_case_flag': 1,
  'format_mask': None,
  'min_length': None,
  'max_length': None,
  'truncate_to_length': None,
  'insert_space_after': None,
  'insert_character': None,
  'rule_note': 'Hong Kong has no postal code; the column is expected to be empty.'}]

STATUS_CODES = [{'status_domain_code': 'ORDER',
  'conformed_status_code': 'DRAFT',
  'conformed_status_name': 'Draft',
  'status_group_code': 'OPEN',
  'sort_order': 10,
  'is_terminal': 0},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'OPEN',
  'conformed_status_name': 'Open',
  'status_group_code': 'OPEN',
  'sort_order': 20,
  'is_terminal': 0},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'BACKORDER',
  'conformed_status_name': 'Backordered',
  'status_group_code': 'OPEN',
  'sort_order': 30,
  'is_terminal': 0},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'PICKING',
  'conformed_status_name': 'Being picked',
  'status_group_code': 'OPEN',
  'sort_order': 40,
  'is_terminal': 0},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'HOLD',
  'conformed_status_name': 'On hold',
  'status_group_code': 'EXCEPTION',
  'sort_order': 50,
  'is_terminal': 0},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'SHIPPED',
  'conformed_status_name': 'Shipped',
  'status_group_code': 'CLOSED',
  'sort_order': 60,
  'is_terminal': 0},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'INVOICED',
  'conformed_status_name': 'Invoiced',
  'status_group_code': 'CLOSED',
  'sort_order': 70,
  'is_terminal': 1},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'CANCELLED',
  'conformed_status_name': 'Cancelled',
  'status_group_code': 'CANCELLED',
  'sort_order': 80,
  'is_terminal': 1},
 {'status_domain_code': 'ORDER',
  'conformed_status_code': 'UNKNOWN',
  'conformed_status_name': 'Unknown order status',
  'status_group_code': 'EXCEPTION',
  'sort_order': 999,
  'is_terminal': 0},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'DRAFT',
  'conformed_status_name': 'Draft',
  'status_group_code': 'OPEN',
  'sort_order': 10,
  'is_terminal': 0},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'ISSUED',
  'conformed_status_name': 'Issued',
  'status_group_code': 'OPEN',
  'sort_order': 20,
  'is_terminal': 0},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'PARTPAID',
  'conformed_status_name': 'Partially paid',
  'status_group_code': 'OPEN',
  'sort_order': 30,
  'is_terminal': 0},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'PAID',
  'conformed_status_name': 'Paid',
  'status_group_code': 'CLOSED',
  'sort_order': 40,
  'is_terminal': 1},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'CREDITED',
  'conformed_status_name': 'Credited',
  'status_group_code': 'CLOSED',
  'sort_order': 50,
  'is_terminal': 1},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'DISPUTED',
  'conformed_status_name': 'Disputed',
  'status_group_code': 'EXCEPTION',
  'sort_order': 60,
  'is_terminal': 0},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'WRITEOFF',
  'conformed_status_name': 'Written off',
  'status_group_code': 'CLOSED',
  'sort_order': 70,
  'is_terminal': 1},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'CANCELLED',
  'conformed_status_name': 'Cancelled',
  'status_group_code': 'CANCELLED',
  'sort_order': 80,
  'is_terminal': 1},
 {'status_domain_code': 'INVOICE',
  'conformed_status_code': 'UNKNOWN',
  'conformed_status_name': 'Unknown invoice status',
  'status_group_code': 'EXCEPTION',
  'sort_order': 999,
  'is_terminal': 0},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'PLANNED',
  'conformed_status_name': 'Planned',
  'status_group_code': 'OPEN',
  'sort_order': 10,
  'is_terminal': 0},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'PICKED',
  'conformed_status_name': 'Picked',
  'status_group_code': 'OPEN',
  'sort_order': 20,
  'is_terminal': 0},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'INTRANSIT',
  'conformed_status_name': 'In transit',
  'status_group_code': 'OPEN',
  'sort_order': 30,
  'is_terminal': 0},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'DELIVERED',
  'conformed_status_name': 'Delivered',
  'status_group_code': 'CLOSED',
  'sort_order': 40,
  'is_terminal': 1},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'FAILED',
  'conformed_status_name': 'Delivery failed',
  'status_group_code': 'EXCEPTION',
  'sort_order': 50,
  'is_terminal': 0},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'RETURNED',
  'conformed_status_name': 'Returned to sender',
  'status_group_code': 'CLOSED',
  'sort_order': 60,
  'is_terminal': 1},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'CANCELLED',
  'conformed_status_name': 'Cancelled',
  'status_group_code': 'CANCELLED',
  'sort_order': 70,
  'is_terminal': 1},
 {'status_domain_code': 'SHIPMENT',
  'conformed_status_code': 'UNKNOWN',
  'conformed_status_name': 'Unknown shipment status',
  'status_group_code': 'EXCEPTION',
  'sort_order': 999,
  'is_terminal': 0},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'DRAFT',
  'conformed_status_name': 'Draft',
  'status_group_code': 'OPEN',
  'sort_order': 10,
  'is_terminal': 0},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'APPROVED',
  'conformed_status_name': 'Approved',
  'status_group_code': 'OPEN',
  'sort_order': 20,
  'is_terminal': 0},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'PARTRECV',
  'conformed_status_name': 'Partially received',
  'status_group_code': 'OPEN',
  'sort_order': 30,
  'is_terminal': 0},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'RECEIVED',
  'conformed_status_name': 'Fully received',
  'status_group_code': 'CLOSED',
  'sort_order': 40,
  'is_terminal': 0},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'CLOSED',
  'conformed_status_name': 'Closed',
  'status_group_code': 'CLOSED',
  'sort_order': 50,
  'is_terminal': 1},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'CANCELLED',
  'conformed_status_name': 'Cancelled',
  'status_group_code': 'CANCELLED',
  'sort_order': 60,
  'is_terminal': 1},
 {'status_domain_code': 'PO',
  'conformed_status_code': 'UNKNOWN',
  'conformed_status_name': 'Unknown purchase order status',
  'status_group_code': 'EXCEPTION',
  'sort_order': 999,
  'is_terminal': 0},
 {'status_domain_code': 'SUPPLIER',
  'conformed_status_code': 'ACTIVE',
  'conformed_status_name': 'Active',
  'status_group_code': 'OPEN',
  'sort_order': 10,
  'is_terminal': 0},
 {'status_domain_code': 'SUPPLIER',
  'conformed_status_code': 'HOLD',
  'conformed_status_name': 'On hold',
  'status_group_code': 'EXCEPTION',
  'sort_order': 20,
  'is_terminal': 0},
 {'status_domain_code': 'SUPPLIER',
  'conformed_status_code': 'PENDING',
  'conformed_status_name': 'Pending approval',
  'status_group_code': 'OPEN',
  'sort_order': 30,
  'is_terminal': 0},
 {'status_domain_code': 'SUPPLIER',
  'conformed_status_code': 'INACTIVE',
  'conformed_status_name': 'Inactive',
  'status_group_code': 'CLOSED',
  'sort_order': 40,
  'is_terminal': 0},
 {'status_domain_code': 'SUPPLIER',
  'conformed_status_code': 'BLOCKED',
  'conformed_status_name': 'Blocked',
  'status_group_code': 'EXCEPTION',
  'sort_order': 50,
  'is_terminal': 1},
 {'status_domain_code': 'SUPPLIER',
  'conformed_status_code': 'UNKNOWN',
  'conformed_status_name': 'Unknown supplier status',
  'status_group_code': 'EXCEPTION',
  'sort_order': 999,
  'is_terminal': 0},
 {'status_domain_code': 'CUSTOMER',
  'conformed_status_code': 'ACTIVE',
  'conformed_status_name': 'Active',
  'status_group_code': 'OPEN',
  'sort_order': 10,
  'is_terminal': 0},
 {'status_domain_code': 'CUSTOMER',
  'conformed_status_code': 'HOLD',
  'conformed_status_name': 'Credit hold',
  'status_group_code': 'EXCEPTION',
  'sort_order': 20,
  'is_terminal': 0},
 {'status_domain_code': 'CUSTOMER',
  'conformed_status_code': 'PROSPECT',
  'conformed_status_name': 'Prospect',
  'status_group_code': 'OPEN',
  'sort_order': 30,
  'is_terminal': 0},
 {'status_domain_code': 'CUSTOMER',
  'conformed_status_code': 'INACTIVE',
  'conformed_status_name': 'Inactive',
  'status_group_code': 'CLOSED',
  'sort_order': 40,
  'is_terminal': 0},
 {'status_domain_code': 'CUSTOMER',
  'conformed_status_code': 'CLOSED',
  'conformed_status_name': 'Account closed',
  'status_group_code': 'CLOSED',
  'sort_order': 50,
  'is_terminal': 1},
 {'status_domain_code': 'CUSTOMER',
  'conformed_status_code': 'UNKNOWN',
  'conformed_status_name': 'Unknown customer status',
  'status_group_code': 'EXCEPTION',
  'sort_order': 999,
  'is_terminal': 0}]

REASON_CODES = [{'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'DAMAGED',
  'conformed_reason_name': 'Damaged in transit',
  'reason_group_code': 'QUALITY',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'DEFECTIVE',
  'conformed_reason_name': 'Defective on arrival',
  'reason_group_code': 'QUALITY',
  'is_customer_fault': 0,
  'is_supplier_fault': 1,
  'requires_approval': 0},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'WRONGITEM',
  'conformed_reason_name': 'Wrong item shipped',
  'reason_group_code': 'FULFILMENT',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'OVERSHIP',
  'conformed_reason_name': 'Over-shipment',
  'reason_group_code': 'FULFILMENT',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'NOTNEEDED',
  'conformed_reason_name': 'No longer required',
  'reason_group_code': 'COMMERCIAL',
  'is_customer_fault': 1,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'LATE',
  'conformed_reason_name': 'Delivered too late',
  'reason_group_code': 'FULFILMENT',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'EXPIRED',
  'conformed_reason_name': 'Past shelf life on arrival',
  'reason_group_code': 'QUALITY',
  'is_customer_fault': 0,
  'is_supplier_fault': 1,
  'requires_approval': 1},
 {'reason_domain_code': 'RETURN',
  'conformed_reason_code': 'UNKNOWN',
  'conformed_reason_name': 'Unknown return reason',
  'reason_group_code': 'EXCEPTION',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 1},
 {'reason_domain_code': 'CREDIT',
  'conformed_reason_code': 'PRICEERR',
  'conformed_reason_name': 'Pricing error',
  'reason_group_code': 'BILLING',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'CREDIT',
  'conformed_reason_code': 'GOODWILL',
  'conformed_reason_name': 'Goodwill gesture',
  'reason_group_code': 'COMMERCIAL',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'CREDIT',
  'conformed_reason_code': 'RETURNCR',
  'conformed_reason_name': 'Credit against a return',
  'reason_group_code': 'RETURNS',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 0},
 {'reason_domain_code': 'CREDIT',
  'conformed_reason_code': 'SHORTSHIP',
  'conformed_reason_name': 'Short shipment',
  'reason_group_code': 'FULFILMENT',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'CREDIT',
  'conformed_reason_code': 'TAXCORR',
  'conformed_reason_name': 'Tax correction',
  'reason_group_code': 'BILLING',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'CREDIT',
  'conformed_reason_code': 'UNKNOWN',
  'conformed_reason_name': 'Unknown credit reason',
  'reason_group_code': 'EXCEPTION',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 1},
 {'reason_domain_code': 'HOLD',
  'conformed_reason_code': 'CREDIT',
  'conformed_reason_name': 'Credit limit exceeded',
  'reason_group_code': 'FINANCE',
  'is_customer_fault': 1,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'HOLD',
  'conformed_reason_code': 'PRICE',
  'conformed_reason_name': 'Price awaiting approval',
  'reason_group_code': 'COMMERCIAL',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'HOLD',
  'conformed_reason_code': 'QUALITY',
  'conformed_reason_name': 'Quality inspection',
  'reason_group_code': 'QUALITY',
  'is_customer_fault': 0,
  'is_supplier_fault': 1,
  'requires_approval': 0},
 {'reason_domain_code': 'HOLD',
  'conformed_reason_code': 'COMPLIANCE',
  'conformed_reason_name': 'Compliance review',
  'reason_group_code': 'COMPLIANCE',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 1},
 {'reason_domain_code': 'HOLD',
  'conformed_reason_code': 'UNKNOWN',
  'conformed_reason_name': 'Unknown hold reason',
  'reason_group_code': 'EXCEPTION',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 1},
 {'reason_domain_code': 'ADJUSTMENT',
  'conformed_reason_code': 'CYCLECOUNT',
  'conformed_reason_name': 'Cycle count correction',
  'reason_group_code': 'INVENTORY',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'ADJUSTMENT',
  'conformed_reason_code': 'SHRINKAGE',
  'conformed_reason_name': 'Shrinkage',
  'reason_group_code': 'INVENTORY',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'ADJUSTMENT',
  'conformed_reason_code': 'DAMAGE',
  'conformed_reason_name': 'Damaged in the warehouse',
  'reason_group_code': 'INVENTORY',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 0},
 {'reason_domain_code': 'ADJUSTMENT',
  'conformed_reason_code': 'REVALUE',
  'conformed_reason_name': 'Stock revaluation',
  'reason_group_code': 'FINANCE',
  'is_customer_fault': 0,
  'is_supplier_fault': 0,
  'requires_approval': 1},
 {'reason_domain_code': 'ADJUSTMENT',
  'conformed_reason_code': 'UNKNOWN',
  'conformed_reason_name': 'Unknown adjustment reason',
  'reason_group_code': 'EXCEPTION',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 1},
 {'reason_domain_code': 'REJECT',
  'conformed_reason_code': 'QUALITY',
  'conformed_reason_name': 'Failed goods-in inspection',
  'reason_group_code': 'QUALITY',
  'is_customer_fault': 0,
  'is_supplier_fault': 1,
  'requires_approval': 0},
 {'reason_domain_code': 'REJECT',
  'conformed_reason_code': 'QUANTITY',
  'conformed_reason_name': 'Quantity does not match the order',
  'reason_group_code': 'FULFILMENT',
  'is_customer_fault': 0,
  'is_supplier_fault': 1,
  'requires_approval': 0},
 {'reason_domain_code': 'REJECT',
  'conformed_reason_code': 'DOCUMENT',
  'conformed_reason_name': 'Paperwork missing or wrong',
  'reason_group_code': 'COMPLIANCE',
  'is_customer_fault': 0,
  'is_supplier_fault': 1,
  'requires_approval': 0},
 {'reason_domain_code': 'REJECT',
  'conformed_reason_code': 'UNKNOWN',
  'conformed_reason_name': 'Unknown rejection reason',
  'reason_group_code': 'EXCEPTION',
  'is_customer_fault': None,
  'is_supplier_fault': None,
  'requires_approval': 1}]

CODE_CROSSWALK = [{'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'ENT',
  'source_code_description': 'Entered',
  'conformed_code_value': 'OPEN',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'BOOK',
  'source_code_description': 'Booked',
  'conformed_code_value': 'OPEN',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'BO',
  'source_code_description': 'Backordered',
  'conformed_code_value': 'BACKORDER',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'HOLD',
  'source_code_description': 'On hold',
  'conformed_code_value': 'HOLD',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'SHIP',
  'source_code_description': 'Shipped',
  'conformed_code_value': 'SHIPPED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'INV',
  'source_code_description': 'Invoiced',
  'conformed_code_value': 'INVOICED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CANC',
  'source_code_description': 'Cancelled',
  'conformed_code_value': 'CANCELLED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'UNDER DEVELOPMENT',
  'source_code_description': 'Under development',
  'conformed_code_value': 'DRAFT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'OPEN',
  'source_code_description': 'Open',
  'conformed_code_value': 'OPEN',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'BACKORDER',
  'source_code_description': 'Backorder',
  'conformed_code_value': 'BACKORDER',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PICKING',
  'source_code_description': 'Being picked',
  'conformed_code_value': 'PICKING',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PICKED',
  'source_code_description': 'Picked',
  'conformed_code_value': 'PICKING',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'INVOICED',
  'source_code_description': 'Invoiced',
  'conformed_code_value': 'INVOICED',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'ORDER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'CANCELLED',
  'source_code_description': 'Cancelled',
  'conformed_code_value': 'CANCELLED',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'DRAFT',
  'source_code_description': 'Draft',
  'conformed_code_value': 'DRAFT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'APPR',
  'source_code_description': 'Approved and issued',
  'conformed_code_value': 'ISSUED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'PPAY',
  'source_code_description': 'Partially paid',
  'conformed_code_value': 'PARTPAID',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'PAID',
  'source_code_description': 'Paid in full',
  'conformed_code_value': 'PAID',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'DISP',
  'source_code_description': 'In dispute',
  'conformed_code_value': 'DISPUTED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'WOFF',
  'source_code_description': 'Written off',
  'conformed_code_value': 'WRITEOFF',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CANC',
  'source_code_description': 'Cancelled',
  'conformed_code_value': 'CANCELLED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'ISSUED',
  'source_code_description': 'Issued',
  'conformed_code_value': 'ISSUED',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PART PAID',
  'source_code_description': 'Part paid',
  'conformed_code_value': 'PARTPAID',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PAID',
  'source_code_description': 'Paid',
  'conformed_code_value': 'PAID',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'INVOICE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'CREDITED',
  'source_code_description': 'Credited',
  'conformed_code_value': 'CREDITED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SHIPMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PLANNED',
  'source_code_description': 'Planned',
  'conformed_code_value': 'PLANNED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SHIPMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'IN TRANSIT',
  'source_code_description': 'In transit',
  'conformed_code_value': 'INTRANSIT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SHIPMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'DELIVERED',
  'source_code_description': 'Delivered',
  'conformed_code_value': 'DELIVERED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SHIPMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'FAILED',
  'source_code_description': 'Delivery failed',
  'conformed_code_value': 'FAILED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SHIPMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'RTS',
  'source_code_description': 'Returned to sender',
  'conformed_code_value': 'RETURNED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SHIPMENT',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'DLV',
  'source_code_description': 'Delivered',
  'conformed_code_value': 'DELIVERED',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'PO',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'INCOMPLETE',
  'source_code_description': 'Incomplete',
  'conformed_code_value': 'DRAFT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PO',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'APPR',
  'source_code_description': 'Approved',
  'conformed_code_value': 'APPROVED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PO',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'PREC',
  'source_code_description': 'Partially received',
  'conformed_code_value': 'PARTRECV',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PO',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'RECV',
  'source_code_description': 'Received',
  'conformed_code_value': 'RECEIVED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PO',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CLSD',
  'source_code_description': 'Closed',
  'conformed_code_value': 'CLOSED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PO',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CANC',
  'source_code_description': 'Cancelled',
  'conformed_code_value': 'CANCELLED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SUPPLIER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'A',
  'source_code_description': 'Active',
  'conformed_code_value': 'ACTIVE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SUPPLIER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'I',
  'source_code_description': 'Inactive',
  'conformed_code_value': 'INACTIVE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SUPPLIER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'H',
  'source_code_description': 'On hold',
  'conformed_code_value': 'HOLD',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SUPPLIER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'P',
  'source_code_description': 'Pending approval',
  'conformed_code_value': 'PENDING',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SUPPLIER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'X',
  'source_code_description': 'Blocked',
  'conformed_code_value': 'BLOCKED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CUSTOMER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'A',
  'source_code_description': 'Active',
  'conformed_code_value': 'ACTIVE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CUSTOMER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'I',
  'source_code_description': 'Inactive',
  'conformed_code_value': 'INACTIVE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CUSTOMER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'H',
  'source_code_description': 'Credit hold',
  'conformed_code_value': 'HOLD',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CUSTOMER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'P',
  'source_code_description': 'Prospect',
  'conformed_code_value': 'PROSPECT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CUSTOMER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'X',
  'source_code_description': 'Account closed',
  'conformed_code_value': 'CLOSED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'DAMAGED',
  'source_code_description': 'Damaged',
  'conformed_code_value': 'DAMAGED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'FAULTY',
  'source_code_description': 'Faulty',
  'conformed_code_value': 'DEFECTIVE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'WRONG ITEM',
  'source_code_description': 'Wrong item',
  'conformed_code_value': 'WRONGITEM',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'TOO MANY',
  'source_code_description': 'Too many delivered',
  'conformed_code_value': 'OVERSHIP',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'NOT REQUIRED',
  'source_code_description': 'No longer required',
  'conformed_code_value': 'NOTNEEDED',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'LATE',
  'source_code_description': 'Arrived late',
  'conformed_code_value': 'LATE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'RTN-DMG',
  'source_code_description': 'Damaged on receipt',
  'conformed_code_value': 'DAMAGED',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'RETURN',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'RTN-QLY',
  'source_code_description': 'Quality failure',
  'conformed_code_value': 'DEFECTIVE',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'CREDIT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PRICE',
  'source_code_description': 'Price adjustment',
  'conformed_code_value': 'PRICEERR',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CREDIT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'GOODWILL',
  'source_code_description': 'Goodwill',
  'conformed_code_value': 'GOODWILL',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CREDIT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'RETURN',
  'source_code_description': 'Against a return',
  'conformed_code_value': 'RETURNCR',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CREDIT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'SHORT',
  'source_code_description': 'Short delivery',
  'conformed_code_value': 'SHORTSHIP',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CREDIT',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CM-TAX',
  'source_code_description': 'Tax correction',
  'conformed_code_value': 'TAXCORR',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'HOLD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CRED',
  'source_code_description': 'Credit limit',
  'conformed_code_value': 'CREDIT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'HOLD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'PRIC',
  'source_code_description': 'Price approval',
  'conformed_code_value': 'PRICE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'HOLD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'QUAL',
  'source_code_description': 'Quality inspection',
  'conformed_code_value': 'QUALITY',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'HOLD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'COMP',
  'source_code_description': 'Compliance review',
  'conformed_code_value': 'COMPLIANCE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ADJUSTMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'STOCKTAKE',
  'source_code_description': 'Stocktake correction',
  'conformed_code_value': 'CYCLECOUNT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ADJUSTMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'SHRINK',
  'source_code_description': 'Shrinkage',
  'conformed_code_value': 'SHRINKAGE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ADJUSTMENT',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'DAMAGE',
  'source_code_description': 'Damaged in warehouse',
  'conformed_code_value': 'DAMAGE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'ADJUSTMENT',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'REVAL',
  'source_code_description': 'Revaluation',
  'conformed_code_value': 'REVALUE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REJECT',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'REJ-QLY',
  'source_code_description': 'Failed inspection',
  'conformed_code_value': 'QUALITY',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REJECT',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'REJ-QTY',
  'source_code_description': 'Quantity mismatch',
  'conformed_code_value': 'QUANTITY',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REJECT',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'REJ-DOC',
  'source_code_description': 'Documentation',
  'conformed_code_value': 'DOCUMENT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REGION',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'AMER',
  'source_code_description': 'Americas',
  'conformed_code_value': 'NA',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REGION',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'NA',
  'source_code_description': 'North America',
  'conformed_code_value': 'NA',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'REGION',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'EMEA',
  'source_code_description': 'Europe, Middle East and Africa',
  'conformed_code_value': 'EU',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REGION',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'EU',
  'source_code_description': 'Europe',
  'conformed_code_value': 'EU',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'REGION',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'APJ',
  'source_code_description': 'Asia Pacific and Japan',
  'conformed_code_value': 'APAC',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'REGION',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'APAC',
  'source_code_description': 'Asia Pacific',
  'conformed_code_value': 'APAC',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'COUNTRY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'USA',
  'source_code_description': 'United States (ISO3)',
  'conformed_code_value': 'US',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COUNTRY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'GBR',
  'source_code_description': 'United Kingdom (ISO3)',
  'conformed_code_value': 'GB',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COUNTRY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'UK',
  'source_code_description': 'United Kingdom (legacy)',
  'conformed_code_value': 'GB',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'COUNTRY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'DEU',
  'source_code_description': 'Germany (ISO3)',
  'conformed_code_value': 'DE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COUNTRY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'AUS',
  'source_code_description': 'Australia (ISO3)',
  'conformed_code_value': 'AU',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COUNTRY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'JPN',
  'source_code_description': 'Japan (ISO3)',
  'conformed_code_value': 'JP',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CURRENCY',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'US$',
  'source_code_description': 'US dollar',
  'conformed_code_value': 'USD',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CURRENCY',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'STG',
  'source_code_description': 'Pound sterling',
  'conformed_code_value': 'GBP',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CURRENCY',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'DEM',
  'source_code_description': 'Deutsche mark (retired)',
  'conformed_code_value': 'EUR',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'UOM',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'EACH',
  'source_code_description': 'Each',
  'conformed_code_value': 'EA',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'UOM',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CASE',
  'source_code_description': 'Case',
  'conformed_code_value': 'CS',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'UOM',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'PALLET',
  'source_code_description': 'Pallet',
  'conformed_code_value': 'PLT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'UOM',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'KILO',
  'source_code_description': 'Kilogram',
  'conformed_code_value': 'KG',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'UOM',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'POUND',
  'source_code_description': 'Pound',
  'conformed_code_value': 'LB',
  'region_code': 'NA',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'UOM',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PACKET',
  'source_code_description': 'Packet',
  'conformed_code_value': 'PKT',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'UOM',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'EACH',
  'source_code_description': 'Each',
  'conformed_code_value': 'EA',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'PAYMENT_METHOD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CHECK',
  'source_code_description': 'Check',
  'conformed_code_value': 'CHQ',
  'region_code': 'NA',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_METHOD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'CHEQUE',
  'source_code_description': 'Cheque',
  'conformed_code_value': 'CHQ',
  'region_code': 'EU',
  'is_default_for_conformed': 0},
 {'code_domain_code': 'PAYMENT_METHOD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'EFT',
  'source_code_description': 'Electronic funds transfer',
  'conformed_code_value': 'BANK',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_METHOD',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'DD',
  'source_code_description': 'Direct debit',
  'conformed_code_value': 'DDEBIT',
  'region_code': 'EU',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_METHOD',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'CREDIT CARD',
  'source_code_description': 'Credit card',
  'conformed_code_value': 'CARD',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_METHOD',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'CASH',
  'source_code_description': 'Cash',
  'conformed_code_value': 'CASH',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_TERMS',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'NET30',
  'source_code_description': 'Net 30 days',
  'conformed_code_value': 'NET30',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_TERMS',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'NET60',
  'source_code_description': 'Net 60 days',
  'conformed_code_value': 'NET60',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_TERMS',
  'source_system_code': 'ORA_ERP',
  'source_code_value': '2/10NET30',
  'source_code_description': '2 percent 10 days, net 30',
  'conformed_code_value': 'DISC210',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_TERMS',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'EOM',
  'source_code_description': 'End of month',
  'conformed_code_value': 'EOM',
  'region_code': 'EU',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_TERMS',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': '7 DAYS',
  'source_code_description': 'Seven days',
  'conformed_code_value': 'NET07',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'PAYMENT_TERMS',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': '30 DAYS',
  'source_code_description': 'Thirty days',
  'conformed_code_value': 'NET30',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'TRANSACTION_TYPE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'STOCK ISSUE',
  'source_code_description': 'Stock issue',
  'conformed_code_value': 'SALE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'TRANSACTION_TYPE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'STOCK RECEIPT',
  'source_code_description': 'Stock receipt',
  'conformed_code_value': 'PURCH',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'TRANSACTION_TYPE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'ADJUSTMENT',
  'source_code_description': 'Adjustment',
  'conformed_code_value': 'ADJ',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'TRANSACTION_TYPE',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'CUSTOMER RETURN',
  'source_code_description': 'Customer return',
  'conformed_code_value': 'RET',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'TRANSACTION_TYPE',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'MISC ISSUE',
  'source_code_description': 'Miscellaneous issue',
  'conformed_code_value': 'ADJ',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'SALES_CHANNEL',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'DIR',
  'source_code_description': 'Direct sales force',
  'conformed_code_value': 'DIRECT',
  'region_code': 'NA',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SALES_CHANNEL',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'DIR',
  'source_code_description': 'Distributor',
  'conformed_code_value': 'PARTNER',
  'region_code': 'APAC',
  'is_default_for_conformed': 0},
 {'code_domain_code': 'SALES_CHANNEL',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'WEB',
  'source_code_description': 'Web store',
  'conformed_code_value': 'ONLINE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SALES_CHANNEL',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PHONE',
  'source_code_description': 'Telesales',
  'conformed_code_value': 'TELE',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'SALES_CHANNEL',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'WHSL',
  'source_code_description': 'Wholesale',
  'conformed_code_value': 'PARTNER',
  'region_code': None,
  'is_default_for_conformed': 0},
 {'code_domain_code': 'LOYALTY_TIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'BRONZE',
  'source_code_description': 'Bronze',
  'conformed_code_value': 'TIER1',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'LOYALTY_TIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'SILVER',
  'source_code_description': 'Silver',
  'conformed_code_value': 'TIER2',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'LOYALTY_TIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'GOLD',
  'source_code_description': 'Gold',
  'conformed_code_value': 'TIER3',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'LOYALTY_TIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'PLATINUM',
  'source_code_description': 'Platinum',
  'conformed_code_value': 'TIER4',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CARRIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'FEDEX',
  'source_code_description': 'FedEx',
  'conformed_code_value': 'FDX',
  'region_code': 'NA',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CARRIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'UPS',
  'source_code_description': 'United Parcel Service',
  'conformed_code_value': 'UPS',
  'region_code': 'NA',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CARRIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'DHL',
  'source_code_description': 'DHL',
  'conformed_code_value': 'DHL',
  'region_code': 'EU',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CARRIER',
  'source_system_code': 'WWI_OLTP',
  'source_code_value': 'OWN FLEET',
  'source_code_description': 'Own fleet',
  'conformed_code_value': 'OWN',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'CARRIER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': 'TOLL',
  'source_code_description': 'Toll Group',
  'conformed_code_value': 'TOLL',
  'region_code': 'APAC',
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COST_CENTER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': '1000',
  'source_code_description': 'Corporate',
  'conformed_code_value': 'CORP',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COST_CENTER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': '2000',
  'source_code_description': 'Sales',
  'conformed_code_value': 'SALES',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COST_CENTER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': '3000',
  'source_code_description': 'Warehouse operations',
  'conformed_code_value': 'OPS',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COST_CENTER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': '4000',
  'source_code_description': 'Logistics',
  'conformed_code_value': 'LOGI',
  'region_code': None,
  'is_default_for_conformed': 1},
 {'code_domain_code': 'COST_CENTER',
  'source_system_code': 'ORA_ERP',
  'source_code_value': '9999',
  'source_code_description': 'Suspense',
  'conformed_code_value': 'SUSP',
  'region_code': None,
  'is_default_for_conformed': 1}]

