"""Oracle SQL*Loader artefacts for the generated extracts.

One ``.ctl`` per Oracle table, derived from the conformed
:class:`~wwigen.schema.TableSpec` - which is the deployed table's own column
vocabulary, in the deployed table's own order - plus one PowerShell driver that
runs them in foreign-key order so a child never loads before its parent.

Two details the first live load fell over:

* a nullable ``DATE`` reaches SQL*Loader as an empty field, which is a value of
  the wrong length rather than a null unless the field says ``NULLIF ... =
  BLANKS``;
* the data file is resolved once, from the control file's own directory, so the
  path cannot pick up the traversal twice.

Each schema is loaded as its own owner, whose password comes from the
``WWI_<SCHEMA>_SECRET`` variable the schema DDL already uses. No credential is
written into a generated artefact.

Nothing here has been run against Oracle.
"""

from __future__ import annotations

import os

from .. import canon, schema

HEADER = """-- SQL*Loader control file for {qualified}
-- Generated by generators/generate.py from the deployed table contract.
-- Target: Oracle {qualified} in the ERP database (service $ORACLE_SERVICE).
-- Data file: {datafile}
-- Run with: sqlldr control={control} log={log}
"""


def field_clause(column: schema.Column) -> str:
    """The field definition, with the null handling the column needs."""
    clause = column.sqlloader_type
    if column.type in (schema.DATE, schema.TIMESTAMP) and column.nullable:
        clause = "%s NULLIF %s=BLANKS" % (clause, column.name)
    return clause


def control_text(spec: schema.TableSpec, data_relative: str) -> str:
    control_name = "%s.ctl" % spec.file_stem
    lines = [HEADER.format(qualified=spec.qualified_name,
                           datafile=data_relative,
                           control=control_name,
                           log="%s.log" % spec.file_stem)]
    lines.append("OPTIONS (ERRORS=10000, ROWS=50000, BINDSIZE=16777216, READSIZE=16777216)")
    lines.append("LOAD DATA")
    lines.append("CHARACTERSET AL32UTF8")
    lines.append("INFILE '%s'" % data_relative)
    lines.append("BADFILE '%s.bad'" % spec.file_stem)
    lines.append("DISCARDFILE '%s.dsc'" % spec.file_stem)
    lines.append("APPEND")
    lines.append("INTO TABLE %s" % spec.qualified_name)
    lines.append("FIELDS TERMINATED BY '%s'" % spec.delimiter)
    lines.append("TRAILING NULLCOLS")
    lines.append("(")
    body = ["    %-32s %s" % (column.name, field_clause(column))
            for column in spec.columns]
    lines.append(",\n".join(body))
    lines.append(")")
    return "\n".join(lines) + "\n"


def _parents(tables, key):
    table = tables.get(key)
    return () if table is None else tuple(table.foreign_keys.values())


def load_order(specs) -> list:
    """The specs in foreign-key order: every parent before its children.

    The graph is the one declared in ``oracle/tables``; a cycle - the estate has
    a couple, through optional self-references - keeps the alphabetical order it
    arrived in rather than aborting the emit.
    """
    keys = {"%s.%s" % (spec.schema, spec.name): spec for spec in specs}
    tables = canon.oracle_tables()
    pending = sorted(keys)
    ordered, placed = [], set()
    while pending:
        ready = [key for key in pending
                 if all(parent in placed or parent not in keys
                        for parent, _column in
                        _parents(tables, key) if parent != key)]
        if not ready:
            ready = pending                     # cycle: keep a stable order
        for key in ready:
            ordered.append(keys[key])
            placed.add(key)
        pending = [key for key in pending if key not in placed]
    return ordered


DRIVER_HEADER = '''#Requires -Version 5.1
<#
.SYNOPSIS
    Load the generated Oracle extracts with SQL*Loader, in foreign-key order.

.DESCRIPTION
    Each schema is loaded as its own owner. Connection details and the schema
    passwords come from the environment and no credential is stored here:

        ORACLE_HOST ORACLE_PORT ORACLE_SERVICE
        WWI_MDM_SECRET WWI_PROC_SECRET WWI_FIN_SECRET WWI_REF_SECRET
        WWI_AUDIT_SECRET

    Nothing in this repository has been run against an Oracle instance.
#>
[CmdletBinding()]
param(
    # Print the loads and their resolved files without running them.
    [switch] $ListOnly
)

$ErrorActionPreference = 'Stop'

foreach ($name in 'ORACLE_HOST', 'ORACLE_PORT', 'ORACLE_SERVICE') {
    if (-not (Test-Path "env:$name")) { throw "set $name" }
}

$LoaderRoot = $PSScriptRoot
$Service = '//{0}:{1}/{2}' -f $env:ORACLE_HOST, $env:ORACLE_PORT, $env:ORACLE_SERVICE

$Loads = @(
'''

DRIVER_FOOTER = ''')

$failed = @()
foreach ($load in $Loads) {
    $secretName = '{0}_SECRET' -f $load.Schema
    if (-not (Test-Path "env:$secretName")) { throw "set $secretName" }
    $control = Join-Path $LoaderRoot (Join-Path $load.Schema $load.Control)
    if (-not (Test-Path -LiteralPath $control)) {
        throw "control file not found: $control"
    }
    $data = Join-Path (Split-Path -Parent $control) $load.Data
    if (-not (Test-Path -LiteralPath $data)) {
        throw "extract file not found: $data"
    }
    if ($ListOnly) {
        '{0,-40} {1}' -f $load.Table, (Resolve-Path -LiteralPath $data).Path
        continue
    }
    Write-Host ("loading {0}" -f $load.Table)
    $connect = '{0}/{1}@{2}' -f $load.Schema, (Get-Item "env:$secretName").Value, $Service
    Push-Location (Split-Path -Parent $control)
    try {
        & sqlldr $connect control=$load.Control log=$load.Log
    } finally {
        Pop-Location
        Remove-Variable connect
    }
    if ($LASTEXITCODE -gt 1) {
        $failed += ('{0} (sqlldr exit {1})' -f $load.Table, $LASTEXITCODE)
    }
}

if ($failed) {
    throw ("sqlldr failed for: " + ($failed -join '; '))
}
Write-Host 'oracle extracts loaded'
'''


def _entry(spec: schema.TableSpec, data_relative: str) -> str:
    return ("    @{ Table = '%s'; Schema = '%s'; Control = '%s.ctl'; "
            "Log = '%s.log'; Data = '%s' }"
            % (spec.qualified_name, spec.schema, spec.file_stem,
               spec.file_stem, data_relative.replace("/", "\\")))


def driver_text(specs, data_relative) -> str:
    body = "\n".join(_entry(spec, data_relative(spec)) for spec in specs)
    return DRIVER_HEADER + body + "\n" + DRIVER_FOOTER


def emit(output_dir: str, specs) -> list:
    """Write one control file per Oracle spec plus the ordered driver."""
    written = []
    oracle_specs = [spec for spec in specs if spec.system == schema.ORACLE]
    if not oracle_specs:
        return written

    root = os.path.join(output_dir, "loaders", "oracle")

    def data_relative(spec):
        directory = os.path.join(root, spec.schema)
        relative = os.path.relpath(
            os.path.join(output_dir, "data", spec.relative_path()), directory)
        return relative.replace(os.sep, "/")

    for spec in sorted(oracle_specs, key=lambda item: item.key):
        directory = os.path.join(root, spec.schema)
        os.makedirs(directory, exist_ok=True)
        path = os.path.join(directory, "%s.ctl" % spec.file_stem)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(control_text(spec, data_relative(spec)))
        written.append(os.path.relpath(path, output_dir).replace(os.sep, "/"))

    driver = os.path.join(root, "Load-Oracle.ps1")
    with open(driver, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(driver_text(load_order(oracle_specs), data_relative))
    written.append(os.path.relpath(driver, output_dir).replace(os.sep, "/"))
    return sorted(written)
