"""Oracle SQL*Loader control-file emitter.

One ``.ctl`` per Oracle table, derived from the same :class:`TableSpec` that
produced the data file, plus one driver shell script per schema that runs them
in dependency order. The scripts take the connection details from the
documented environment variables and never contain a credential.

Nothing here has been run against Oracle; the control files are emitted
statically from the column declarations.
"""

from __future__ import annotations

import os

from .. import schema

HEADER = """-- SQL*Loader control file for {qualified}
-- Generated by generators/generate.py from the table specification.
-- Target: Oracle {qualified} in the ERP database (service $ORACLE_SERVICE).
-- Data file: {datafile}
-- Run with: sqlldr control={control} log={log}
"""


def control_text(spec: schema.TableSpec, data_relative: str) -> str:
    control_name = "%s.ctl" % spec.file_stem
    lines = [HEADER.format(qualified=spec.qualified_name,
                           datafile=data_relative,
                           control=control_name,
                           log="%s.log" % spec.file_stem)]
    lines.append("OPTIONS (ERRORS=10000, ROWS=50000, BINDSIZE=16777216, READSIZE=16777216)")
    lines.append("LOAD DATA")
    lines.append("CHARACTERSET AL32UTF8")
    lines.append("INFILE '%s'" % data_relative)
    lines.append("BADFILE '%s.bad'" % spec.file_stem)
    lines.append("DISCARDFILE '%s.dsc'" % spec.file_stem)
    lines.append("APPEND")
    lines.append("INTO TABLE %s" % spec.qualified_name)
    lines.append("FIELDS TERMINATED BY '%s'" % spec.delimiter)
    lines.append("TRAILING NULLCOLS")
    lines.append("(")
    body = []
    for column in spec.columns:
        body.append("    %-32s %s" % (column.name, column.sqlloader_type))
    lines.append(",\n".join(body))
    lines.append(")")
    return "\n".join(lines) + "\n"


DRIVER_HEADER = """#!/bin/sh
# Load the generated Oracle extract files for the {schema_name} schema.
# Connection details come from the environment; no credential is stored here.
#   ORACLE_HOST ORACLE_PORT ORACLE_SERVICE ORACLE_USER ORACLE_PASSWORD
# Nothing in this repository has been run against an Oracle instance.
set -e

: "${{ORACLE_HOST:?set ORACLE_HOST}}"
: "${{ORACLE_PORT:?set ORACLE_PORT}}"
: "${{ORACLE_SERVICE:?set ORACLE_SERVICE}}"
: "${{ORACLE_USER:?set ORACLE_USER}}"
: "${{ORACLE_PASSWORD:?set ORACLE_PASSWORD}}"

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
CONNECT="${{ORACLE_USER}}/${{ORACLE_PASSWORD}}@//${{ORACLE_HOST}}:${{ORACLE_PORT}}/${{ORACLE_SERVICE}}"

cd "${{BASE_DIR}}"
"""


def driver_text(schema_name: str, specs) -> str:
    lines = [DRIVER_HEADER.format(schema_name=schema_name)]
    for spec in specs:
        lines.append('echo "loading %s"' % spec.qualified_name)
        lines.append('sqlldr "${CONNECT}" control="%s.ctl" log="%s.log" direct=true'
                     % (spec.file_stem, spec.file_stem))
        lines.append("")
    lines.append('echo "%s complete"' % schema_name)
    return "\n".join(lines) + "\n"


def emit(output_dir: str, specs) -> list:
    """Write one control file per Oracle spec plus a driver script per schema."""
    written = []
    by_schema = {}
    for spec in specs:
        if spec.system != schema.ORACLE:
            continue
        by_schema.setdefault(spec.schema, []).append(spec)

    for schema_name in sorted(by_schema):
        schema_specs = sorted(by_schema[schema_name], key=lambda item: item.name)
        directory = os.path.join(output_dir, "loaders", "oracle", schema_name)
        os.makedirs(directory, exist_ok=True)
        for spec in schema_specs:
            data_relative = os.path.relpath(
                os.path.join(output_dir, "data", spec.relative_path()), directory)
            path = os.path.join(directory, "%s.ctl" % spec.file_stem)
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(control_text(spec, data_relative.replace(os.sep, "/")))
            written.append(os.path.relpath(path, output_dir).replace(os.sep, "/"))
        driver = os.path.join(directory, "load_%s.sh" % schema_name.lower())
        with open(driver, "w", encoding="utf-8") as handle:
            handle.write(driver_text(schema_name, schema_specs))
        os.chmod(driver, 0o755)
        written.append(os.path.relpath(driver, output_dir).replace(os.sep, "/"))
    return sorted(written)
