/* =====================================================================
 * Object       : Reference content - WWI_REF.REGION_REF, WWI_REF.COUNTRY_REF
 * Schema       : WWI_REF (Oracle ERP - WWIGERP)
 * Deploy order : 100 (first reference content script)
 * Depends on   : oracle/tables/WWI_REF.REGION_REF.sql,
 *                oracle/tables/WWI_REF.COUNTRY_REF.sql
 * Called by    : run once per environment after the table DDL; re-runnable
 *                only after deleting the rows it inserts
 *
 * The three operating regions and the countries they trade in. The regional
 * rows carry the divergence the rest of the estate keys off: sales tax in NA,
 * VAT in EU, GST in APAC; three different fiscal calendars; three different
 * consent regimes and retention periods.
 *
 * LATAM was folded into NA in 2013 and EMEA_OLD into EU in 2009. Both rows
 * are kept inactive because pre-merge history still carries the codes.
 * ===================================================================== */

SET DEFINE OFF

INSERT INTO WWI_REF.REGION_REF
    (REGION_CD, REGION_NAME, REPORTING_CURR_CD, FISCAL_YEAR_START_MONTH,
     FISCAL_CALENDAR_CD, TAX_REGIME_CD, ADDRESS_FORMAT_CD, POSTAL_FORMAT_CD,
     DATE_FORMAT_MASK, DEFAULT_LANGUAGE_CD, CONSENT_REGIME_CD, RETENTION_MONTHS,
     TIMEZONE_TXT, ACTIVE_FLG, RETIRED_DT)
VALUES
    ('NA', 'North America', 'USD', 1,
     'NA_CAL', 'SALES', 'US_STREET', 'ZIP5_4',
     'MM/DD/YYYY', 'en-US', 'CAN_SPAM', 84,
     'America/Chicago', 'Y', NULL)
/

INSERT INTO WWI_REF.REGION_REF
    (REGION_CD, REGION_NAME, REPORTING_CURR_CD, FISCAL_YEAR_START_MONTH,
     FISCAL_CALENDAR_CD, TAX_REGIME_CD, ADDRESS_FORMAT_CD, POSTAL_FORMAT_CD,
     DATE_FORMAT_MASK, DEFAULT_LANGUAGE_CD, CONSENT_REGIME_CD, RETENTION_MONTHS,
     TIMEZONE_TXT, ACTIVE_FLG, RETIRED_DT)
VALUES
    ('EU', 'Europe', 'EUR', 1,
     'EU_CAL445', 'VAT', 'EU_STREET', 'EU_ALNUM',
     'DD/MM/YYYY', 'en-GB', 'GDPR', 72,
     'Europe/Amsterdam', 'Y', NULL)
/

INSERT INTO WWI_REF.REGION_REF
    (REGION_CD, REGION_NAME, REPORTING_CURR_CD, FISCAL_YEAR_START_MONTH,
     FISCAL_CALENDAR_CD, TAX_REGIME_CD, ADDRESS_FORMAT_CD, POSTAL_FORMAT_CD,
     DATE_FORMAT_MASK, DEFAULT_LANGUAGE_CD, CONSENT_REGIME_CD, RETENTION_MONTHS,
     TIMEZONE_TXT, ACTIVE_FLG, RETIRED_DT)
VALUES
    ('APAC', 'Asia Pacific', 'AUD', 4,
     'APAC_APR', 'GST', 'AP_BLOCK', 'AP_MIXED',
     'YYYY/MM/DD', 'en-AU', 'APPI_PDPA', 60,
     'Asia/Singapore', 'Y', NULL)
/

INSERT INTO WWI_REF.REGION_REF
    (REGION_CD, REGION_NAME, REPORTING_CURR_CD, FISCAL_YEAR_START_MONTH,
     FISCAL_CALENDAR_CD, TAX_REGIME_CD, ADDRESS_FORMAT_CD, POSTAL_FORMAT_CD,
     DATE_FORMAT_MASK, DEFAULT_LANGUAGE_CD, CONSENT_REGIME_CD, RETENTION_MONTHS,
     TIMEZONE_TXT, ACTIVE_FLG, RETIRED_DT)
VALUES
    ('LATM', 'Latin America (merged into NA 2013)', 'USD', 1,
     'NA_CAL', 'MIXED', 'US_STREET', 'ZIP5_4',
     'DD/MM/YYYY', 'es-MX', 'CAN_SPAM', 120,
     'America/Mexico_City', 'N', TO_DATE('2013-06-30', 'YYYY-MM-DD'))
/

INSERT INTO WWI_REF.REGION_REF
    (REGION_CD, REGION_NAME, REPORTING_CURR_CD, FISCAL_YEAR_START_MONTH,
     FISCAL_CALENDAR_CD, TAX_REGIME_CD, ADDRESS_FORMAT_CD, POSTAL_FORMAT_CD,
     DATE_FORMAT_MASK, DEFAULT_LANGUAGE_CD, CONSENT_REGIME_CD, RETENTION_MONTHS,
     TIMEZONE_TXT, ACTIVE_FLG, RETIRED_DT)
VALUES
    ('EMEA', 'EMEA (superseded by EU 2009)', 'EUR', 1,
     'EU_CAL445', 'VAT', 'EU_STREET', 'EU_ALNUM',
     'DD/MM/YYYY', 'en-GB', 'GDPR', 120,
     'Europe/London', 'N', TO_DATE('2009-12-31', 'YYYY-MM-DD'))
/

/* ---------------------------------------------------------------------
 * Countries. STATE_PROV_REQUIRED_FLG and POSTAL_REQUIRED_FLG are what the
 * address validation branches on, and they are the reason a US address
 * without a state is rejected while an IE address without a postal code is
 * accepted.
 * ------------------------------------------------------------------- */

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('US', 'USA', '840', '001', 'United States',
     'United States of America', 'NA', 'Northern America', 'USD', 'en-US',
     'N', 'N', NULL, '99999 or 99999-9999',
     'Y', 'Y', '+1', 'N',
     'USMCA', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('CA', 'CAN', '124', '002', 'Canada',
     'Canada', 'NA', 'Northern America', 'CAD', 'en-CA',
     'N', 'N', NULL, 'A9A 9A9',
     'Y', 'Y', '+1', 'N',
     'USMCA', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('MX', 'MEX', '484', '003', 'Mexico',
     'Estados Unidos Mexicanos', 'NA', 'Latin America', 'MXN', 'es-MX',
     'N', 'N', 'RFC 13 characters', '99999',
     'Y', 'Y', '+52', 'N',
     'USMCA', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('DE', 'DEU', '276', '049', 'Germany',
     'Bundesrepublik Deutschland', 'EU', 'Western Europe', 'EUR', 'de-DE',
     'Y', 'Y', 'DE999999999', '99999',
     'Y', 'N', '+49', 'N',
     'EU', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('FR', 'FRA', '250', '033', 'France',
     'Republique francaise', 'EU', 'Western Europe', 'EUR', 'fr-FR',
     'Y', 'Y', 'FRXX999999999', '99999',
     'Y', 'N', '+33', 'N',
     'EU', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('NL', 'NLD', '528', '031', 'Netherlands',
     'Koninkrijk der Nederlanden', 'EU', 'Western Europe', 'EUR', 'nl-NL',
     'Y', 'Y', 'NL999999999B99', '9999 AA',
     'Y', 'N', '+31', 'N',
     'EU', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('IE', 'IRL', '372', '353', 'Ireland',
     'Ireland', 'EU', 'Western Europe', 'EUR', 'en-IE',
     'Y', 'Y', 'IE9999999AA', 'Eircode A99 A999',
     'N', 'N', '+353', 'N',
     'EU', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('GB', 'GBR', '826', '044', 'United Kingdom',
     'United Kingdom of Great Britain and Northern Ireland', 'EU', 'Northern Europe', 'GBP', 'en-GB',
     'N', 'N', 'GB999999999', 'AA9A 9AA',
     'Y', 'N', '+44', 'N',
     'UK', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('AU', 'AUS', '036', '061', 'Australia',
     'Commonwealth of Australia', 'APAC', 'Oceania', 'AUD', 'en-AU',
     'N', 'N', 'ABN 99 999 999 999', '9999',
     'Y', 'Y', '+61', 'N',
     'ANZ', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('NZ', 'NZL', '554', '064', 'New Zealand',
     'New Zealand', 'APAC', 'Oceania', 'NZD', 'en-NZ',
     'N', 'N', 'GST 999-999-999', '9999',
     'Y', 'N', '+64', 'N',
     'ANZ', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('JP', 'JPN', '392', '081', 'Japan',
     'Nippon-koku', 'APAC', 'Eastern Asia', 'JPY', 'ja-JP',
     'N', 'N', 'T9999999999999', '999-9999',
     'Y', 'Y', '+81', 'N',
     'CPTPP', 'Y')
/

INSERT INTO WWI_REF.COUNTRY_REF
    (COUNTRY_CD, COUNTRY_CD_3, COUNTRY_NUM_CD, LEGACY_MAINFRAME_CD, COUNTRY_NAME,
     OFFICIAL_NAME, REGION_CD, SUB_REGION_TXT, DEFAULT_CURR_CD, DEFAULT_LANGUAGE_CD,
     EU_MEMBER_FLG, EU_VAT_AREA_FLG, VAT_NBR_FORMAT_TXT, POSTAL_FORMAT_TXT,
     POSTAL_REQUIRED_FLG, STATE_PROV_REQUIRED_FLG, PHONE_PREFIX_CD, SANCTIONED_FLG,
     TRADE_BLOC_CD, ACTIVE_FLG)
VALUES
    ('SG', 'SGP', '702', '065', 'Singapore',
     'Republic of Singapore', 'APAC', 'South-Eastern Asia', 'SGD', 'en-SG',
     'N', 'N', 'GST M9-9999999-9', '999999',
     'Y', 'N', '+65', 'N',
     'ASEAN', 'Y')
/

COMMIT
/

SET DEFINE ON
