/* =====================================================================
 * Object       : Reference content - WWI_REF.CURRENCY_CODE, WWI_REF.FX_RATE_DAILY
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 101
 * Depends on   : oracle/tables/WWI_REF.CURRENCY_CODE.sql, oracle/tables/WWI_REF.FX_RATE_DAILY.sql
 * Called by    : run once per environment after the table DDL
 *
 * Trading currencies plus two pre-euro national currencies kept for history.
 * JPY carries zero minor units, which the older rounding code ignores.
 *
 * The FX rows are the opening set for each regional feed and show the three
 * conventions side by side: NA loads one CORP rate per month and repeats it,
 * EU loads the ECB daily rate, APAC loads a BANK rate with bid and ask. The
 * APAC feed has no weekend rows at all - that is the behaviour, not an
 * omission in this script.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('USD', '840', 'US Dollar', '$', 2, 'HALFUP', 'US', 'NA', 'N', NULL, NULL, 'Y', 'Y', 10, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('CAD', '124', 'Canadian Dollar', 'C$', 2, 'HALFUP', 'CA', 'NA', 'N', NULL, NULL, 'Y', 'Y', 20, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('MXN', '484', 'Mexican Peso', '$', 2, 'HALFUP', 'MX', 'NA', 'N', NULL, NULL, 'Y', 'Y', 30, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('EUR', '978', 'Euro', 'E', 2, 'HALFEVEN', 'DE', 'EU', 'N', NULL, NULL, 'Y', 'Y', 40, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('GBP', '826', 'Pound Sterling', 'L', 2, 'HALFUP', 'GB', 'EU', 'N', NULL, NULL, 'Y', 'Y', 50, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('AUD', '036', 'Australian Dollar', 'A$', 2, 'HALFUP', 'AU', 'APAC', 'N', NULL, NULL, 'Y', 'Y', 60, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('NZD', '554', 'New Zealand Dollar', 'NZ$', 2, 'HALFUP', 'NZ', 'APAC', 'N', NULL, NULL, 'Y', 'Y', 70, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('JPY', '392', 'Japanese Yen', 'Y', 0, 'HALFEVEN', 'JP', 'APAC', 'N', NULL, NULL, 'Y', 'Y', 80, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('SGD', '702', 'Singapore Dollar', 'S$', 2, 'HALFUP', 'SG', 'APAC', 'N', NULL, NULL, 'Y', 'Y', 90, NULL)
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('DEM', '276', 'Deutsche Mark (pre-euro)', 'DM', 2, 'HALFUP', 'DE', 'EU', 'Y', 1.95583000,
            TO_DATE('2002-01-01', 'YYYY-MM-DD'), 'N', 'N', 900, TO_DATE('2002-02-28', 'YYYY-MM-DD'))
    INTO WWI_REF.CURRENCY_CODE
        (CURR_CD, CURR_NUM_CD, CURR_NAME, CURR_SYMBOL, MINOR_UNIT_DIGITS, ROUNDING_RULE_CD,
         PRIMARY_COUNTRY_CD, REGION_CD, EURO_LEGACY_FLG, EURO_FIXED_RATE, EURO_CONVERSION_DT,
         ACTIVE_FLG, TRADING_ALLOWED_FLG, DISPLAY_SEQ_NBR, RETIRED_DT)
    VALUES ('FRF', '250', 'French Franc (pre-euro)', 'F', 2, 'HALFUP', 'FR', 'EU', 'Y', 6.55957000,
            TO_DATE('2002-01-01', 'YYYY-MM-DD'), 'N', 'N', 910, TO_DATE('2002-02-28', 'YYYY-MM-DD'))
SELECT * FROM DUAL
/

/* NA corporate rate: one rate per month, repeated for every day by the feed.
   Only the first day of the month is seeded here. */
INSERT ALL
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('CAD', 'USD', TO_DATE('2024-01-01', 'YYYY-MM-DD'), 'CORP', 0.74500000, 1.34228188,
            NULL, NULL, 'TREASURY_NA', 'NA', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('MXN', 'USD', TO_DATE('2024-01-01', 'YYYY-MM-DD'), 'CORP', 0.05900000, 16.94915254,
            NULL, NULL, 'TREASURY_NA', 'NA', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('EUR', 'USD', TO_DATE('2024-01-01', 'YYYY-MM-DD'), 'CORP', 1.10200000, 0.90744102,
            NULL, NULL, 'TREASURY_NA', 'NA', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('USD', 'EUR', TO_DATE('2024-01-02', 'YYYY-MM-DD'), 'ECB', 0.90790000, 1.10143187,
            NULL, NULL, 'ECB_DAILY', 'EU', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('GBP', 'EUR', TO_DATE('2024-01-02', 'YYYY-MM-DD'), 'ECB', 1.15420000, 0.86640097,
            NULL, NULL, 'ECB_DAILY', 'EU', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('USD', 'EUR', TO_DATE('2024-01-06', 'YYYY-MM-DD'), 'ECB', 0.90790000, 1.10143187,
            NULL, NULL, 'ECB_DAILY', 'EU', 'Y', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('USD', 'AUD', TO_DATE('2024-01-02', 'YYYY-MM-DD'), 'BANK', 1.47300000, 0.67888663,
            1.47050000, 1.47550000, 'ANZ_FEED', 'APAC', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('JPY', 'AUD', TO_DATE('2024-01-02', 'YYYY-MM-DD'), 'BANK', 0.01041000, 96.06147934,
            0.01039000, 0.01043000, 'ANZ_FEED', 'APAC', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('SGD', 'AUD', TO_DATE('2024-01-02', 'YYYY-MM-DD'), 'BANK', 1.11600000, 0.89605735,
            1.11400000, 1.11800000, 'DBS_FEED', 'APAC', 'N', 'N')
    INTO WWI_REF.FX_RATE_DAILY
        (FROM_CURR_CD, TO_CURR_CD, RATE_DT, RATE_TYPE_CD, RATE, INVERSE_RATE,
         BID_RATE, ASK_RATE, RATE_SOURCE_CD, FEED_REGION_CD, INTERPOLATED_FLG, SUPERSEDED_FLG)
    VALUES ('EUR', 'USD', TO_DATE('2024-01-01', 'YYYY-MM-DD'), 'BUDGET', 1.08000000, 0.92592593,
            NULL, NULL, 'FP_AND_A', NULL, 'N', 'N')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
