/* =====================================================================
 * Object       : Reference content - WWI_REF.CITY_REF, WWI_REF.POSTAL_REF
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 102
 * Depends on   : oracle/tables/WWI_REF.CITY_REF.sql, oracle/tables/WWI_REF.POSTAL_REF.sql
 * Called by    : run once per environment after the table DDL
 *
 * A representative slice of the geography reference showing the three postal
 * conventions the estate has to live with: NA five-digit ZIP with a ZIP+4
 * range and a county FIPS code for sales tax, EU alphanumeric codes with a
 * NUTS region, APAC codes that in Japan carry a district rather than a city.
 *
 * The APAC city rows carry a local-script name in CITY_NAME_LOCAL that the
 * address matcher never looks at.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100001, 'Chicago', NULL, 'CHICAGO', 'IL', 'Illinois',
            NULL, 'Cook', 'US', 'NA', 41.878114, -87.629798,
            2746388, 'America/Chicago', 'CHI', 'US-IL-COOK-CHI', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100002, 'Dallas', NULL, 'DALLAS', 'TX', 'Texas',
            NULL, 'Dallas', 'US', 'NA', 32.776664, -96.796988,
            1304379, 'America/Chicago', 'DFW', 'US-TX-DALLAS-DAL', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100003, 'Toronto', NULL, 'TORONTO', 'ON', 'Ontario',
            NULL, NULL, 'CA', 'NA', 43.653226, -79.383184,
            2794356, 'America/Toronto', 'GTA', 'CA-ON-TOR', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100004, 'Munich', 'Muenchen', 'MUNICH', 'BY', 'Bayern',
            NULL, NULL, 'DE', 'EU', 48.135125, 11.581981,
            1487708, 'Europe/Berlin', 'MUC', 'DE-VAT', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100005, 'Rotterdam', NULL, 'ROTTERDAM', 'ZH', 'Zuid-Holland',
            NULL, NULL, 'NL', 'EU', 51.922500, 4.479170,
            651446, 'Europe/Amsterdam', 'RTM', 'NL-VAT', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100006, 'Dublin', 'Baile Atha Cliath', 'DUBLIN', 'D', 'Leinster',
            NULL, NULL, 'IE', 'EU', 53.349805, -6.260310,
            554554, 'Europe/Dublin', 'DUB', 'IE-VAT', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100007, 'Sydney', NULL, 'SYDNEY', 'NSW', 'New South Wales',
            NULL, NULL, 'AU', 'APAC', -33.868820, 151.209290,
            5312163, 'Australia/Sydney', 'SYD', 'AU-GST', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100008, 'Osaka', 'Osaka-shi', 'OSAKA', NULL, NULL,
            'Osaka-fu', NULL, 'JP', 'APAC', 34.693738, 135.502165,
            2691185, 'Asia/Tokyo', 'OSA', 'JP-CONS', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100009, 'Singapore', NULL, 'SINGAPORE', NULL, NULL,
            NULL, NULL, 'SG', 'APAC', 1.352083, 103.819836,
            5453600, 'Asia/Singapore', 'SIN', 'SG-GST', NULL, 'Y')
    INTO WWI_REF.CITY_REF
        (CITY_ID, CITY_NAME, CITY_NAME_LOCAL, CITY_NAME_UPPER, STATE_PROV_CD, STATE_PROV_NAME,
         PREFECTURE_TXT, COUNTY_TXT, COUNTRY_CD, REGION_CD, LATITUDE, LONGITUDE,
         POPULATION_CNT, TIMEZONE_TXT, METRO_AREA_CD, TAX_JURISDICTION_CD, ALIAS_OF_CITY_ID, ACTIVE_FLG)
    VALUES (100010, 'Chicagoo', NULL, 'CHICAGOO', 'IL', 'Illinois',
            NULL, 'Cook', 'US', 'NA', NULL, NULL,
            NULL, 'America/Chicago', 'CHI', 'US-IL-COOK-CHI', 100001, 'N')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500001, '60601', '60601', 'US', 'NA', 100001, 'Chicago',
            'IL', 'Cook', NULL, '0001', '9999', '17031',
            NULL, NULL, 'US-IL-COOK-CHI', 14820,
            'N', 'Y', TO_DATE('2024-02-01', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500002, '75201', '75201', 'US', 'NA', 100002, 'Dallas',
            'TX', 'Dallas', NULL, '0001', '9999', '48113',
            NULL, NULL, 'US-TX-DALLAS-DAL', 9210,
            'N', 'Y', TO_DATE('2024-02-01', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500003, '80331', '80331', 'DE', 'EU', 100004, 'Munich',
            'BY', NULL, 'Altstadt', NULL, NULL, NULL,
            'DE212', NULL, 'DE-VAT', 3120,
            'N', 'Y', TO_DATE('2023-11-15', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500004, '3011 AA', '3011AA', 'NL', 'EU', 100005, 'Rotterdam',
            'ZH', NULL, 'Centrum', NULL, NULL, NULL,
            'NL339', NULL, 'NL-VAT', 880,
            'N', 'Y', TO_DATE('2023-11-15', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500005, 'D02 XY45', 'D02XY45', 'IE', 'EU', 100006, 'Dublin',
            'D', NULL, 'Dublin 2', NULL, NULL, NULL,
            'IE061', NULL, 'IE-VAT', 1,
            'N', 'Y', TO_DATE('2023-11-15', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500006, '2000', '2000', 'AU', 'APAC', 100007, 'Sydney',
            'NSW', NULL, 'Sydney CBD', NULL, NULL, NULL,
            NULL, 'NSW-SYD-CBD', 'AU-GST', 7400,
            'N', 'Y', TO_DATE('2024-01-10', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500007, '541-0041', '5410041', 'JP', 'APAC', 100008, 'Osaka',
            NULL, NULL, 'Chuo-ku Kitakyuhoji', NULL, NULL, NULL,
            NULL, 'OSA-CHUO-04', 'JP-CONS', 2100,
            'N', 'Y', TO_DATE('2024-01-10', 'YYYY-MM-DD'))
    INTO WWI_REF.POSTAL_REF
        (POSTAL_ID, POSTAL_CD, POSTAL_CD_NORM, COUNTRY_CD, REGION_CD, CITY_ID, CITY_NAME_TXT,
         STATE_PROV_CD, COUNTY_TXT, DISTRICT_TXT, NA_ZIP4_FROM, NA_ZIP4_TO, NA_COUNTY_FIPS_CD,
         EU_NUTS_CD, APAC_DISTRICT_CD, TAX_JURISDICTION_CD, DELIVERY_POINT_CNT,
         PO_BOX_ONLY_FLG, ACTIVE_FLG, LAST_VERIFIED_DT)
    VALUES (500008, '018956', '018956', 'SG', 'APAC', 100009, 'Singapore',
            NULL, NULL, 'Marina Bay', NULL, NULL, NULL,
            NULL, 'SG-CENTRAL', 'SG-GST', 340,
            'N', 'Y', TO_DATE('2024-01-10', 'YYYY-MM-DD'))
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
