/* =====================================================================
 * Object       : Reference content - WWI_REF.UOM_REF, WWI_REF.LANGUAGE_REF, WWI_REF.INCOTERM_REF
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 103
 * Depends on   : oracle/tables/WWI_REF.UOM_REF.sql, oracle/tables/WWI_REF.LANGUAGE_REF.sql, oracle/tables/WWI_REF.INCOTERM_REF.sql
 * Called by    : run once per environment after the table DDL
 *
 * Units of measure, correspondence languages and Incoterms.
 *
 * The UOM set is where the imperial/metric split shows: LB and OZ are used by
 * NA purchasing only, KG and G by EU and APAC, and the conversion between the
 * two classes is not expressible here.
 *
 * Both the 2010 and 2020 Incoterm revisions are active because open contracts
 * still cite the 2010 terms.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('EA', 'Each', 'COUNT', 'EA', 1.00000000, 'BOTH', 0, 'EA', 'EACH', 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('CS', 'Case', 'COUNT', 'EA', 12.00000000, 'BOTH', 0, 'CS', 'CASE', 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('PLT', 'Pallet', 'COUNT', 'EA', 480.00000000, 'BOTH', 0, 'PF', 'PALL', 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('KG', 'Kilogram', 'WEIGHT', 'KG', 1.00000000, 'METRIC', 3, 'KGM', 'KILO', 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('G', 'Gram', 'WEIGHT', 'KG', 0.00100000, 'METRIC', 3, 'GRM', NULL, 'N', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('LB', 'Pound', 'WEIGHT', 'KG', 0.45359237, 'IMPER', 3, 'LBR', 'LBS', 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('OZ', 'Ounce', 'WEIGHT', 'KG', 0.02834952, 'IMPER', 3, 'ONZ', NULL, 'N', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('L', 'Litre', 'VOLUME', 'L', 1.00000000, 'METRIC', 3, 'LTR', NULL, 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('GAL', 'US Gallon', 'VOLUME', 'L', 3.78541178, 'IMPER', 3, 'GLL', NULL, 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('HR', 'Hour', 'TIME', 'HR', 1.00000000, 'BOTH', 2, 'HUR', NULL, 'Y', 'N', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('DAY', 'Day', 'TIME', 'HR', 8.00000000, 'BOTH', 2, 'DAY', NULL, 'Y', 'N', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('M', 'Metre', 'LENGTH', 'M', 1.00000000, 'METRIC', 3, 'MTR', NULL, 'Y', 'Y', 'Y')
    INTO WWI_REF.UOM_REF
        (UOM_CD, UOM_NAME, UOM_CLASS_CD, BASE_UOM_CD, CONVERSION_FACTOR, MEASUREMENT_SYSTEM_CD,
         PRECISION_DIGITS, ISO_UOM_CD, LEGACY_UOM_CD, PURCHASING_ALLOWED_FLG,
         INVENTORY_ALLOWED_FLG, ACTIVE_FLG)
    VALUES ('FT', 'Foot', 'LENGTH', 'M', 0.30480000, 'IMPER', 3, 'FOT', NULL, 'Y', 'Y', 'Y')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('en-US', 'English (United States)', 'English', 'EN', 'en', 'WE8MSWIN1252',
            'LTR', 'NA', 'STD_EN', 'FULL', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('en-GB', 'English (United Kingdom)', 'English', 'EN', 'en', 'WE8MSWIN1252',
            'LTR', 'EU', 'STD_EN', 'FULL', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('de-DE', 'German', 'Deutsch', 'DE', 'de', 'WE8MSWIN1252',
            'LTR', 'EU', 'STD_DE', 'FULL', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('fr-FR', 'French', 'Francais', 'FR', 'fr', 'WE8MSWIN1252',
            'LTR', 'EU', 'STD_FR', 'FULL', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('nl-NL', 'Dutch', 'Nederlands', 'NL', 'nl', 'WE8MSWIN1252',
            'LTR', 'EU', 'STD_NL', 'PART', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('es-MX', 'Spanish (Mexico)', 'Espanol', 'ES', 'es', 'WE8MSWIN1252',
            'LTR', 'NA', 'STD_ES', 'PART', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('ja-JP', 'Japanese', 'Nihongo', 'JA', 'ja', 'AL32UTF8',
            'LTR', 'APAC', 'STD_JA', 'PART', 'Y')
    INTO WWI_REF.LANGUAGE_REF
        (LANGUAGE_CD, LANGUAGE_NAME, NATIVE_NAME, LEGACY_LANG_CD, ISO_639_1_CD, CHARACTER_SET_CD,
         WRITING_DIRECTION_CD, DEFAULT_REGION_CD, DOCUMENT_TEMPLATE_CD, TRANSLATION_STATUS_CD, ACTIVE_FLG)
    VALUES ('en-AU', 'English (Australia)', 'English', 'EN', 'en', 'WE8MSWIN1252',
            'LTR', 'APAC', 'STD_EN', 'FULL', 'Y')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('EXW', 2020, 'Ex Works', 'Buyer collects at the seller premises.', 'ANY',
            'BUYER', 'BUYER', 'Seller premises',
            'BUYER', 'BUYER', 'Y',
            NULL, 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('FCA', 2020, 'Free Carrier', 'Seller delivers to the named carrier.', 'ANY',
            'BUYER', 'BUYER', 'Named place of delivery',
            'SELLER', 'BUYER', 'Y',
            NULL, 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('CIF', 2020, 'Cost Insurance and Freight', 'Sea freight, seller insures to destination port.', 'SEA',
            'SELLER', 'SELLER', 'On board vessel at origin',
            'SELLER', 'BUYER', 'N',
            NULL, 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('DAP', 2020, 'Delivered At Place', 'Seller delivers ready for unloading.', 'ANY',
            'SELLER', 'SELLER', 'Named destination',
            'SELLER', 'BUYER', 'N',
            NULL, 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('DDP', 2020, 'Delivered Duty Paid', 'Seller bears everything including import duty.', 'ANY',
            'SELLER', 'SELLER', 'Named destination',
            'SELLER', 'SELLER', 'N',
            NULL, 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('DAT', 2010, 'Delivered At Terminal', 'Superseded by DPU in the 2020 revision.', 'ANY',
            'SELLER', 'SELLER', 'Named terminal',
            'SELLER', 'BUYER', 'N',
            'DPU', 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('DPU', 2020, 'Delivered At Place Unloaded', 'Replaces DAT from the 2020 revision.', 'ANY',
            'SELLER', 'SELLER', 'Named place after unloading',
            'SELLER', 'BUYER', 'N',
            NULL, 'Y')
    INTO WWI_REF.INCOTERM_REF
        (INCOTERM_CD, REVISION_YEAR_NBR, INCOTERM_NAME, DESCRIPTION_TXT, TRANSPORT_MODE_CD,
         FREIGHT_PAID_BY_CD, INSURANCE_PAID_BY_CD, RISK_TRANSFER_POINT_TXT,
         EXPORT_CLEARANCE_BY_CD, IMPORT_CLEARANCE_BY_CD, LANDED_COST_INCLUDE_FLG,
         SUPERSEDED_BY_CD, ACTIVE_FLG)
    VALUES ('FOB', 2010, 'Free On Board', 'Still cited by pre-2020 sea freight contracts.', 'SEA',
            'BUYER', 'BUYER', 'On board vessel at origin',
            'SELLER', 'BUYER', 'Y',
            NULL, 'Y')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
