/* =====================================================================
 * Object       : Reference content - WWI_FIN.TAX_JURISDICTION, WWI_FIN.TAX_RATE (NA)
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 104
 * Depends on   : oracle/tables/WWI_FIN.TAX_JURISDICTION.sql, oracle/tables/WWI_FIN.TAX_RATE.sql
 * Called by    : run once per environment after the table DDL
 *
 * North American sales and use tax. The defining NA characteristic is
 * stacking: a Chicago delivery attracts the Illinois state rate, the Cook
 * County rate, the city rate and a special transit-district rate, applied in
 * compound sequence, and the total is what the PO header stores in
 * NA_SALES_TAX_RATE as a single number. Nothing in the transactional tables
 * remembers which four rates produced it.
 *
 * Use tax is a separate regime on the same jurisdictions, self-assessed, and
 * recoverable at 0 per cent - it is a cost, not a receivable.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7001, 'US-IL', 'Illinois Department of Revenue', 'NA', 'US',
            'IL', NULL, NULL, NULL, NULL,
            'STATE', 'SALES', 'N', NULL,
            'Y', 'IL-BT-4471902', 'M', 20,
            'Illinois Department of Revenue', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7002, 'US-IL-COOK', 'Cook County IL', 'NA', 'US',
            'IL', 'Cook', NULL, '60000', '60999',
            'COUNTY', 'SALES', 'Y', 'US-IL',
            'Y', 'IL-BT-4471902', 'M', 20,
            'Cook County Department of Revenue', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7003, 'US-IL-COOK-CHI', 'City of Chicago', 'NA', 'US',
            'IL', 'Cook', 'Chicago', '60601', '60699',
            'CITY', 'SALES', 'Y', 'US-IL-COOK',
            'Y', 'CHI-9930041', 'M', 15,
            'Chicago Department of Finance', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7004, 'US-IL-RTA', 'Regional Transportation Authority', 'NA', 'US',
            'IL', 'Cook', NULL, '60000', '60999',
            'SPEC', 'SALES', 'Y', 'US-IL-COOK',
            'N', NULL, 'Q', 20,
            'RTA', TO_DATE('2008-04-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7005, 'US-TX-DALLAS-DAL', 'City of Dallas', 'NA', 'US',
            'TX', 'Dallas', 'Dallas', '75201', '75299',
            'CITY', 'SALES', 'Y', 'US-TX',
            'Y', 'TX-17451209', 'M', 20,
            'Texas Comptroller of Public Accounts', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9001, 'IL_STD', 'US-IL', 'NA', 'SALES',
            'STD', 6.25000, 'N', 1, 0.00,
            TO_DATE('2008-07-01', 'YYYY-MM-DD'), NULL, '2210-000-0000', 'N', 'N',
            'IL-ST1', NULL, 'Illinois state sales tax', '35 ILCS 120', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9002, 'COOK_STD', 'US-IL-COOK', 'NA', 'SALES',
            'STD', 1.75000, 'Y', 2, 0.00,
            TO_DATE('2016-07-01', 'YYYY-MM-DD'), NULL, '2210-000-0000', 'N', 'N',
            'IL-ST1', NULL, 'Cook County home rule sales tax', 'Cook Cty Ord 15-4522', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9003, 'CHI_STD', 'US-IL-COOK-CHI', 'NA', 'SALES',
            'STD', 1.25000, 'Y', 3, 0.00,
            TO_DATE('2016-01-01', 'YYYY-MM-DD'), NULL, '2210-000-0000', 'N', 'N',
            'IL-ST1', NULL, 'City of Chicago home rule sales tax', 'MCC 3-27', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9004, 'RTA_STD', 'US-IL-RTA', 'NA', 'SALES',
            'STD', 1.00000, 'Y', 4, 0.00,
            TO_DATE('2008-04-01', 'YYYY-MM-DD'), NULL, '2210-000-0000', 'N', 'N',
            'IL-ST1', NULL, 'RTA transit district sales tax', '70 ILCS 3615', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9005, 'IL_RESALE', 'US-IL', 'NA', 'SALES',
            'RESALE', 0.00000, 'N', 1, 0.00,
            TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, NULL, 'N', 'N',
            'IL-EX', 'RESALE', 'Resale certificate on file with the supplier', '35 ILCS 120/2c', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9006, 'IL_USE', 'US-IL', 'NA', 'USE',
            'STD', 6.25000, 'N', 1, 0.00,
            TO_DATE('2008-07-01', 'YYYY-MM-DD'), NULL, '6810-000-0000', 'N', 'Y',
            'IL-UT', NULL, 'Self-assessed use tax on untaxed out-of-state purchases', '35 ILCS 105', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9007, 'TX_STD', 'US-TX-DALLAS-DAL', 'NA', 'SALES',
            'STD', 8.25000, 'N', 1, 0.00,
            TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, '2210-000-0000', 'N', 'N',
            'TX-ST', NULL, 'Combined Texas state and local rate held as one row', 'Tex Tax Code 151', 'Y')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
