/* =====================================================================
 * Object       : Reference content - WWI_FIN.TAX_JURISDICTION, WWI_FIN.TAX_RATE (EU)
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 105
 * Depends on   : oracle/tables/WWI_FIN.TAX_JURISDICTION.sql, oracle/tables/WWI_FIN.TAX_RATE.sql
 * Called by    : run once per environment after the table DDL
 *
 * European VAT. Nothing stacks: one rate per member state per category, but
 * there are five categories and the reduced ones differ per state. VAT is
 * recoverable, which is why RECOVERABLE_PCT is 100 here and 0 in NA, and why
 * the AP invoice tax lines behave completely differently between the regions.
 *
 * Intra-community acquisitions carry a zero rate with REVERSE_CHARGE_FLG = 'Y'
 * and are reported in two boxes at once; the estate handles this by writing two
 * tax lines and hoping the totals agree.
 *
 * The GB rows continue after the UK left the EU VAT area: the regime is still
 * recorded as VAT, the jurisdiction is still under the EU region, and only
 * EU_VAT_AREA_FLG on COUNTRY_REF says otherwise.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7101, 'DE-VAT', 'Germany VAT', 'EU', 'DE',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'VAT', 'N', NULL,
            'Y', 'DE811907980', 'M', 10,
            'Bundeszentralamt fuer Steuern', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7102, 'FR-VAT', 'France TVA', 'EU', 'FR',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'VAT', 'N', NULL,
            'Y', 'FR40303265045', 'M', 19,
            'Direction generale des Finances publiques', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7103, 'NL-VAT', 'Netherlands BTW', 'EU', 'NL',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'VAT', 'N', NULL,
            'Y', 'NL004495445B01', 'Q', 30,
            'Belastingdienst', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7104, 'IE-VAT', 'Ireland VAT', 'EU', 'IE',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'VAT', 'N', NULL,
            'Y', 'IE6388047V', 'B', 23,
            'Revenue Commissioners', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7105, 'GB-VAT', 'United Kingdom VAT (post-Brexit)', 'EU', 'GB',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'VAT', 'N', NULL,
            'Y', 'GB553557881', 'Q', 7,
            'HM Revenue and Customs', TO_DATE('2021-01-01', 'YYYY-MM-DD'), NULL, 'Y')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9101, 'DE_STD', 'DE-VAT', 'EU', 'VAT',
            'STD', 19.00000, 'N', NULL, 100.00,
            TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL, '1450-000-0000', 'N', 'N',
            'DE-81', NULL, 'German standard VAT rate', 'UStG 12 Abs 1', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9102, 'DE_RED', 'DE-VAT', 'EU', 'VAT',
            'RED1', 7.00000, 'N', NULL, 100.00,
            TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL, '1450-000-0000', 'N', 'N',
            'DE-86', 'FOOD', 'German reduced VAT rate', 'UStG 12 Abs 2', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9103, 'DE_STD_COVID', 'DE-VAT', 'EU', 'VAT',
            'STD', 16.00000, 'N', NULL, 100.00,
            TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2020-12-31', 'YYYY-MM-DD'), '1450-000-0000', 'N', 'N',
            'DE-81', NULL, 'Temporary German standard rate, still needed to restate 2020', 'Zweites CorStHG', 'N')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9104, 'FR_STD', 'FR-VAT', 'EU', 'VAT',
            'STD', 20.00000, 'N', NULL, 100.00,
            TO_DATE('2014-01-01', 'YYYY-MM-DD'), NULL, '1450-000-0000', 'N', 'N',
            'FR-08', NULL, 'French standard TVA rate', 'CGI art 278', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9105, 'FR_RED1', 'FR-VAT', 'EU', 'VAT',
            'RED1', 10.00000, 'N', NULL, 100.00,
            TO_DATE('2014-01-01', 'YYYY-MM-DD'), NULL, '1450-000-0000', 'N', 'N',
            'FR-09', 'LOGISTICS', 'French intermediate TVA rate', 'CGI art 279', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9106, 'FR_RED2', 'FR-VAT', 'EU', 'VAT',
            'RED2', 5.50000, 'N', NULL, 100.00,
            TO_DATE('2014-01-01', 'YYYY-MM-DD'), NULL, '1450-000-0000', 'N', 'N',
            'FR-09', 'FOOD', 'French reduced TVA rate', 'CGI art 278-0 bis', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9107, 'NL_ICA', 'NL-VAT', 'EU', 'VAT',
            'ZERO', 0.00000, 'N', NULL, 100.00,
            TO_DATE('2002-01-01', 'YYYY-MM-DD'), NULL, '1450-100-0000', 'Y', 'Y',
            'NL-4B', NULL, 'Intra-community acquisition, reverse charged', 'Wet OB 1968 art 17b', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9108, 'GB_STD', 'GB-VAT', 'EU', 'VAT',
            'STD', 20.00000, 'N', NULL, 100.00,
            TO_DATE('2011-01-04', 'YYYY-MM-DD'), NULL, '1450-000-0000', 'N', 'N',
            'GB-B1', NULL, 'UK standard VAT rate', 'VATA 1994 s2', 'Y')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
