/* =====================================================================
 * Object       : Reference content - WWI_FIN.TAX_JURISDICTION, WWI_FIN.TAX_RATE (APAC)
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 106
 * Depends on   : oracle/tables/WWI_FIN.TAX_JURISDICTION.sql, oracle/tables/WWI_FIN.TAX_RATE.sql
 * Called by    : run once per environment after the table DDL
 *
 * Asia-Pacific indirect tax. Three different things wear the same GST label:
 * Australian GST at a flat 10 per cent, Singapore GST which has moved twice in
 * three years, and Japanese consumption tax which is a separate regime code
 * with a reduced rate for food and a qualified-invoice number requirement from
 * October 2023.
 *
 * The INPUT rate category exists only in APAC and is what the AP side uses to
 * claim input credits; the equivalent in EU is simply RECOVERABLE_PCT on the
 * standard rate, which is why input-credit reporting cannot be written once
 * for both regions.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7201, 'AU-GST', 'Australia GST', 'APAC', 'AU',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'GST', 'N', NULL,
            'Y', '53004085616', 'Q', 28,
            'Australian Taxation Office', TO_DATE('2000-07-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7202, 'NZ-GST', 'New Zealand GST', 'APAC', 'NZ',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'GST', 'N', NULL,
            'Y', '104-235-916', 'B', 28,
            'Inland Revenue Department', TO_DATE('2000-07-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7203, 'SG-GST', 'Singapore GST', 'APAC', 'SG',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'GST', 'N', NULL,
            'Y', 'M2-0117295-4', 'Q', 30,
            'Inland Revenue Authority of Singapore', TO_DATE('2004-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.TAX_JURISDICTION
        (TAX_JURISDICTION_ID, JURISDICTION_CD, JURISDICTION_NAME, REGION_CD, COUNTRY_CD,
         STATE_PROV_CD, COUNTY_TXT, CITY_TXT, POSTAL_FROM_CD, POSTAL_TO_CD,
         JURISDICTION_LEVEL_CD, TAX_REGIME_CD, STACKS_WITH_PARENT_FLG, PARENT_JURISDICTION_CD,
         REGISTRATION_REQ_FLG, OUR_REGISTRATION_NBR, FILING_FREQUENCY_CD, FILING_DUE_DAY_NBR,
         AUTHORITY_NAME, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (7204, 'JP-CONS', 'Japan Consumption Tax', 'APAC', 'JP',
            NULL, NULL, NULL, NULL, NULL,
            'NATL', 'CONS', 'N', NULL,
            'Y', 'T7010001008844', 'A', 60,
            'National Tax Agency', TO_DATE('2004-04-01', 'YYYY-MM-DD'), NULL, 'Y')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9201, 'AU_GST', 'AU-GST', 'APAC', 'GST',
            'STD', 10.00000, 'N', NULL, 100.00,
            TO_DATE('2000-07-01', 'YYYY-MM-DD'), NULL, '1460-000-0000', 'N', 'N',
            'AU-1A', NULL, 'Australian GST standard rate', 'A New Tax System (GST) Act 1999', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9202, 'AU_FREE', 'AU-GST', 'APAC', 'GST',
            'ZERO', 0.00000, 'N', NULL, 100.00,
            TO_DATE('2000-07-01', 'YYYY-MM-DD'), NULL, NULL, 'N', 'N',
            'AU-G1', 'FOOD', 'GST-free supplies', 'GST Act Div 38', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9203, 'NZ_GST', 'NZ-GST', 'APAC', 'GST',
            'STD', 15.00000, 'N', NULL, 100.00,
            TO_DATE('2010-10-01', 'YYYY-MM-DD'), NULL, '1460-000-0000', 'N', 'N',
            'NZ-GST', NULL, 'New Zealand GST standard rate', 'GST Act 1985', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9204, 'SG_GST7', 'SG-GST', 'APAC', 'GST',
            'STD', 7.00000, 'N', NULL, 100.00,
            TO_DATE('2007-07-01', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'), '1460-000-0000', 'N', 'N',
            'SG-B1', NULL, 'Singapore GST prior to the 2023 increase', 'GST Act Cap 117A', 'N')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9205, 'SG_GST9', 'SG-GST', 'APAC', 'GST',
            'STD', 9.00000, 'N', NULL, 100.00,
            TO_DATE('2024-01-01', 'YYYY-MM-DD'), NULL, '1460-000-0000', 'N', 'N',
            'SG-B1', NULL, 'Singapore GST standard rate', 'GST Act Cap 117A', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9206, 'JP_CONS10', 'JP-CONS', 'APAC', 'CONS',
            'STD', 10.00000, 'N', NULL, 100.00,
            TO_DATE('2019-10-01', 'YYYY-MM-DD'), NULL, '1460-000-0000', 'N', 'N',
            'JP-C1', NULL, 'Japanese consumption tax standard rate', 'Consumption Tax Act art 29', 'Y')
    INTO WWI_FIN.TAX_RATE
        (TAX_RATE_ID, TAX_CODE_CD, JURISDICTION_CD, REGION_CD, TAX_REGIME_CD,
         RATE_CATEGORY_CD, RATE_PCT, COMPOUND_FLG, COMPOUND_SEQ_NBR, RECOVERABLE_PCT,
         EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, TAX_ACCOUNT_CD, REVERSE_CHARGE_FLG, SELF_ASSESS_FLG,
         REPORTING_BOX_CD, PRODUCT_CATEGORY_CD, RATE_DESC, LEGISLATION_REF_TXT, ACTIVE_FLG)
    VALUES (9207, 'JP_INPUT', 'JP-CONS', 'APAC', 'CONS',
            'INPUT', 10.00000, 'N', NULL, 100.00,
            TO_DATE('2023-10-01', 'YYYY-MM-DD'), NULL, '1460-100-0000', 'N', 'N',
            'JP-C2', NULL, 'Input credit, requires a qualified invoice registration number', 'Invoice System 2023', 'Y')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
