/* =====================================================================
 * Object       : Reference content - WWI_FIN.PAYMENT_TERMS, WWI_REF.PAYMENT_METHOD_REF
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 107
 * Depends on   : oracle/tables/WWI_FIN.PAYMENT_TERMS.sql, oracle/tables/WWI_REF.PAYMENT_METHOD_REF.sql
 * Called by    : run once per environment after the table DDL
 *
 * Payment terms and the payment methods available per country.
 *
 * The regional divergence is real: NA runs discount terms from the invoice
 * date, EU runs 30-day terms carrying the Late Payment Directive interest
 * entitlement and a statutory recovery fee, and APAC runs end-of-month and
 * day-of-month terms because that is how the local suppliers invoice. The
 * EOM60 term used in Japan means 'end of the month after next', which is what
 * MONTHS_FORWARD_NBR = 2 encodes and what nobody outside the APAC team reads
 * correctly.
 *
 * Two terms codes are retired but left active because open POs reference them.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8001, 'N30', 'Net 30 days from invoice date', 'NA', 'NETDAY',
            30, NULL, NULL, 'INVDT',
            1.500, 'MONTH', 'N', 'N',
            'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'N30')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8002, '2P10N30', '2 percent 10 days, net 30', 'NA', 'NETDAY',
            30, NULL, NULL, 'INVDT',
            1.500, 'MONTH', 'Y', 'N',
            'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, '210')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8003, 'N45', 'Net 45 days from receipt date', 'NA', 'NETDAY',
            45, NULL, NULL, 'RCVDT',
            1.000, 'MONTH', 'N', 'N',
            'Y', TO_DATE('2004-01-01', 'YYYY-MM-DD'), NULL, 'N45')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8004, 'CIA', 'Cash in advance', 'NA', 'PREPAY',
            NULL, NULL, NULL, 'INVDT',
            NULL, NULL, 'N', 'N',
            'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL, 'CIA')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8005, 'EU30', 'Net 30 days, Late Payment Directive applies', 'EU', 'NETDAY',
            30, NULL, NULL, 'INVDT',
            8.000, 'ANNUM', 'N', 'Y',
            'Y', TO_DATE('2013-03-16', 'YYYY-MM-DD'), NULL, 'E30')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8006, 'EU60', 'Net 60 days, agreed extension under the Directive', 'EU', 'NETDAY',
            60, NULL, NULL, 'INVDT',
            8.000, 'ANNUM', 'N', 'Y',
            'Y', TO_DATE('2013-03-16', 'YYYY-MM-DD'), NULL, 'E60')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8007, 'EUEOM', 'End of month following invoice month', 'EU', 'EOM',
            NULL, NULL, 1, 'EOM',
            8.000, 'ANNUM', 'N', 'Y',
            'Y', TO_DATE('2005-01-01', 'YYYY-MM-DD'), NULL, 'EOM')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8008, 'EU1P14', '1 percent 14 days, net 30 (Skonto)', 'EU', 'NETDAY',
            30, NULL, NULL, 'INVDT',
            8.000, 'ANNUM', 'Y', 'Y',
            'Y', TO_DATE('2005-01-01', 'YYYY-MM-DD'), NULL, 'SKO')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8009, 'AP25EOM', 'Due on the 25th of the following month', 'APAC', 'DOM',
            NULL, 25, 1, 'EOM',
            NULL, NULL, 'N', 'N',
            'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL, 'A25')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8010, 'APEOM60', 'End of the month after next (Japan)', 'APAC', 'EOM',
            NULL, NULL, 2, 'EOM',
            NULL, NULL, 'N', 'N',
            'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL, 'J60')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8011, 'APIMM', 'Immediate on presentation', 'APAC', 'IMMED',
            NULL, NULL, NULL, 'INVDT',
            NULL, NULL, 'N', 'N',
            'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL, 'IMM')
    INTO WWI_FIN.PAYMENT_TERMS
        (PAYMENT_TERMS_ID, PAYMENT_TERMS_CD, TERMS_DESC, REGION_CD, TERM_BASIS_CD,
         NET_DAYS, DUE_DAY_OF_MONTH_NBR, MONTHS_FORWARD_NBR, DISCOUNT_BASIS_CD,
         LATE_FEE_PCT, LATE_FEE_BASIS_CD, PROMPT_PAY_FLG, EU_LATE_PAYMENT_DIR_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, LEGACY_TERMS_CD)
    VALUES (8012, 'N30OLD', 'Net 30 (retired 2011, open POs still cite it)', NULL, 'NETDAY',
            30, NULL, NULL, 'INVDT',
            NULL, NULL, 'N', 'N',
            'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), TO_DATE('2011-12-31', 'YYYY-MM-DD'), 'N3O')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('CHK', 'US', 'Printed cheque', 'NA', 'CHECK_LSR',
            5, '14:00', 25.00000, 250000.00000, 'USD', 0.00000,
            'N', 'Y', 'N', 'Y',
            'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('ACH', 'US', 'NACHA ACH credit', 'NA', 'NACHA_CCD',
            2, '16:00', 1.00000, 999999.99000, 'USD', 0.35000,
            'N', 'Y', 'N', 'Y',
            'Y', TO_DATE('2003-01-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('WIRE', 'US', 'Domestic wire transfer', 'NA', 'FEDWIRE',
            0, '15:00', 5000.00000, NULL, 'USD', 25.00000,
            'N', 'Y', 'N', 'Y',
            'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('EFT', 'CA', 'Canadian EFT', 'NA', 'CPA005',
            2, '15:00', 1.00000, 500000.00000, 'CAD', 0.50000,
            'N', 'Y', 'N', 'Y',
            'Y', TO_DATE('2005-01-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('SEPACT', 'DE', 'SEPA credit transfer', 'EU', 'PAIN001',
            1, '13:00', 0.01000, NULL, 'EUR', 0.00000,
            'Y', 'N', 'N', 'Y',
            'Y', TO_DATE('2014-02-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('SEPADD', 'DE', 'SEPA B2B direct debit', 'EU', 'PAIN008',
            2, '11:00', 0.01000, 100000.00000, 'EUR', 0.00000,
            'Y', 'N', 'Y', 'Y',
            'Y', TO_DATE('2014-02-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('SEPACT', 'NL', 'SEPA credit transfer', 'EU', 'PAIN001',
            1, '13:00', 0.01000, NULL, 'EUR', 0.00000,
            'Y', 'N', 'N', 'Y',
            'Y', TO_DATE('2014-02-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('BACS', 'GB', 'BACS credit', 'EU', 'BACS18',
            3, '10:30', 0.01000, NULL, 'GBP', 0.00000,
            'N', 'Y', 'N', 'Y',
            'Y', TO_DATE('2001-01-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('ABA', 'AU', 'Australian direct entry', 'APAC', 'ABA_CEMTEX',
            1, '16:00', 1.00000, NULL, 'AUD', 0.20000,
            'N', 'Y', 'N', 'Y',
            'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('ZENGIN', 'JP', 'Zengin domestic transfer', 'APAC', 'ZENGIN_FW',
            1, '15:00', 1.00000, NULL, 'JPY', 440.00000,
            'N', 'N', 'N', 'N',
            'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('GIRO', 'SG', 'Interbank GIRO', 'APAC', 'GIRO_FW',
            2, '14:00', 1.00000, NULL, 'SGD', 0.50000,
            'N', 'N', 'Y', 'Y',
            'Y', TO_DATE('2008-01-01', 'YYYY-MM-DD'), NULL)
    INTO WWI_REF.PAYMENT_METHOD_REF
        (PAYMENT_METHOD_CD, COUNTRY_CD, METHOD_NAME, REGION_CD, FILE_FORMAT_CD,
         SETTLEMENT_DAYS, CUT_OFF_TIME_TXT, MIN_AMT, MAX_AMT, METHOD_CURR_CD, BANK_CHARGE_AMT,
         REQUIRES_IBAN_FLG, REQUIRES_ROUTING_FLG, REQUIRES_MANDATE_FLG, REMITTANCE_ADVICE_FLG,
         ACTIVE_FLG, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    VALUES ('CHK', 'JP', 'Bank cheque (retired 2019)', 'APAC', 'MANUAL',
            7, NULL, 1.00000, NULL, 'JPY', 880.00000,
            'N', 'N', 'N', 'N',
            'N', TO_DATE('2006-04-01', 'YYYY-MM-DD'), TO_DATE('2019-03-31', 'YYYY-MM-DD'))
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
