/* =====================================================================
 * Object       : Reference content - WWI_FIN.GL_ACCOUNT, WWI_FIN.COST_CENTER
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 109
 * Depends on   : oracle/tables/WWI_FIN.GL_ACCOUNT.sql, oracle/tables/WWI_FIN.COST_CENTER.sql
 * Called by    : run once per environment after the table DDL
 *
 * The corporate chart of accounts and the cost centre hierarchy.
 *
 * ACCOUNT_CD is the concatenated segment string 'CC-AAAA-SSS-PPP' that the
 * 1998 chart used and that the split segment columns on the journal lines
 * duplicate. OLD_ACCOUNT_CD is the five-digit code from before the 2007
 * re-chart; three reports still join on it.
 *
 * Cost centres carry a legal entity, a functional currency and an approval
 * limit that is denominated in that currency but compared against amounts in
 * the transaction currency by the approval logic.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6001, '0000-1000-000-000',
            '0000', '1000', '000', '000',
            'Cash and cash equivalents', 'ASST', 'CUR',
            'D', NULL, 1, 'N',
            'Y', 'N', 'B-I', 'IAS7-CASH',
            'ASC305', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '10000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6002, '0000-1010-000-000',
            '0000', '1010', '000', '000',
            'Operating bank account', 'ASST', 'CUR',
            'D', '0000-1000-000-000', 2, 'Y',
            'Y', 'N', 'B-I-1', 'IAS7-CASH',
            'ASC305', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '10100', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6003, '0000-1300-000-000',
            '0000', '1300', '000', '000',
            'Inventory - raw materials', 'ASST', 'CUR',
            'D', NULL, 1, 'Y',
            'Y', 'N', 'B-II', 'IAS2-INV',
            'ASC330', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '13000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6004, '0000-1450-000-000',
            '0000', '1450', '000', '000',
            'VAT recoverable', 'ASST', 'CUR',
            'D', NULL, 1, 'Y',
            'Y', 'N', 'B-II-4', 'IAS12-TAX',
            NULL, 'EUR', TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '14500', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6005, '0000-1460-000-000',
            '0000', '1460', '000', '000',
            'GST input credit', 'ASST', 'CUR',
            'D', NULL, 1, 'Y',
            'Y', 'N', NULL, 'IAS12-TAX',
            NULL, NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '14600', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6006, '0000-2100-000-000',
            '0000', '2100', '000', '000',
            'Accounts payable - trade', 'LIAB', 'CUR',
            'C', NULL, 1, 'Y',
            'Y', 'N', 'C-IV', 'IAS1-TP',
            'ASC405', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '21000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6007, '0000-2150-000-000',
            '0000', '2150', '000', '000',
            'Goods received not invoiced', 'LIAB', 'CUR',
            'C', '0000-2100-000-000', 2, 'Y',
            'Y', 'N', 'C-IV-2', 'IAS1-TP',
            'ASC405', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '21500', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6008, '0000-2210-000-000',
            '0000', '2210', '000', '000',
            'Sales tax payable', 'LIAB', 'CUR',
            'C', NULL, 1, 'Y',
            'Y', 'N', NULL, 'IAS12-TAX',
            'ASC450', 'USD', TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '22100', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6009, '0000-2300-000-000',
            '0000', '2300', '000', '000',
            'Withholding tax payable', 'LIAB', 'CUR',
            'C', NULL, 1, 'Y',
            'Y', 'N', NULL, 'IAS12-TAX',
            'ASC740', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '23000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6010, '0000-3000-000-000',
            '0000', '3000', '000', '000',
            'Retained earnings', 'EQTY', 'EQ',
            'C', NULL, 1, 'N',
            'N', 'N', 'A-IV', 'IAS1-EQ',
            'ASC505', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '30000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6011, '0000-4000-000-000',
            '0000', '4000', '000', '000',
            'Revenue - product sales', 'REV', 'OPS',
            'C', NULL, 1, 'Y',
            'N', 'N', 'P-1', 'IFRS15-REV',
            'ASC606', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '40000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6012, '0000-5000-000-000',
            '0000', '5000', '000', '000',
            'Cost of goods sold', 'EXP', 'OPS',
            'D', NULL, 1, 'Y',
            'N', 'N', 'P-2', 'IAS2-COGS',
            'ASC330', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '50000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6013, '0000-6100-000-000',
            '0000', '6100', '000', '000',
            'Freight inward', 'EXP', 'OPS',
            'D', '0000-5000-000-000', 2, 'Y',
            'N', 'N', 'P-2-1', 'IAS2-COGS',
            'ASC330', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '61000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6014, '0000-6300-000-000',
            '0000', '6300', '000', '000',
            'Warehouse operating expense', 'EXP', 'OPS',
            'D', NULL, 1, 'Y',
            'N', 'N', 'P-5', 'IAS1-OPEX',
            'ASC720', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '63000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6015, '0000-6810-000-000',
            '0000', '6810', '000', '000',
            'Use tax expense', 'EXP', 'OPS',
            'D', NULL, 1, 'Y',
            'N', 'N', NULL, 'IAS12-TAX',
            'ASC450', 'USD', TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '68100', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6016, '0000-6900-000-000',
            '0000', '6900', '000', '000',
            'Intercompany recharge', 'EXP', 'OPS',
            'D', NULL, 1, 'Y',
            'Y', 'Y', 'P-9', 'IAS24-RP',
            'ASC850', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '69000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6017, '0000-7700-000-000',
            '0000', '7700', '000', '000',
            'FX gain or loss on settlement', 'EXP', 'FIN',
            'D', NULL, 1, 'Y',
            'N', 'N', 'P-11', 'IAS21-FX',
            'ASC830', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '77000', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6018, '0000-9999-000-000',
            '0000', '9999', '000', '000',
            'Suspense - unclassified postings', 'EXP', 'OPS',
            'D', NULL, 1, 'Y',
            'Y', 'N', NULL, NULL,
            NULL, NULL, TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '99999', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6019, '0000-6350-000-000',
            '0000', '6350', '000', '000',
            'Warehouse expense (pre-2007 chart)', 'EXP', 'OPS',
            'D', NULL, 1, 'N',
            'N', 'N', NULL, NULL,
            NULL, NULL, TO_DATE('1998-01-01', 'YYYY-MM-DD'), TO_DATE('2006-12-31', 'YYYY-MM-DD'),
            'CLSD', '63500', 'N')
    INTO WWI_FIN.GL_ACCOUNT
        (GL_ACCOUNT_ID, ACCOUNT_CD,
         SEGMENT_1_CD, SEGMENT_2_CD, SEGMENT_3_CD, SEGMENT_4_CD, ACCOUNT_NAME, ACCOUNT_TYPE_CD, ACCOUNT_CLASS_CD,
         NORMAL_BALANCE_CD, PARENT_ACCOUNT_CD, ROLLUP_LEVEL_NBR, POSTING_ALLOWED_FLG,
         RECONCILIATION_FLG, INTERCOMPANY_FLG, STATUTORY_ACCOUNT_CD, IFRS_MAPPING_CD,
         US_GAAP_MAPPING_CD, CURRENCY_RESTRICT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT,
         ACCOUNT_STATUS_CD, OLD_ACCOUNT_CD, DELETED_FLG)
    VALUES (6020, '0000-1500-000-000',
            '0000', '1500', '000', '000',
            'Prepaid expenses', 'ASST', 'CUR',
            'D', NULL, 1, 'Y',
            'Y', 'N', 'B-II-5', 'IAS1-PRE',
            'ASC340', NULL, TO_DATE('2007-01-01', 'YYYY-MM-DD'), NULL,
            'ACTV', '15000', 'N')
SELECT * FROM DUAL
/

INSERT ALL
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5001, 'NA-CORP', 'North America corporate', 'NA', 'US',
            'US001', NULL, 1, 'M0100', 'Corporate Controller',
            '0000-6300-000-000', 'USD', 'M0100', 12500000.00000, 'FY2024',
            250000.00000, 'HEADCT', 'CHI-HQ', 'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL,
            'CORP')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5002, 'NA-WH-CHI', 'Chicago distribution centre', 'NA', 'US',
            'US001', 'NA-CORP', 2, 'M0210', 'Chicago DC Manager',
            '0000-6300-000-000', 'USD', 'M0100', 4800000.00000, 'FY2024',
            50000.00000, 'SQFT', 'CHI-DC1', 'Y', TO_DATE('1999-04-01', 'YYYY-MM-DD'), NULL,
            'WH01')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5003, 'NA-WH-DAL', 'Dallas distribution centre', 'NA', 'US',
            'US001', 'NA-CORP', 2, 'M0215', 'Dallas DC Manager',
            '0000-6300-000-000', 'USD', 'M0100', 3900000.00000, 'FY2024',
            50000.00000, 'SQFT', 'DAL-DC1', 'Y', TO_DATE('2003-09-01', 'YYYY-MM-DD'), NULL,
            'WH02')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5004, 'NA-PROC', 'North America procurement', 'NA', 'US',
            'US001', 'NA-CORP', 2, 'M0300', 'Director of Procurement',
            '0000-6300-000-000', 'USD', 'M0100', 1450000.00000, 'FY2024',
            500000.00000, 'HEADCT', 'CHI-HQ', 'Y', TO_DATE('1998-01-01', 'YYYY-MM-DD'), NULL,
            'PROC')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5005, 'CA-WH-TOR', 'Toronto warehouse', 'NA', 'CA',
            'CA001', 'NA-CORP', 2, 'M0220', 'Toronto Site Lead',
            '0000-6300-000-000', 'CAD', 'M0100', 2100000.00000, 'FY2024',
            40000.00000, 'SQFT', 'TOR-DC1', 'Y', TO_DATE('2006-01-01', 'YYYY-MM-DD'), NULL,
            'WH05')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5006, 'EU-CORP', 'Europe corporate', 'EU', 'NL',
            'NL001', NULL, 1, 'M0500', 'EMEA Finance Director',
            '0000-6300-000-000', 'EUR', 'M0500', 9800000.00000, 'FY2024',
            200000.00000, 'HEADCT', 'RTM-HQ', 'Y', TO_DATE('2000-01-01', 'YYYY-MM-DD'), NULL,
            'ECOR')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5007, 'EU-WH-RTM', 'Rotterdam hub', 'EU', 'NL',
            'NL001', 'EU-CORP', 2, 'M0510', 'Rotterdam Hub Manager',
            '0000-6300-000-000', 'EUR', 'M0500', 6200000.00000, 'FY2024',
            75000.00000, 'PALLET', 'RTM-DC1', 'Y', TO_DATE('2000-06-01', 'YYYY-MM-DD'), NULL,
            'WH10')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5008, 'EU-WH-MUC', 'Munich regional depot', 'EU', 'DE',
            'DE001', 'EU-CORP', 2, 'M0520', 'Munich Depot Manager',
            '0000-6300-000-000', 'EUR', 'M0500', 2750000.00000, 'FY2024',
            40000.00000, 'PALLET', 'MUC-DC1', 'Y', TO_DATE('2004-03-01', 'YYYY-MM-DD'), NULL,
            'WH11')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5009, 'EU-PROC', 'Europe procurement', 'EU', 'NL',
            'NL001', 'EU-CORP', 2, 'M0530', 'EMEA Category Lead',
            '0000-6300-000-000', 'EUR', 'M0500', 1200000.00000, 'FY2024',
            400000.00000, 'HEADCT', 'RTM-HQ', 'Y', TO_DATE('2000-01-01', 'YYYY-MM-DD'), NULL,
            'EPRC')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5010, 'EU-WH-DUB', 'Dublin depot (closed 2021)', 'EU', 'IE',
            'IE001', 'EU-CORP', 2, NULL, NULL,
            '0000-6300-000-000', 'EUR', 'M0500', NULL, NULL,
            NULL, 'PALLET', 'DUB-DC1', 'N', TO_DATE('2011-05-01', 'YYYY-MM-DD'), TO_DATE('2021-09-30', 'YYYY-MM-DD'),
            'WH12')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5011, 'AP-CORP', 'Asia Pacific corporate', 'APAC', 'SG',
            'SG001', NULL, 1, 'M0700', 'APAC Finance Director',
            '0000-6300-000-000', 'SGD', 'M0700', 7400000.00000, 'FY2025',
            150000.00000, 'HEADCT', 'SIN-HQ', 'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL,
            'ACOR')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5012, 'AP-WH-SYD', 'Sydney distribution centre', 'APAC', 'AU',
            'AU001', 'AP-CORP', 2, 'M0710', 'Sydney DC Manager',
            '0000-6300-000-000', 'AUD', 'M0700', 3300000.00000, 'FY2025',
            60000.00000, 'SQM', 'SYD-DC1', 'Y', TO_DATE('2006-07-01', 'YYYY-MM-DD'), NULL,
            'WH20')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5013, 'AP-WH-OSA', 'Osaka distribution centre', 'APAC', 'JP',
            'JP001', 'AP-CORP', 2, 'M0720', 'Osaka DC Manager',
            '0000-6300-000-000', 'JPY', 'M0700', 410000000.00000, 'FY2025',
            5000000.00000, 'SQM', 'OSA-DC1', 'Y', TO_DATE('2009-04-01', 'YYYY-MM-DD'), NULL,
            'WH21')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5014, 'AP-PROC', 'Asia Pacific procurement', 'APAC', 'SG',
            'SG001', 'AP-CORP', 2, 'M0730', 'APAC Sourcing Manager',
            '0000-6300-000-000', 'SGD', 'M0700', 900000.00000, 'FY2025',
            300000.00000, 'HEADCT', 'SIN-HQ', 'Y', TO_DATE('2006-04-01', 'YYYY-MM-DD'), NULL,
            'APRC')
    INTO WWI_FIN.COST_CENTER
        (COST_CENTER_ID, COST_CENTER_CD, COST_CENTER_NAME, REGION_CD, COUNTRY_CD,
         LEGAL_ENTITY_CD, PARENT_COST_CENTER_CD, HIERARCHY_LEVEL_NBR, MANAGER_CD, MANAGER_NAME_TXT,
         DEFAULT_GL_ACCOUNT_CD, FUNCTIONAL_CURR_CD, BUDGET_OWNER_CD, ANNUAL_BUDGET_AMT, BUDGET_FY_CD,
         APPROVAL_LIMIT_AMT, ALLOCATION_BASIS_CD, SITE_CD, ACTIVE_FLG, OPENED_DT, CLOSED_DT,
         LEGACY_DEPT_CD)
    VALUES (5015, 'AP-WH-AKL', 'Auckland depot', 'APAC', 'NZ',
            'NZ001', 'AP-CORP', 2, 'M0740', 'Auckland Depot Lead',
            '0000-6300-000-000', 'NZD', 'M0700', 1150000.00000, 'FY2025',
            30000.00000, 'SQM', 'AKL-DC1', 'Y', TO_DATE('2012-04-01', 'YYYY-MM-DD'), NULL,
            'WH22')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
