/* =====================================================================
 * Object       : Reference content - WWI_FIN.WITHHOLDING_RULE
 * Schema       : WWI_REF / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 111
 * Depends on   : oracle/tables/WWI_FIN.WITHHOLDING_RULE.sql, oracle/reference/05_tax_na_sales_and_use.sql
 * Called by    : run once per environment after the table DDL
 *
 * Withholding rules, which are three unrelated bodies of law sharing one
 * table.
 *
 * NA withholding is 1099 reporting: a box and a form, a backup withholding
 * rate that only applies when the supplier has no TIN on file, and an annual
 * threshold measured on the calendar year.
 *
 * EU withholding is treaty relief on cross-border interest and royalties: a
 * domestic rate, a lower treaty rate, the treaty article, and a certificate
 * requirement per payment.
 *
 * APAC withholding is domestic, per country, with a local form number and no
 * threshold at all in Japan.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4001, 'US_1099NEC', 'US non-employee compensation reporting', 'NA', 'US', 'US-IL',
            'INDIV', 'SERVICES', 0.00000, NULL, NULL,
            600.00000, 'USD', 'CALYR', 'N',
            '1', '1099-NEC', NULL, NULL,
            '0000-2300-000-000', TO_DATE('2020-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4002, 'US_1099MISC', 'US rents and other income reporting', 'NA', 'US', 'US-IL',
            'CORP', 'RENT', 0.00000, NULL, NULL,
            600.00000, 'USD', 'CALYR', 'N',
            '1', '1099-MISC', NULL, NULL,
            '0000-2300-000-000', TO_DATE('2020-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4003, 'US_BACKUP', 'US backup withholding, no TIN on file', 'NA', 'US', 'US-IL',
            'INDIV', 'SERVICES', 24.00000, NULL, NULL,
            0.00000, 'USD', 'INVOICE', 'Y',
            '4', '1099-NEC', NULL, NULL,
            '0000-2300-000-000', TO_DATE('2018-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4004, 'CA_NR', 'Canada non-resident services withholding', 'NA', 'CA', NULL,
            'CORP', 'SERVICES', 15.00000, NULL, NULL,
            0.00000, 'CAD', 'INVOICE', 'N',
            NULL, NULL, NULL, NULL,
            '0000-2300-000-000', TO_DATE('2005-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4005, 'DE_ROY', 'German royalty withholding with treaty relief', 'EU', 'DE', 'DE-VAT',
            'CORP', 'ROYALTY', 15.82500, 5.00000, 'NL',
            NULL, NULL, NULL, 'Y',
            NULL, NULL, 'Article 12 DE-NL double tax treaty', NULL,
            '0000-2300-000-000', TO_DATE('2012-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4006, 'FR_INT', 'French interest withholding', 'EU', 'FR', 'FR-VAT',
            'CORP', 'INTEREST', 12.80000, 0.00000, 'DE',
            NULL, NULL, NULL, 'Y',
            NULL, NULL, 'Article 11 FR-DE double tax treaty', NULL,
            '0000-2300-000-000', TO_DATE('2018-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4007, 'IE_PSWT', 'Irish professional services withholding tax', 'EU', 'IE', 'IE-VAT',
            'CORP', 'SERVICES', 20.00000, NULL, NULL,
            0.00000, 'EUR', 'INVOICE', 'Y',
            NULL, NULL, 'TCA 1997 Chapter 1 Part 18', NULL,
            '0000-2300-000-000', TO_DATE('2002-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4008, 'JP_DOM', 'Japan domestic withholding on professional fees', 'APAC', 'JP', 'JP-CONS',
            'INDIV', 'SERVICES', 10.21000, NULL, NULL,
            NULL, NULL, NULL, 'N',
            NULL, NULL, NULL, 'Form 3-2',
            '0000-2300-000-000', TO_DATE('2013-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4009, 'SG_NR', 'Singapore non-resident withholding', 'APAC', 'SG', 'SG-GST',
            'CORP', 'SERVICES', 17.00000, 10.00000, 'AU',
            0.00000, 'SGD', 'INVOICE', 'Y',
            NULL, NULL, NULL, 'IR37',
            '0000-2300-000-000', TO_DATE('2010-01-01', 'YYYY-MM-DD'), NULL, 'Y')
    INTO WWI_FIN.WITHHOLDING_RULE
        (WHT_RULE_ID, WHT_RULE_CD, RULE_DESC, REGION_CD, COUNTRY_CD, JURISDICTION_CD,
         SUPPLIER_TYPE_CD, INCOME_TYPE_CD, WHT_RATE_PCT, TREATY_RATE_PCT, TREATY_COUNTRY_CD,
         THRESHOLD_AMT, THRESHOLD_CURR_CD, THRESHOLD_BASIS_CD, CERTIFICATE_REQ_FLG,
         NA_1099_BOX_CD, NA_1099_FORM_CD, EU_TREATY_ARTICLE_TXT, APAC_FORM_CD,
         WHT_LIABILITY_ACCT_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT, ACTIVE_FLG)
    VALUES (4010, 'AU_NOABN', 'Australian no-ABN withholding', 'APAC', 'AU', 'AU-GST',
            'CORP', 'SERVICES', 47.00000, NULL, NULL,
            75.00000, 'AUD', 'INVOICE', 'N',
            NULL, NULL, NULL, 'NAT3346',
            '0000-2300-000-000', TO_DATE('2006-07-01', 'YYYY-MM-DD'), NULL, 'Y')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
