"""Render the feed manifest the preflight reads.

config/landing-zone.yaml is the source of truth for where a feed lands, what it
is called and how it is encoded, but the preflight runs on the execution host in
PowerShell, where parsing YAML means shipping a module. Rendering the same facts
to JSON keeps one source of truth and gives the preflight something it can read
with ConvertFrom-Json.

Usage: python tools/landing/render_feed_manifest.py [--check]

``--check`` re-renders in memory and fails when the tracked file is stale, which
is what the static validation calls so a landing-zone edit cannot silently leave
the preflight checking yesterday's layout.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CONFIG_PATH = os.path.join(REPO_ROOT, "config", "landing-zone.yaml")
OUTPUT_PATH = os.path.join(REPO_ROOT, "deployment", "preflight", "feed-manifest.json")

HEADER = (
    "Generated by tools/landing/render_feed_manifest.py from config/landing-zone.yaml. "
    "Do not edit by hand."
)


def render():
    with open(CONFIG_PATH) as handle:
        config = yaml.safe_load(handle)

    feeds = []
    working = []
    for directory in config["directories"].values():
        for entry in directory.get("working_subdirectories", []) or []:
            working.append(
                {
                    "relative_path": entry["path"],
                    "written_by": entry["written_by"],
                    "drained_by": entry["drained_by"],
                }
            )
        for entry in directory.get("subdirectories", []) or []:
            consumer = entry.get("consumed_by")
            if not consumer:
                continue
            stem, _, extension = entry["pattern"].rpartition(".")
            prefix = stem.split("{")[0].rstrip("_")
            feeds.append(
                {
                    "feed": entry["feeds"][0],
                    "consumed_by": consumer,
                    "relative_path": entry["path"],
                    "file_spec": ("%s_*.%s" % (prefix, extension)) if prefix else "*",
                    "encoding": entry["encoding"],
                    "delimiter": entry["delimiter"],
                    "header": bool(entry["header"]),
                    "raw_table": entry["raw_table"],
                }
            )

    feeds.sort(key=lambda item: item["feed"])
    return {
        "_generated_by": HEADER,
        "root_variable": config["root_variable"],
        "top_level_directories": sorted(config["directories"].keys()),
        "working_directories": sorted(working, key=lambda item: item["relative_path"]),
        "feeds": feeds,
    }


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the tracked file is stale")
    args = parser.parse_args(argv)

    payload = json.dumps(render(), indent=2) + "\n"

    if args.check:
        if not os.path.exists(OUTPUT_PATH):
            print("%s is missing; run tools/landing/render_feed_manifest.py" % OUTPUT_PATH)
            return 1
        with open(OUTPUT_PATH) as handle:
            if handle.read() != payload:
                print("%s is stale; run tools/landing/render_feed_manifest.py" % OUTPUT_PATH)
                return 1
        return 0

    with open(OUTPUT_PATH, "w") as handle:
        handle.write(payload)
    print(os.path.relpath(OUTPUT_PATH, REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
