# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_EU_Load_Customer
# MAGIC Dimension.Customer (EU) - hybrid SCD, EU conditioning / consent / retention rules
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_EU_Load_Customer.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_MigrateStagedCustomerData` (RegionCode = EU); regional rules baselined by `validation/runtime/04_regional_divergence.sql`. Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_customer` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import customer, runtime, specs  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_EU_Load_Customer"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

REGION_CODE = "EU"

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.CUSTOMER
    dimTable = naming.table(catalog, "gold", spec.tableName)

    load = customer.loadRegionalCustomers(
        spark, catalog, REGION_CODE, batchId, packageExecutionId, businessDate, loadTimestamp, reloadFullHistory)
    result = load.scdResult
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, customer.REJECT_OBJECT_NAME, load.rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        sourceSystemCode=None, rejectStage="Dimension", businessKeyColumn="CustomerBusinessKey",
    )
    run.rowsRead = load.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, f"Dimension.Customer[{REGION_CODE}]",
        sourceRowCount=load.rowsRead,
        targetRowCount=spark.table(dimTable).where((F.col("IsCurrentRow") == True) & (F.col("CustomerKey") > 0) & (F.col("RegionCode") == REGION_CODE)).count(),  # noqa: E712
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    control.logRowCount(spark, catalog, packageExecutionId, "work.LateArrivingDimensionQueue", insertRowCount=load.rowsQueuedLateArriving)
    print(f"{PACKAGE_NAME} [{REGION_CODE}]: {result} rejected={rowsRejected}")
