# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Load_CustomerSegment
# MAGIC Dimension.Customer Segment - SCD2 + customer segment assignment
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Load_CustomerSegment.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_MigrateStagedCustomerSegmentData` (segments, then consent-aware customer assignment). Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_customer_segment` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import loaders, runtime, scd, specs, tables  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Load_CustomerSegment"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.CUSTOMER_SEGMENT
    dimTable = naming.table(catalog, "gold", spec.tableName)
    runtime.prepareDimension(spark, catalog, spec)

    staged = runtime.filterBatch(spark.table(naming.table(catalog, "silver", "stg_customer_segment")), batchId, reloadFullHistory)
    valid, rejected = runtime.splitRejects(staged)
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "stg.CustomerSegment", rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Dimension", businessKeyColumn="SegmentBusinessKey",
    )
    source = loaders.transformCustomerSegment(valid)

    result = scd.applyScd(spark, catalog, spec, source, batchId, packageExecutionId, loadTimestamp=loadTimestamp)

    # Customer -> segment assignment (Type 1 on the current customer row; consent / model exclusions -> default / -2)
    assignmentTable = naming.table(catalog, "silver", "stg_customer_segment_assignment")
    assignedCustomers = 0
    if tables.tableExists(spark, assignmentTable) and tables.tableExists(spark, specs.CUSTOMER.fullTableName(catalog)):
        assignments = runtime.filterBatch(spark.table(assignmentTable), batchId, reloadFullHistory)
        assignments, assignmentRejects = runtime.splitRejects(assignments)
        rowsRejected += control.logRejectedRecordSet(
            spark, catalog, "stg.CustomerSegmentAssignment", assignmentRejects, batchId=batchId,
            packageExecutionId=packageExecutionId, rejectStage="Dimension", businessKeyColumn="CustomerBusinessKey")
        segmentKeys = loaders.resolveSegmentAssignments(assignments, scd.currentMembers(spark, catalog, spec))
        assignedCustomers = scd.applyType1Overwrite(
            spark, catalog, specs.CUSTOMER, segmentKeys, ["CustomerSegmentKey"], batchId, packageExecutionId, currentOnly=True)
    control.logRowCount(spark, catalog, packageExecutionId, "Dimension.Customer.CustomerSegmentKey", updateRowCount=assignedCustomers)
    run.rowsRead = result.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, runtime.legacyObjectName(spec),
        sourceRowCount=result.rowsRead,
        targetRowCount=runtime.targetRowCount(spark, catalog, spec),
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    print(f"{PACKAGE_NAME}: {result}")
