# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Load_StockItem
# MAGIC Dimension.Stock Item - hybrid SCD with inferred-member enrichment
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Load_StockItem.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_MigrateStagedStockItemData` / `usp_InsertInferredMember`. Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_stock_item` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import loaders, runtime, scd, specs, tables  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Load_StockItem"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.STOCK_ITEM
    dimTable = naming.table(catalog, "gold", spec.tableName)
    runtime.prepareDimension(spark, catalog, spec)

    productTable = naming.table(catalog, "silver", "stg_product")
    product = runtime.filterBatch(spark.table(productTable), batchId, reloadFullHistory) if tables.tableExists(spark, productTable) else None
    staged = runtime.filterBatch(spark.table(naming.table(catalog, "silver", "stg_stock_item")), batchId, reloadFullHistory)
    valid, rejected = runtime.splitRejects(staged)
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "stg.StockItem", rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Dimension", businessKeyColumn="StockItemBusinessKey",
    )
    source = loaders.transformStockItem(valid, product)

    # Lookups: primary Supplier and Product Category (unmatched supplier -> -1 + late-arriving queue)
    source = runtime.lookupSurrogateKey(spark, catalog, source, specs.SUPPLIER, "PrimarySupplierId", "PrimarySupplierKey")
    source = runtime.lookupSurrogateKey(spark, catalog, source, specs.PRODUCT_CATEGORY, "CategoryCode", "ProductCategoryKey")
    rowsQueued = runtime.queueLateArrivingMembers(
        spark, catalog, source, specs.SUPPLIER.name, "PrimarySupplierId", "PrimarySupplierKey",
        batchId, packageExecutionId, "Dimension.Stock Item", loadTimestamp)
    result = scd.applyScd(spark, catalog, spec, source, batchId, packageExecutionId, loadTimestamp=loadTimestamp)

    run.rowsRead = result.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, runtime.legacyObjectName(spec),
        sourceRowCount=result.rowsRead,
        targetRowCount=runtime.targetRowCount(spark, catalog, spec),
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    print(f"{PACKAGE_NAME}: {result}")
