# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Rekey_LateArriving
# MAGIC Late-arriving dimension queue: resolve, stub, escalate and repoint facts
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Rekey_LateArriving.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_ResolveLateArrivingMembers` / `usp_RekeyFacts` (retry thresholds NA=3, EU=7, APAC=21, default 5). Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_* (+ silver.work_fact_rekey_queue)` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import rekey, runtime, specs, tables  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Rekey_LateArriving"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

maxQueueAgeDays = int(runtime.configurationOrDefault(control, spark, catalog, "Dimension.LateArriving.MaxQueueAgeDays", environmentCode, str(rekey.DEFAULT_MAX_QUEUE_AGE_DAYS)))

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName="Rekey Late Arriving") as run:
    packageExecutionId = run.packageExecutionId
    queueTable = naming.table(catalog, "silver", "work_late_arriving_dimension_queue")
    rekeyQueueTable = naming.table(catalog, "silver", "work_fact_rekey_queue")

    outcome = rekey.runRekey(spark, catalog, batchId, packageExecutionId, businessDate, maxQueueAgeDays=maxQueueAgeDays, now=loadTimestamp)
    result = outcome["result"]

    # Escalated / manual-intervention rows are surfaced as rejects (err.RejectedLookupFailure in the legacy estate)
    escalated = outcome["escalated"].select(
        F.col("MissingBusinessKey").alias("BusinessKey"), F.col("DimensionName"), F.col("SourceSystemCode"),
        F.col("EscalationCode").alias("RejectReasonCode"), F.col("RetryCount"), F.col("QueueAgeDays"))
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "work.LateArrivingDimensionQueue", escalated, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Rekey", rejectReasonCode=rekey.ESCALATION_ERROR_CODE, businessKeyColumn="BusinessKey")

    run.rowsRead = result.queueDepth
    run.rowsInserted = result.rowsStubbed
    run.rowsUpdated = result.factRowsRekeyed
    run.rowsRejected = rowsRejected
    control.logRowCount(spark, catalog, packageExecutionId, "work.LateArrivingDimensionQueue",
                        sourceRowCount=result.queueDepth, updateRowCount=result.rowsResolved + result.rowsRetried,
                        rejectRowCount=result.rowsEscalated,
                        targetRowCount=spark.table(queueTable).where("ResolvedFlag = false").count())
    control.logRowCount(spark, catalog, packageExecutionId, "work.FactRekeyQueue",
                        insertRowCount=spark.table(rekeyQueueTable).where(F.col("BatchId") == batchId).count(),
                        updateRowCount=result.factRowsRekeyed, targetRowCount=result.remainingUnknownFacts)
    for factTable in sorted({factTable for _, factTable, _ in specs.FACT_REKEY_TARGETS}):
        if factTable in result.skippedFactTables:
            continue
        control.logRowCount(spark, catalog, packageExecutionId, f"Fact.{factTable}", updateRowCount=result.factRowsRekeyed)
    if result.skippedFactTables:
        control.logError(spark, catalog, packageExecutionId=packageExecutionId, batchId=batchId, errorSeverity="Warning",
                         errorCode="REKEY_FACT_MISSING", sourceName=PACKAGE_NAME, sourceComponent="repointFacts",
                         errorDescription=f"Fact tables not yet present, rekey deferred: {', '.join(sorted(set(result.skippedFactTables)))}")
    print(f"{PACKAGE_NAME}: {result}")
