# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Load_VendorContract
# MAGIC Dimension.Vendor Contract - SCD2 (contract status / amounts / dates)
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Load_VendorContract.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_MigrateStagedVendorContractData` (incl. expiry of lapsed contracts). Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_vendor_contract` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import loaders, runtime, scd, specs  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Load_VendorContract"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.VENDOR_CONTRACT
    dimTable = naming.table(catalog, "gold", spec.tableName)
    runtime.prepareDimension(spark, catalog, spec)

    staged = runtime.filterBatch(spark.table(naming.table(catalog, "silver", "stg_vendor_contract")), batchId, reloadFullHistory)
    valid, rejected = runtime.splitRejects(staged)
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "stg.VendorContract", rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Dimension", businessKeyColumn="ContractBusinessKey",
    )
    source = loaders.transformVendorContract(valid, businessDate)

    # Lookup: Supplier (full cache, unmatched -> -1 Unknown and queued as late arriving)
    source = runtime.lookupSurrogateKey(spark, catalog, source, specs.SUPPLIER, "SupplierBusinessKey", "SupplierKey")
    rowsQueued = runtime.queueLateArrivingMembers(
        spark, catalog, source, specs.SUPPLIER.name, "SupplierBusinessKey", "SupplierKey",
        batchId, packageExecutionId, "Dimension.Vendor Contract", loadTimestamp)
    result = scd.applyScd(spark, catalog, spec, source, batchId, packageExecutionId, loadTimestamp=loadTimestamp)

    run.rowsRead = result.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, runtime.legacyObjectName(spec),
        sourceRowCount=result.rowsRead,
        targetRowCount=runtime.targetRowCount(spark, catalog, spec),
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    print(f"{PACKAGE_NAME}: {result}")
