# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Load_Promotion
# MAGIC Dimension.Promotion - SCD2 with campaign duration, overlap and regional tax treatment
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Load_Promotion.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_MigrateStagedPromotionData`. Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_promotion` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import loaders, runtime, scd, specs  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Load_Promotion"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.PROMOTION
    dimTable = naming.table(catalog, "gold", spec.tableName)
    runtime.prepareDimension(spark, catalog, spec)

    staged = runtime.filterBatch(spark.table(naming.table(catalog, "silver", "stg_promotion")), batchId, reloadFullHistory)
    valid, rejected = runtime.splitRejects(staged)
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "stg.Promotion", rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Dimension", businessKeyColumn="PromotionBusinessKey",
    )
    source = loaders.transformPromotion(valid)

    result = scd.applyScd(spark, catalog, spec, source, batchId, packageExecutionId, loadTimestamp=loadTimestamp)

    run.rowsRead = result.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, runtime.legacyObjectName(spec),
        sourceRowCount=result.rowsRead,
        targetRowCount=runtime.targetRowCount(spark, catalog, spec),
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    print(f"{PACKAGE_NAME}: {result}")
