# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Load_City
# MAGIC Dimension.City - SCD2 with population-change threshold and inferred-member promotion
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Load_City.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_LoadCityDimension` (PopulationChangeThresholdPercent package parameter). Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_city` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import loaders, runtime, scd, specs  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Load_City"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.CITY
    dimTable = naming.table(catalog, "gold", spec.tableName)
    runtime.prepareDimension(spark, catalog, spec)

    staged = runtime.filterBatch(spark.table(naming.table(catalog, "silver", "stg_city")), batchId, reloadFullHistory)
    valid, rejected = runtime.splitRejects(staged)
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "stg.City", rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Dimension", businessKeyColumn="CityBusinessKey",
    )
    source = loaders.transformCity(valid)

    source = runtime.lookupSurrogateKey(spark, catalog, source, specs.SALES_TERRITORY, "SalesTerritoryCode", "SalesTerritoryKey")
    thresholdPercent = float(runtime.configurationOrDefault(
        control, spark, catalog, "Dimension.City.PopulationChangeThresholdPercent", environmentCode, "5.0"))
    source = loaders.applyPopulationThreshold(source, scd.currentMembers(spark, catalog, spec), thresholdPercent)
    populationType1 = source.where(F.col("_PopulationType1").isNotNull()).select(
        "CityBusinessKey", F.col("_PopulationType1").alias("LatestRecordedPopulation"))
    source = source.drop("_PopulationType1")
    result = scd.applyScd(spark, catalog, spec, source, batchId, packageExecutionId, loadTimestamp=loadTimestamp)

    # Sub-threshold population drift: Type 1 write-through across every version, no new row
    populationCorrections = scd.applyType1Overwrite(spark, catalog, spec, populationType1, ["LatestRecordedPopulation"], batchId, packageExecutionId)
    control.logRowCount(spark, catalog, packageExecutionId, "Dimension.City.PopulationType1", updateRowCount=populationCorrections)
    run.rowsRead = result.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, runtime.legacyObjectName(spec),
        sourceRowCount=result.rowsRead,
        targetRowCount=runtime.targetRowCount(spark, catalog, spec),
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    print(f"{PACKAGE_NAME}: {result}")
