# Databricks notebook source
# MAGIC %md
# MAGIC # DIM_Load_Salesperson
# MAGIC Dimension.Salesperson - SCD2 + Salesperson/Territory bridge
# MAGIC
# MAGIC Port of `ssis/07_dimensions/DIM_Load_Salesperson.dtsx` (generated by `build_dimension_packages.py`) and
# MAGIC `Integration.usp_MigrateStagedSalespersonData` / `usp_MaintainSalespersonTerritoryBridge`. Reads `silver.stg_*` / `silver.ref_*`, writes `gold.dim_salesperson` with Delta MERGE through
# MAGIC the shared `wwi_dimensions` helpers; batch / package / row-count / reject logging goes through `dbx_etl_common`.

# COMMAND ----------

import os
import sys
from datetime import datetime, timezone

from pyspark.sql import functions as F

from dbx_etl_common import control, params, naming

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..", "src")))
from wwi_dimensions import employee, loaders, runtime, scd, specs, tables  # noqa: E402

# COMMAND ----------

p = params.getJobParams(dbutils)
catalog = p["catalog"]
batchId = p["batchId"]
businessDate = p["businessDate"]
reloadFullHistory = p["reloadFullHistory"]
environmentCode = p["environmentCode"]
PACKAGE_NAME = "DIM_Load_Salesperson"
loadTimestamp = datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)

# COMMAND ----------

with control.packageRun(spark, catalog, batchId, PACKAGE_NAME, projectName=runtime.PROJECT_NAME, stepName=runtime.STEP_NAME) as run:
    packageExecutionId = run.packageExecutionId
    spec = specs.SALESPERSON
    dimTable = naming.table(catalog, "gold", spec.tableName)
    runtime.prepareDimension(spark, catalog, spec)

    staged = runtime.filterBatch(spark.table(naming.table(catalog, "silver", "stg_salesperson")), batchId, reloadFullHistory)
    valid, rejected = runtime.splitRejects(staged)
    rowsRejected = control.logRejectedRecordSet(
        spark, catalog, "stg.Salesperson", rejected, batchId=batchId, packageExecutionId=packageExecutionId,
        rejectStage="Dimension", businessKeyColumn="SalespersonBusinessKey",
    )
    source = loaders.transformSalesperson(valid)

    # Lookups: Employee (current row) and Sales Territory; RegionCode inherited from the territory
    source = runtime.lookupSurrogateKey(spark, catalog, source, specs.EMPLOYEE, "EmployeeBusinessKey", "EmployeeKey")
    source = runtime.lookupSurrogateKey(spark, catalog, source, specs.SALES_TERRITORY, "SalesTerritoryCode", "SalesTerritoryKey")
    if tables.tableExists(spark, specs.SALES_TERRITORY.fullTableName(catalog)):
        territories = spark.table(specs.SALES_TERRITORY.fullTableName(catalog)).select(
            F.col("SalesTerritoryCode").alias("_tc"), F.col("RegionCode").alias("_tr")).where("SalesTerritoryKey > 0")
        source = source.join(territories, source["SalesTerritoryCode"] == F.col("_tc"), "left").withColumn(
            "RegionCode", F.coalesce(F.col("_tr"), F.lit("GLOBAL"))).drop("_tc", "_tr")
    else:
        source = source.withColumn("RegionCode", F.lit("GLOBAL"))
    rowsQueued = runtime.queueLateArrivingMembers(
        spark, catalog, source, specs.EMPLOYEE.name, "EmployeeBusinessKey", "EmployeeKey",
        batchId, packageExecutionId, "Dimension.Salesperson", loadTimestamp)
    result = scd.applyScd(spark, catalog, spec, source, batchId, packageExecutionId, loadTimestamp=loadTimestamp)

    bridge = employee.maintainTerritoryBridge(spark, catalog, loadTimestamp, lineageKey=packageExecutionId)
    control.logRowCount(spark, catalog, packageExecutionId, "Dimension.SalespersonTerritoryBridge",
                        insertRowCount=bridge["opened"], updateRowCount=bridge["closed"],
                        targetRowCount=spark.table(naming.table(catalog, "gold", "dim_salesperson_territory_bridge")).count())
    run.rowsRead = result.rowsRead
    run.rowsInserted = result.rowsWritten
    run.rowsUpdated = result.rowsUpdated
    run.rowsRejected = rowsRejected
    control.logRowCount(
        spark, catalog, packageExecutionId, runtime.legacyObjectName(spec),
        sourceRowCount=result.rowsRead,
        targetRowCount=runtime.targetRowCount(spark, catalog, spec),
        insertRowCount=result.rowsWritten,
        updateRowCount=result.rowsUpdated,
        rejectRowCount=rowsRejected,
    )
    print(f"{PACKAGE_NAME}: {result}")
