-- SQL*Loader control file for WWI_FIN.AP_INVOICE_HDR
-- Generated by generators/generate.py from the deployed table contract.
-- Target: Oracle WWI_FIN.AP_INVOICE_HDR in the ERP database (service $ORACLE_SERVICE).
-- Data file: ../../../data/oracle/WWI_FIN/AP_INVOICE_HDR.dat
-- Run with: sqlldr control=WWI_FIN.AP_INVOICE_HDR.ctl log=WWI_FIN.AP_INVOICE_HDR.log

OPTIONS (ERRORS=10000, ROWS=50000, BINDSIZE=16777216, READSIZE=16777216)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE '../../../data/oracle/WWI_FIN/AP_INVOICE_HDR.dat'
BADFILE 'WWI_FIN.AP_INVOICE_HDR.bad'
DISCARDFILE 'WWI_FIN.AP_INVOICE_HDR.dsc'
APPEND
INTO TABLE WWI_FIN.AP_INVOICE_HDR
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
    INVOICE_ID                       CHAR(40),
    INVOICE_NBR                      CHAR(30),
    SUPP_ID                          CHAR(40),
    INVOICE_DT                       DATE "YYYY-MM-DD",
    RECEIVED_DT                      DATE "YYYY-MM-DD" NULLIF RECEIVED_DT=BLANKS,
    GL_DATE                          DATE "YYYY-MM-DD",
    PERIOD_CD                        CHAR(7),
    REGION_CD                        CHAR(4),
    LEGAL_ENTITY_CD                  CHAR(6),
    INVOICE_CURR_CD                  CHAR(3),
    FX_RATE                          CHAR(40),
    GROSS_AMT                        CHAR(40),
    NET_AMT                          CHAR(40),
    TAX_AMT                          CHAR(40),
    WITHHELD_AMT                     CHAR(40),
    PAYMENT_TERMS_CD                 CHAR(8),
    DUE_DT                           DATE "YYYY-MM-DD" NULLIF DUE_DT=BLANKS,
    INVOICE_STATUS_CD                CHAR(4),
    SCANNED_IMAGE_REF                CHAR(200),
    SOURCE_SYS                       CHAR(12),
    CREATED_BY                       CHAR(30),
    CREATED_DT                       DATE "YYYY-MM-DD",
    UPDATED_BY                       CHAR(30),
    UPDATED_DT                       DATE "YYYY-MM-DD" NULLIF UPDATED_DT=BLANKS
)
