-- SQL*Loader control file for WWI_FIN.AP_INVOICE_HDR
-- Generated by generators/generate.py from the table specification.
-- Target: Oracle WWI_FIN.AP_INVOICE_HDR in the ERP database (service $ORACLE_SERVICE).
-- Data file: ../../../data/oracle/WWI_FIN/AP_INVOICE_HDR.dat
-- Run with: sqlldr control=WWI_FIN.AP_INVOICE_HDR.ctl log=WWI_FIN.AP_INVOICE_HDR.log

OPTIONS (ERRORS=10000, ROWS=50000, BINDSIZE=16777216, READSIZE=16777216)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE '../../../data/oracle/WWI_FIN/AP_INVOICE_HDR.dat'
BADFILE 'WWI_FIN.AP_INVOICE_HDR.bad'
DISCARDFILE 'WWI_FIN.AP_INVOICE_HDR.dsc'
APPEND
INTO TABLE WWI_FIN.AP_INVOICE_HDR
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
    INVOICE_NO                       CHAR(20),
    SUPP_CODE                        CHAR(12),
    PO_NO                            CHAR(14),
    REGION_CD                        CHAR(4),
    CURRENCY_CD                      CHAR(3),
    INVOICE_DT                       DATE "YYYY-MM-DD",
    RECEIVED_DT                      DATE "YYYY-MM-DD",
    DUE_DT                           DATE "YYYY-MM-DD",
    GL_DT                            DATE "YYYY-MM-DD",
    GROSS_AMT                        CHAR(40),
    NET_AMT                          CHAR(40),
    TAX_AMT                          CHAR(40),
    WITHHOLDING_AMT                  CHAR(40),
    BASE_AMT                         CHAR(40),
    BASE_CURRENCY_CD                 CHAR(3),
    FX_RATE                          CHAR(40),
    FX_TYPE_CD                       CHAR(16),
    STATUS_CD                        CHAR(10),
    HOLD_CD                          CHAR(10),
    PAYMENT_TERMS_CD                 CHAR(8),
    MATCHED_FLG                      CHAR(1),
    SUPPLIER_INVOICE_REF             CHAR(30),
    SRC_SYSTEM_CD                    CHAR(8),
    CREATED_BY                       CHAR(30),
    CREATED_TS                       TIMESTAMP "YYYY-MM-DD HH24:MI:SS",
    PERIOD_CD                        CHAR(12)
)
