<#
    Builds the WWI SSIS projects into .ispac deployment files.

    The estate's packages are generated by tools/ssisgen into ssis/<NN_area>/,
    one Visual Studio project per area, so this script builds every .dtproj it
    finds under ssis/ and writes one .ispac per project. -Project filters that
    list by project name when a single area is being redeployed.

    Three build paths are supported, because the estate has all three kinds of
    host:

      * devenv.com against each .dtproj - what the build server does when Visual
        Studio with the Integration Services projects extension is installed;
      * SSISBuild.exe (the standalone SSIS DevOps build tool) - what the newer
        agents have instead of Visual Studio;
      * a hand-rolled .ispac (a zip of the manifest, the project parameters, the
        connection managers and the project's .dtsx files) - the fallback for
        hosts with neither. It has always been the awkward part of this build.

    This script has not been executed on a build host.

    Usage: .\deployment\ssis\Build-SsisProject.ps1 [-OutputPath artifacts] [-DryRun]
#>

[CmdletBinding()]
param(
    [string] $OutputPath = 'artifacts',
    [string] $Configuration = 'Development',
    [string[]] $Project,
    [switch] $ForceZipFallback,
    [switch] $DryRun
)

. (Join-Path (Join-Path (Join-Path $PSScriptRoot '..') 'lib') 'Common.ps1')
$script:WwiLogPrefix = 'wwi-build-ssis'

$repoRoot = Get-WwiRepositoryRoot
$ssisRoot = Join-Path $repoRoot 'ssis'
$artifacts = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $repoRoot $OutputPath }

if (-not (Test-Path $ssisRoot)) { Stop-WwiWithError "ssis/ is not present in $repoRoot." }

# obj\ holds build intermediates, including a copy of the .dtproj; building it
# would produce a second .ispac for the same project.
$projects = @(
    Get-ChildItem -Path $ssisRoot -Filter '*.dtproj' -Recurse -File |
        Where-Object { $_.FullName -notmatch '\\obj\\' } |
        Sort-Object FullName
)
if ($Project) {
    $projects = @($projects | Where-Object { $Project -contains $_.BaseName })
}
if ($projects.Count -eq 0) { Stop-WwiWithError 'no .dtproj projects found under ssis/.' }

if (-not $DryRun -and -not (Test-Path $artifacts)) {
    New-Item -ItemType Directory -Path $artifacts -Force | Out-Null
}

$devenv = Get-Command devenv.com -ErrorAction SilentlyContinue
$ssisBuild = Get-Command SSISBuild.exe -ErrorAction SilentlyContinue

function Build-WwiIspacFromFolder {
    <# Zips a project folder into an .ispac when no SSIS build tool is present. #>
    param(
        [Parameter(Mandatory)][string] $ProjectDirectory,
        [Parameter(Mandatory)][string] $ProjectName,
        [Parameter(Mandatory)][string] $IspacPath
    )

    $packages = @(Get-ChildItem -Path $ProjectDirectory -Filter '*.dtsx' -File)
    if ($packages.Count -eq 0) {
        Stop-WwiWithError "no .dtsx packages found in $ProjectDirectory."
    }

    $staging = Join-Path ([System.IO.Path]::GetTempPath()) ("wwi-ispac-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $staging -Force | Out-Null
    try {
        foreach ($package in $packages) { Copy-Item -Path $package.FullName -Destination $staging -Force }
        foreach ($extra in @('*.params', '*.conmgr')) {
            Get-ChildItem -Path $ProjectDirectory -Filter $extra -File -ErrorAction SilentlyContinue |
                ForEach-Object { Copy-Item -Path $_.FullName -Destination $staging -Force }
        }

        # The manifest lists every part; ISDeploymentWizard rejects an .ispac
        # whose manifest and contents disagree, which is how the fallback used
        # to fail silently before the manifest was generated from the folder.
        $manifest = [xml] @"
<?xml version="1.0" encoding="utf-8"?>
<SSIS:Project SSIS:ProtectionLevel="DontSaveSensitive" xmlns:SSIS="www.microsoft.com/SqlServer/SSIS">
  <SSIS:Properties>
    <SSIS:Property SSIS:Name="Name">$ProjectName</SSIS:Property>
    <SSIS:Property SSIS:Name="VersionMajor">1</SSIS:Property>
    <SSIS:Property SSIS:Name="VersionMinor">0</SSIS:Property>
  </SSIS:Properties>
  <SSIS:Packages />
  <SSIS:ConnectionManagers />
</SSIS:Project>
"@
        $packagesNode = $manifest.SelectSingleNode('//*[local-name()="Packages"]')
        foreach ($package in $packages) {
            $node = $manifest.CreateElement('SSIS', 'Package', 'www.microsoft.com/SqlServer/SSIS')
            $node.SetAttribute('Name', 'www.microsoft.com/SqlServer/SSIS', $package.Name)
            $node.SetAttribute('EntryPoint', 'www.microsoft.com/SqlServer/SSIS',
                               $(if ($package.Name -like 'Master_*') { '1' } else { '0' }))
            [void] $packagesNode.AppendChild($node)
        }
        $connectionsNode = $manifest.SelectSingleNode('//*[local-name()="ConnectionManagers"]')
        foreach ($connection in (Get-ChildItem -Path $ProjectDirectory -Filter '*.conmgr' -File -ErrorAction SilentlyContinue)) {
            $node = $manifest.CreateElement('SSIS', 'ConnectionManager', 'www.microsoft.com/SqlServer/SSIS')
            $node.SetAttribute('Name', 'www.microsoft.com/SqlServer/SSIS', $connection.Name)
            [void] $connectionsNode.AppendChild($node)
        }
        $manifest.Save((Join-Path $staging '@Project.manifest'))

        if (Test-Path $IspacPath) { Remove-Item $IspacPath -Force }
        Compress-Archive -Path (Join-Path $staging '*') -DestinationPath "$IspacPath.zip" -Force
        Move-Item -Path "$IspacPath.zip" -Destination $IspacPath -Force
    }
    finally {
        Remove-Item -Path $staging -Recurse -Force -ErrorAction SilentlyContinue
    }
}

$built = @()

foreach ($dtproj in $projects) {
    $projectName = $dtproj.BaseName
    $projectDir = $dtproj.DirectoryName
    $ispacPath = Join-Path $artifacts "$projectName.ispac"
    $packageCount = @(Get-ChildItem -Path $projectDir -Filter '*.dtsx' -File).Count

    if ($DryRun) {
        Write-WwiLog "WHATIF build $projectName ($Configuration) -> $ispacPath"
        Write-WwiLog ("WHATIF include {0} package(s), project parameters and connection managers" -f $packageCount)
        continue
    }

    if ($devenv -and -not $ForceZipFallback) {
        Invoke-WwiCommand -Description "devenv build $projectName" `
                          -FilePath $devenv.Source `
                          -ArgumentList @($dtproj.FullName, '/Build', $Configuration) | Out-Null
        $output = Get-ChildItem -Path $projectDir -Filter "$projectName.ispac" -Recurse -File |
                  Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
        if (-not $output) { Stop-WwiWithError "devenv reported success but no .ispac was produced for $projectName." }
        Copy-Item -Path $output.FullName -Destination $ispacPath -Force
    }
    elseif ($ssisBuild -and -not $ForceZipFallback) {
        # SSISBuild writes into <output>\<configuration>\, so it is given a
        # directory and the produced file is located afterwards.
        $stagingOut = Join-Path $artifacts "$projectName.build"
        Invoke-WwiCommand -Description "SSISBuild $projectName" `
                          -FilePath $ssisBuild.Source `
                          -ArgumentList @('-project', $dtproj.FullName, '-configuration', $Configuration, '-output', $stagingOut) | Out-Null
        $output = Get-ChildItem -Path $stagingOut -Filter '*.ispac' -Recurse -File |
                  Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
        if (-not $output) { Stop-WwiWithError "SSISBuild reported success but no .ispac was produced for $projectName." }
        Copy-Item -Path $output.FullName -Destination $ispacPath -Force
        Remove-Item -Path $stagingOut -Recurse -Force -ErrorAction SilentlyContinue
    }
    else {
        Write-WwiLog "no SSIS build tool available for $projectName; assembling the .ispac by hand." 'WARN'
        Build-WwiIspacFromFolder -ProjectDirectory $projectDir -ProjectName $projectName -IspacPath $ispacPath
    }

    Write-WwiLog ("built {0} ({1} package(s)) -> {2}" -f $projectName, $packageCount, $ispacPath)
    $built += $ispacPath
}

if ($DryRun) {
    Write-WwiLog ("WHATIF {0} project(s) would be built into {1}" -f $projects.Count, $artifacts)
    return
}

Write-WwiLog ("build complete: {0} .ispac file(s) in {1}" -f $built.Count, $artifacts)
