<#
    Builds the WWI SSIS project into an .ispac deployment file.

    The estate's packages are generated by tools/ssisgen into ssis/**; this
    script assembles them into the project that ISDeploymentWizard consumes.
    Two paths are supported, because the estate has both:

      * devenv.com against ssis/WWI_Estate.dtproj - what the build server does
        when Visual Studio with the Integration Services projects extension is
        installed;
      * a hand-rolled .ispac (a zip of the manifest, the project parameters, the
        connection managers and every .dtsx) - what the platform team falls back
        to on hosts without Visual Studio. It has always been the awkward part
        of this build.

    This script has not been executed on a build host.

    Usage: .\deployment\ssis\Build-SsisProject.ps1 [-OutputPath artifacts] [-DryRun]
#>

[CmdletBinding()]
param(
    [string] $OutputPath = 'artifacts',
    [string] $Configuration = 'Development',
    [switch] $ForceZipFallback,
    [switch] $DryRun
)

. (Join-Path $PSScriptRoot '..' 'lib' 'Common.ps1')
$script:WwiLogPrefix = 'wwi-build-ssis'

function Get-DefaultedSsisProject {
    $value = [Environment]::GetEnvironmentVariable('SSIS_PROJECT')
    if ([string]::IsNullOrWhiteSpace($value)) { return 'WWI_Estate' }
    return $value
}

$repoRoot    = Get-WwiRepositoryRoot
$ssisRoot    = Join-Path $repoRoot 'ssis'
$projectName = Get-DefaultedSsisProject
$artifacts   = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $repoRoot $OutputPath }

if (-not (Test-Path $ssisRoot)) { Stop-WwiWithError "ssis/ is not present in $repoRoot." }

$packages = @(Get-ChildItem -Path $ssisRoot -Filter '*.dtsx' -Recurse -File)
if ($packages.Count -eq 0) { Stop-WwiWithError 'no .dtsx packages found under ssis/.' }
Write-WwiLog ("{0} package(s) found under ssis/" -f $packages.Count)

$ispacPath  = Join-Path $artifacts "$projectName.ispac"
$dtprojPath = Join-Path $ssisRoot "$projectName.dtproj"

if ($DryRun) {
    Write-WwiLog "WHATIF build $projectName ($Configuration) -> $ispacPath"
    Write-WwiLog ("WHATIF include {0} package(s), project parameters and connection managers" -f $packages.Count)
    return
}

if (-not (Test-Path $artifacts)) { New-Item -ItemType Directory -Path $artifacts -Force | Out-Null }

$devenv = Get-Command devenv.com -ErrorAction SilentlyContinue

if ($devenv -and -not $ForceZipFallback -and (Test-Path $dtprojPath)) {
    Invoke-WwiCommand -Description "devenv build $projectName" `
                      -FilePath $devenv.Source `
                      -ArgumentList @($dtprojPath, '/Build', $Configuration) | Out-Null

    $built = Get-ChildItem -Path $ssisRoot -Filter "$projectName.ispac" -Recurse -File |
             Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
    if (-not $built) { Stop-WwiWithError 'devenv reported success but no .ispac was produced.' }
    Copy-Item -Path $built.FullName -Destination $ispacPath -Force
}
else {
    Write-WwiLog 'devenv.com unavailable or bypassed; assembling the .ispac by hand.' 'WARN'

    $staging = Join-Path ([System.IO.Path]::GetTempPath()) ("wwi-ispac-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $staging -Force | Out-Null
    try {
        foreach ($package in $packages) { Copy-Item -Path $package.FullName -Destination $staging -Force }

        foreach ($extra in @('*.params', '*.conmgr')) {
            Get-ChildItem -Path $ssisRoot -Filter $extra -Recurse -File -ErrorAction SilentlyContinue |
                ForEach-Object { Copy-Item -Path $_.FullName -Destination $staging -Force }
        }

        # The manifest lists every part; ISDeploymentWizard rejects an .ispac
        # whose manifest and contents disagree, which is how the fallback used
        # to fail silently before the manifest was generated from the folder.
        $manifest = [xml] @"
<?xml version="1.0" encoding="utf-8"?>
<SSIS:Project SSIS:ProtectionLevel="DontSaveSensitive" xmlns:SSIS="www.microsoft.com/SqlServer/SSIS">
  <SSIS:Properties>
    <SSIS:Property SSIS:Name="Name">$projectName</SSIS:Property>
    <SSIS:Property SSIS:Name="VersionMajor">1</SSIS:Property>
    <SSIS:Property SSIS:Name="VersionMinor">0</SSIS:Property>
  </SSIS:Properties>
  <SSIS:Packages />
  <SSIS:ConnectionManagers />
</SSIS:Project>
"@
        $packagesNode = $manifest.SelectSingleNode('//*[local-name()="Packages"]')
        foreach ($package in $packages) {
            $node = $manifest.CreateElement('SSIS', 'Package', 'www.microsoft.com/SqlServer/SSIS')
            $node.SetAttribute('Name', 'www.microsoft.com/SqlServer/SSIS', $package.Name)
            $node.SetAttribute('EntryPoint', 'www.microsoft.com/SqlServer/SSIS',
                               $(if ($package.Name -like 'Master_*') { '1' } else { '0' }))
            [void] $packagesNode.AppendChild($node)
        }
        $manifest.Save((Join-Path $staging '@Project.manifest'))

        if (Test-Path $ispacPath) { Remove-Item $ispacPath -Force }
        Compress-Archive -Path (Join-Path $staging '*') -DestinationPath "$ispacPath.zip" -Force
        Move-Item -Path "$ispacPath.zip" -Destination $ispacPath -Force
    }
    finally {
        Remove-Item -Path $staging -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Write-WwiLog "build complete: $ispacPath"
