<#
    Builds the WWI SSIS projects into .ispac deployment files.

    The estate's packages are generated by tools/ssisgen into ssis/<NN_area>/,
    one Visual Studio project per area, so this script builds every .dtproj it
    finds under ssis/ and writes one .ispac per project. -Project filters that
    list by project name when a single area is being redeployed.

    Three build paths are supported, because the estate has all three kinds of
    host:

      * devenv.com against each .dtproj - what the build server does when Visual
        Studio with the Integration Services projects extension is installed;
      * SSISBuild.exe (the standalone SSIS DevOps build tool) - what the newer
        agents have instead of Visual Studio;
      * a hand-rolled .ispac (a zip of the manifest, the project parameters, the
        connection managers and the project's .dtsx files) - the fallback for
        hosts with neither.

    Whichever path builds it, the .ispac is opened afterwards and checked before
    it is accepted: an .ispac whose manifest omits the project parameters and
    the CM.<connection>.Password connection-manager parameters deploys perfectly
    and then connects with an empty password, because the catalog has nothing to
    bind the credential to. That is a build defect, so the build fails on it.

    Usage: .\deployment\ssis\Build-SsisProject.ps1 [-OutputPath artifacts] [-DryRun]
#>

[CmdletBinding()]
param(
    [string] $OutputPath = 'artifacts',
    [string] $Configuration = 'Development',
    [string[]] $Project,
    [switch] $ForceZipFallback,
    [switch] $DryRun
)

. (Join-Path (Join-Path (Join-Path $PSScriptRoot '..') 'lib') 'Common.ps1')
$script:WwiLogPrefix = 'wwi-build-ssis'

$repoRoot = Get-WwiRepositoryRoot
$ssisRoot = Join-Path $repoRoot 'ssis'
$artifacts = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $repoRoot $OutputPath }

if (-not (Test-Path $ssisRoot)) { Stop-WwiWithError "ssis/ is not present in $repoRoot." }

# obj\ holds build intermediates, including a copy of the .dtproj; building it
# would produce a second .ispac for the same project.
$projects = @(
    Get-ChildItem -Path $ssisRoot -Filter '*.dtproj' -Recurse -File |
        Where-Object { $_.FullName -notmatch '\\obj\\' } |
        Sort-Object FullName
)
if ($Project) {
    $projects = @($projects | Where-Object { $Project -contains $_.BaseName })
}
if ($projects.Count -eq 0) { Stop-WwiWithError 'no .dtproj projects found under ssis/.' }

if (-not $DryRun -and -not (Test-Path $artifacts)) {
    New-Item -ItemType Directory -Path $artifacts -Force | Out-Null
}

$devenv = Get-Command devenv.com -ErrorAction SilentlyContinue
$ssisBuild = Get-Command SSISBuild.exe -ErrorAction SilentlyContinue

function Build-WwiIspacFromFolder {
    <#
        Assembles an .ispac from a project folder when no SSIS build tool is
        present.

        The manifest is not synthesised any more. The .dtproj already carries the
        real one under DeploymentModelSpecificContent/Manifest - the same
        document a build tool writes out as @Project.manifest - including
        <SSIS:DeploymentInfo>, the project parameters and the
        CM.<connection>.Password connection-manager parameters. Rebuilding it
        from a directory listing dropped all of that, which is what made the
        fallback's output undeployable in practice: the project appeared in the
        catalog with no parameters at all, so every binding was a silent no-op.
    #>
    param(
        [Parameter(Mandatory)][string] $ProjectDirectory,
        [Parameter(Mandatory)][string] $ProjectName,
        [Parameter(Mandatory)][string] $DtprojPath,
        [Parameter(Mandatory)][string] $IspacPath
    )

    $packages = @(Get-ChildItem -Path $ProjectDirectory -Filter '*.dtsx' -File)
    if ($packages.Count -eq 0) {
        Stop-WwiWithError "no .dtsx packages found in $ProjectDirectory."
    }

    $dtproj = [xml] (Get-Content -Path $DtprojPath -Raw)
    $manifestNode = $dtproj.SelectSingleNode(
        '/*[local-name()="Project"]/*[local-name()="DeploymentModelSpecificContent"]/*[local-name()="Manifest"]/*[local-name()="Project"]')
    if (-not $manifestNode) {
        Stop-WwiWithError ("$DtprojPath has no DeploymentModelSpecificContent/Manifest project element, so no " +
                           'deployable manifest can be produced. Regenerate the project with tools/ssisgen.')
    }

    $staging = Join-Path ([System.IO.Path]::GetTempPath()) ("wwi-ispac-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $staging -Force | Out-Null
    try {
        foreach ($package in $packages) { Copy-Item -Path $package.FullName -Destination $staging -Force }
        foreach ($extra in @('*.params', '*.conmgr')) {
            Get-ChildItem -Path $ProjectDirectory -Filter $extra -File -ErrorAction SilentlyContinue |
                ForEach-Object { Copy-Item -Path $_.FullName -Destination $staging -Force }
        }

        $manifest = New-Object System.Xml.XmlDocument
        [void] $manifest.AppendChild($manifest.CreateXmlDeclaration('1.0', 'utf-8', $null))
        [void] $manifest.AppendChild($manifest.ImportNode($manifestNode, $true))
        $manifest.Save((Join-Path $staging '@Project.manifest'))

        if (Test-Path $IspacPath) { Remove-Item $IspacPath -Force }
        Compress-Archive -Path (Join-Path $staging '*') -DestinationPath "$IspacPath.zip" -Force
        Move-Item -Path "$IspacPath.zip" -Destination $IspacPath -Force
    }
    finally {
        Remove-Item -Path $staging -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Test-WwiIspac {
    <#
        Opens the produced .ispac and checks it is deployable, whichever path
        built it.

        An .ispac is a zip. It must contain @Project.manifest, Project.params and
        every .dtsx and .conmgr the manifest names, and the manifest must declare
        a Sensitive CM.<connection>.Password parameter for each OLE DB connection
        manager - that parameter is the only thing the catalog environment can
        bind a credential to now that no expression carries one.
    #>
    param(
        [Parameter(Mandatory)][string] $IspacPath,
        [Parameter(Mandatory)][int]    $ExpectedPackages
    )

    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [System.IO.Compression.ZipFile]::OpenRead($IspacPath)
    try {
        $entries = @($archive.Entries | ForEach-Object { $_.FullName })
        $problems = @()

        if ($entries -notcontains '@Project.manifest') { $problems += 'no @Project.manifest' }
        if ($entries -notcontains 'Project.params')    { $problems += 'no Project.params' }

        $packageEntries = @($entries | Where-Object { $_ -like '*.dtsx' })
        if ($packageEntries.Count -ne $ExpectedPackages) {
            $problems += "holds $($packageEntries.Count) package(s), the project has $ExpectedPackages"
        }

        $manifestEntry = $archive.GetEntry('@Project.manifest')
        if ($manifestEntry) {
            $reader = New-Object System.IO.StreamReader $manifestEntry.Open()
            try { $manifestXml = [xml] $reader.ReadToEnd() } finally { $reader.Dispose() }

            $declared = @($manifestXml.SelectNodes('//*[local-name()="Parameter"]') |
                ForEach-Object { $_.GetAttribute('Name', 'www.microsoft.com/SqlServer/SSIS') })
            if ($declared.Count -eq 0) {
                $problems += 'the manifest declares no parameters at all'
            }

            foreach ($entry in @($entries | Where-Object { $_ -like '*.conmgr' })) {
                $conmgrEntry = $archive.GetEntry($entry)
                $reader = New-Object System.IO.StreamReader $conmgrEntry.Open()
                try { $conmgrXml = [xml] $reader.ReadToEnd() } finally { $reader.Dispose() }
                $creationName = $conmgrXml.DocumentElement.GetAttribute(
                    'CreationName', 'www.microsoft.com/SqlServer/Dts')
                if ($creationName -ne 'OLEDB') { continue }
                $parameter = 'CM.' + [System.IO.Path]::GetFileNameWithoutExtension($entry) + '.Password'
                if ($declared -notcontains $parameter) {
                    $problems += "the manifest does not declare $parameter"
                }
            }
        }

        if ($problems.Count -gt 0) {
            Stop-WwiWithError ("$IspacPath is not deployable: {0}." -f ($problems -join '; '))
        }
    }
    finally {
        $archive.Dispose()
    }
}

$built = @()

foreach ($dtproj in $projects) {
    $projectName = $dtproj.BaseName
    $projectDir = $dtproj.DirectoryName
    $ispacPath = Join-Path $artifacts "$projectName.ispac"
    $packageCount = @(Get-ChildItem -Path $projectDir -Filter '*.dtsx' -File).Count

    if ($DryRun) {
        Write-WwiLog "WHATIF build $projectName ($Configuration) -> $ispacPath"
        Write-WwiLog ("WHATIF include {0} package(s), project parameters and connection managers" -f $packageCount)
        continue
    }

    if ($devenv -and -not $ForceZipFallback) {
        Invoke-WwiCommand -Description "devenv build $projectName" `
                          -FilePath $devenv.Source `
                          -ArgumentList @($dtproj.FullName, '/Build', $Configuration) | Out-Null
        $output = Get-ChildItem -Path $projectDir -Filter "$projectName.ispac" -Recurse -File |
                  Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
        if (-not $output) { Stop-WwiWithError "devenv reported success but no .ispac was produced for $projectName." }
        Copy-Item -Path $output.FullName -Destination $ispacPath -Force
    }
    elseif ($ssisBuild -and -not $ForceZipFallback) {
        # SSISBuild takes -argument:value; a space-separated pair is read as an
        # unknown option and the tool exits non-zero after printing its usage.
        # It writes into <output>\<configuration>\, so it is given a directory
        # and the produced file is located afterwards.
        $stagingOut = Join-Path $artifacts "$projectName.build"
        Invoke-WwiCommand -Description "SSISBuild $projectName" `
                          -FilePath $ssisBuild.Source `
                          -ArgumentList @("-project:$($dtproj.FullName)",
                                          "-configuration:$Configuration",
                                          "-output:$stagingOut") | Out-Null
        $output = Get-ChildItem -Path $stagingOut -Filter '*.ispac' -Recurse -File |
                  Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
        if (-not $output) { Stop-WwiWithError "SSISBuild reported success but no .ispac was produced for $projectName." }
        Copy-Item -Path $output.FullName -Destination $ispacPath -Force
        Remove-Item -Path $stagingOut -Recurse -Force -ErrorAction SilentlyContinue
    }
    else {
        Write-WwiLog "no SSIS build tool available for $projectName; assembling the .ispac by hand." 'WARN'
        Build-WwiIspacFromFolder -ProjectDirectory $projectDir -ProjectName $projectName `
                                 -DtprojPath $dtproj.FullName -IspacPath $ispacPath
    }

    Test-WwiIspac -IspacPath $ispacPath -ExpectedPackages $packageCount
    Write-WwiLog ("built {0} ({1} package(s)) -> {2}" -f $projectName, $packageCount, $ispacPath)
    $built += $ispacPath
}

if ($DryRun) {
    Write-WwiLog ("WHATIF {0} project(s) would be built into {1}" -f $projects.Count, $artifacts)
    return
}

Write-WwiLog ("build complete: {0} .ispac file(s) in {1}" -f $built.Count, $artifacts)
