/* =====================================================================
 * Object       : Object and system grants for the WWIGERP schemas
 * Schema       : n/a (SYS/DBA level, plus owner-issued object grants)
 * Deploy order : 05  - after all tables exist (oracle/tables) and after
 *                oracle/ddl/04_create_roles.sql
 * Depends on   : oracle/ddl/04_create_roles.sql, oracle/tables/*
 * Called by    : DBA deployment runbook (oracle/ddl/README.md)
 *
 * Grants are table-by-table rather than schema-wide because the 2011 audit
 * finding required it. New tables are frequently added without a matching
 * grant, which is why the extract packages fail with ORA-00942 the first
 * night after a release; the runbook step "re-run 05_grant_privileges.sql"
 * exists for exactly that reason.
 * ===================================================================== */

/* --- master data: full read for the extract role ------------------- */
GRANT SELECT ON WWI_MDM.CUST_MASTER            TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.CUST_ADDRESS           TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.CUST_CONTACT           TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.CUST_CLASSIFICATION    TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.CUST_CREDIT_PROFILE    TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.CUST_HIERARCHY         TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.CUST_SEGMENT_ASSIGN    TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.SUPP_MASTER            TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.SUPP_ADDRESS           TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.SUPP_CONTACT           TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.SUPP_CERTIFICATION     TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.PRODUCT_MASTER         TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.PRODUCT_CATEGORY       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.PRODUCT_HIERARCHY      TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.PRODUCT_UOM_CONV       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.PRODUCT_SUBSTITUTE     TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.PARTY_XREF             TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_MDM.MDM_MERGE_HISTORY      TO WWI_ETL_EXTRACT_ROLE
/

/* Bank accounts are NOT granted to the extract role. Downstream reads the
   masked view WWI_MDM.V_SUPPLIER_BANK_MASKED instead. */
GRANT SELECT ON WWI_MDM.SUPP_BANK_ACCOUNT      TO WWI_FIN_SENSITIVE_ROLE
/

/* --- procurement --------------------------------------------------- */
GRANT SELECT ON WWI_PROC.REQUISITION_HDR       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.REQUISITION_LINE      TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.SOURCING_EVENT        TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.SUPPLIER_QUOTE        TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.SUPPLIER_QUOTE_LINE   TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_HDR    TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_LINE   TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.PO_CHANGE_ORDER       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.PO_RECEIPT_HDR        TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.PO_RECEIPT_LINE       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.GOODS_RETURN_HDR      TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.GOODS_RETURN_LINE     TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.VENDOR_CONTRACT       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.VENDOR_CONTRACT_LINE  TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_PROC.SUPPLIER_SCORECARD    TO WWI_ETL_EXTRACT_ROLE
/

/* --- finance -------------------------------------------------------- */
GRANT SELECT ON WWI_FIN.AP_INVOICE_HDR         TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.AP_INVOICE_LINE        TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.AP_INVOICE_HOLD        TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.AP_PAYMENT             TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.AP_PAYMENT_APPLY       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.AP_AGING_SNAPSHOT      TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.GL_ACCOUNT             TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.GL_JOURNAL_HDR         TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.GL_JOURNAL_LINE        TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.GL_PERIOD_STATUS       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.COST_CENTER            TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.COST_ALLOCATION_RULE   TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.PAYMENT_TERMS          TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.TAX_RATE               TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.TAX_JURISDICTION       TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_FIN.WITHHOLDING_RULE       TO WWI_FIN_SENSITIVE_ROLE
/

/* --- reference: readable by everyone in the ERP --------------------- */
GRANT SELECT ON WWI_REF.CURRENCY_CODE          TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.FX_RATE_DAILY          TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.COUNTRY_REF            TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.REGION_REF             TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.CITY_REF               TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.POSTAL_REF             TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.UOM_REF                TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.LANGUAGE_REF           TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.INCOTERM_REF           TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.PAYMENT_METHOD_REF     TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.STATUS_CODE_REF        TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.REASON_CODE_REF        TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.CALENDAR_FISCAL        TO WWI_ETL_EXTRACT_ROLE, WWI_ERP_APP_ROLE
/
GRANT SELECT ON WWI_REF.SOURCE_SYSTEM_REF      TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_REF.CODE_TRANSLATION       TO WWI_ETL_EXTRACT_ROLE
/

/* --- audit: the extract account also writes its own bookmark row ---- */
GRANT SELECT ON WWI_AUDIT.CHANGE_LOG           TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT, INSERT, UPDATE ON WWI_AUDIT.EXTRACT_CONTROL TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT, INSERT ON WWI_AUDIT.INTERFACE_ERROR TO WWI_ETL_EXTRACT_ROLE
/
GRANT SELECT ON WWI_AUDIT.PURGE_LOG            TO WWI_ETL_EXTRACT_ROLE
/

/* Sequence needed because the extract account inserts interface errors. */
GRANT SELECT ON WWI_AUDIT.SEQ_INTERFACE_ERROR  TO WWI_ETL_EXTRACT_ROLE
/

/* --- cross-schema reads required to compile the extract views -------
 * These are granted to the owning schema directly, not through a role:
 * privileges acquired via a role are not visible while a view is being
 * compiled, so a role grant leaves the view INVALID with ORA-00942.
 * Every entry below backs a static dependency in oracle/views/*.sql and is
 * enforced by validation/checks/check_oracle_view_columns.py.
 * ------------------------------------------------------------------- */

/* WWI_FIN.V_AP_AGING_CURRENT, V_AP_INVOICE_EXTRACT, V_AP_PAYMENT_EXTRACT */
GRANT SELECT ON WWI_MDM.SUPP_MASTER            TO WWI_FIN
/
GRANT SELECT ON WWI_REF.PAYMENT_METHOD_REF     TO WWI_FIN
/

/* WWI_MDM.V_CUSTOMER_ADDRESS_CURRENT, V_CUSTOMER_EXTRACT, V_PRODUCT_EXTRACT */
GRANT SELECT ON WWI_REF.CITY_REF               TO WWI_MDM
/
GRANT SELECT ON WWI_REF.COUNTRY_REF            TO WWI_MDM
/
GRANT SELECT ON WWI_REF.POSTAL_REF             TO WWI_MDM
/
GRANT SELECT ON WWI_REF.UOM_REF                TO WWI_MDM
/

/* WWI_MDM.V_SUPPLIER_EXTRACT */
GRANT SELECT ON WWI_PROC.VENDOR_CONTRACT       TO WWI_MDM
/
GRANT SELECT ON WWI_FIN.WITHHOLDING_RULE       TO WWI_MDM
/

/* WWI_PROC.V_PURCHASE_ORDER_EXTRACT, V_PO_LINE_EXTRACT,
   V_SUPPLIER_SCORECARD_CURRENT, V_OPEN_PO_BALANCE */
GRANT SELECT ON WWI_MDM.SUPP_MASTER            TO WWI_PROC
/
GRANT SELECT ON WWI_MDM.PRODUCT_MASTER         TO WWI_PROC
/
GRANT SELECT ON WWI_FIN.AP_INVOICE_HDR         TO WWI_PROC
/
GRANT SELECT ON WWI_FIN.AP_INVOICE_LINE        TO WWI_PROC
/

/* WWI_REF.V_PAYMENT_TERMS_EXTRACT */
GRANT SELECT ON WWI_FIN.PAYMENT_TERMS          TO WWI_REF
/

/* --- cross-schema reads required to compile the scalar functions ----
 * Same rule as the view grants above: a stored function body resolves its
 * references with direct privileges only.
 * ------------------------------------------------------------------- */

/* WWI_FIN.FN_CONVERT_AMOUNT */
GRANT SELECT ON WWI_REF.CURRENCY_CODE          TO WWI_FIN
/
GRANT SELECT ON WWI_REF.FX_RATE_DAILY          TO WWI_FIN
/

/* WWI_MDM.FN_PRODUCT_ACTIVE_FLAG */
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_LINE   TO WWI_MDM
/

/* WWI_PROC.FN_RECEIPT_VARIANCE_PCT */
GRANT SELECT ON WWI_MDM.PRODUCT_UOM_CONV       TO WWI_PROC
/

/* --- cross-schema privileges required to compile the packages and
 * procedures ---------------------------------------------------------
 * Same rule again: a stored PL/SQL body resolves its references with direct
 * privileges only, and the extract/purge/audit bodies write across schema
 * boundaries as well as read.
 * ------------------------------------------------------------------- */

/* WWI_FIN and WWI_MDM write change/purge history through WWI_AUDIT */
GRANT SELECT, INSERT ON WWI_AUDIT.CHANGE_LOG   TO WWI_FIN
/
GRANT SELECT, INSERT ON WWI_AUDIT.CHANGE_LOG   TO WWI_MDM
/
GRANT SELECT, INSERT ON WWI_AUDIT.PURGE_LOG    TO WWI_MDM
/
GRANT SELECT ON WWI_AUDIT.EXTRACT_CONTROL      TO WWI_FIN
/
GRANT SELECT ON WWI_AUDIT.SEQ_CHANGE_LOG       TO WWI_FIN
/
GRANT SELECT ON WWI_AUDIT.SEQ_CHANGE_LOG       TO WWI_MDM
/
GRANT SELECT ON WWI_AUDIT.SEQ_PURGE_LOG        TO WWI_MDM
/

/* WWI_AUDIT extract preparation and quarterly purge */
GRANT SELECT, DELETE ON WWI_FIN.AP_AGING_SNAPSHOT TO WWI_AUDIT
/
GRANT SELECT ON WWI_FIN.AP_INVOICE_HDR         TO WWI_AUDIT
/
GRANT SELECT ON WWI_FIN.GL_PERIOD_STATUS       TO WWI_AUDIT
/
GRANT SELECT ON WWI_MDM.CUST_MASTER            TO WWI_AUDIT
/
GRANT SELECT ON WWI_MDM.CUST_ADDRESS           TO WWI_AUDIT
/
GRANT SELECT ON WWI_MDM.PRODUCT_MASTER         TO WWI_AUDIT
/
GRANT SELECT ON WWI_MDM.SUPP_MASTER            TO WWI_AUDIT
/
GRANT SELECT ON WWI_MDM.SUPP_BANK_ACCOUNT      TO WWI_AUDIT
/
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_LINE   TO WWI_AUDIT
/
GRANT SELECT ON WWI_REF.CODE_TRANSLATION       TO WWI_AUDIT
/

/* WWI_FIN AP matching, payment and supplier maintenance */
GRANT SELECT ON WWI_MDM.SUPP_BANK_ACCOUNT      TO WWI_FIN
/
GRANT SELECT ON WWI_MDM.SUPP_CONTACT           TO WWI_FIN
/
GRANT UPDATE ON WWI_MDM.SUPP_MASTER            TO WWI_FIN
/
GRANT SELECT ON WWI_PROC.PO_RECEIPT_HDR        TO WWI_FIN
/
GRANT SELECT, UPDATE ON WWI_PROC.PO_RECEIPT_LINE TO WWI_FIN
/
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_HDR    TO WWI_FIN
/
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_LINE   TO WWI_FIN
/
GRANT SELECT ON WWI_REF.COUNTRY_REF            TO WWI_FIN
/
GRANT SELECT ON WWI_REF.SOURCE_SYSTEM_REF      TO WWI_FIN
/

/* WWI_MDM and WWI_PROC read the source-system register and PO history */
GRANT SELECT ON WWI_PROC.PURCHASE_ORDER_HDR    TO WWI_MDM
/
GRANT SELECT ON WWI_REF.SOURCE_SYSTEM_REF      TO WWI_MDM
/
GRANT SELECT ON WWI_REF.SOURCE_SYSTEM_REF      TO WWI_PROC
/
