/* =====================================================================
 * Object       : PUBLIC and private SYNONYMs for the WWIGERP schemas
 * Schema       : n/a (SYS/DBA level for PUBLIC synonyms, WWI_EXTRACT for
 *                the private ones)
 * Deploy order : 07  - after 05_grant_privileges.sql
 * Depends on   : oracle/ddl/05_grant_privileges.sql, oracle/tables/*
 * Called by    : DBA deployment runbook (oracle/ddl/README.md)
 *
 * PUBLIC synonyms exist only for the reference schema, which the 2003
 * standard said "all applications may see unqualified". Everything else is a
 * private synonym in WWI_EXTRACT so the extract SQL in the SSIS packages can
 * be written unqualified - which is also why a schema rename has never been
 * attempted.
 * ===================================================================== */

/* --- public reference synonyms (1998 / 2003 standard) --------------- */
CREATE OR REPLACE PUBLIC SYNONYM CURRENCY_CODE      FOR WWI_REF.CURRENCY_CODE
/
CREATE OR REPLACE PUBLIC SYNONYM FX_RATE_DAILY      FOR WWI_REF.FX_RATE_DAILY
/
CREATE OR REPLACE PUBLIC SYNONYM COUNTRY_REF        FOR WWI_REF.COUNTRY_REF
/
CREATE OR REPLACE PUBLIC SYNONYM REGION_REF         FOR WWI_REF.REGION_REF
/
CREATE OR REPLACE PUBLIC SYNONYM CITY_REF           FOR WWI_REF.CITY_REF
/
CREATE OR REPLACE PUBLIC SYNONYM POSTAL_REF         FOR WWI_REF.POSTAL_REF
/
CREATE OR REPLACE PUBLIC SYNONYM UOM_REF            FOR WWI_REF.UOM_REF
/
CREATE OR REPLACE PUBLIC SYNONYM LANGUAGE_REF       FOR WWI_REF.LANGUAGE_REF
/
CREATE OR REPLACE PUBLIC SYNONYM INCOTERM_REF       FOR WWI_REF.INCOTERM_REF
/
CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_METHOD_REF FOR WWI_REF.PAYMENT_METHOD_REF
/
CREATE OR REPLACE PUBLIC SYNONYM STATUS_CODE_REF    FOR WWI_REF.STATUS_CODE_REF
/
CREATE OR REPLACE PUBLIC SYNONYM REASON_CODE_REF    FOR WWI_REF.REASON_CODE_REF
/
CREATE OR REPLACE PUBLIC SYNONYM CALENDAR_FISCAL    FOR WWI_REF.CALENDAR_FISCAL
/

/* --- extract-account private synonyms ------------------------------- */
CREATE OR REPLACE SYNONYM WWI_EXTRACT.CUST_MASTER         FOR WWI_MDM.CUST_MASTER
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.CUST_ADDRESS        FOR WWI_MDM.CUST_ADDRESS
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.CUST_CONTACT        FOR WWI_MDM.CUST_CONTACT
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.CUST_CREDIT_PROFILE FOR WWI_MDM.CUST_CREDIT_PROFILE
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.SUPP_MASTER         FOR WWI_MDM.SUPP_MASTER
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.SUPP_ADDRESS        FOR WWI_MDM.SUPP_ADDRESS
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.PRODUCT_MASTER      FOR WWI_MDM.PRODUCT_MASTER
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.PARTY_XREF          FOR WWI_MDM.PARTY_XREF
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.PURCHASE_ORDER_HDR  FOR WWI_PROC.PURCHASE_ORDER_HDR
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.PURCHASE_ORDER_LINE FOR WWI_PROC.PURCHASE_ORDER_LINE
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.PO_RECEIPT_HDR      FOR WWI_PROC.PO_RECEIPT_HDR
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.PO_RECEIPT_LINE     FOR WWI_PROC.PO_RECEIPT_LINE
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.VENDOR_CONTRACT     FOR WWI_PROC.VENDOR_CONTRACT
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.AP_INVOICE_HDR      FOR WWI_FIN.AP_INVOICE_HDR
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.AP_INVOICE_LINE     FOR WWI_FIN.AP_INVOICE_LINE
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.AP_PAYMENT          FOR WWI_FIN.AP_PAYMENT
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.GL_JOURNAL_HDR      FOR WWI_FIN.GL_JOURNAL_HDR
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.GL_JOURNAL_LINE     FOR WWI_FIN.GL_JOURNAL_LINE
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.COST_CENTER         FOR WWI_FIN.COST_CENTER
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.EXTRACT_CONTROL     FOR WWI_AUDIT.EXTRACT_CONTROL
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.CHANGE_LOG          FOR WWI_AUDIT.CHANGE_LOG
/
CREATE OR REPLACE SYNONYM WWI_EXTRACT.INTERFACE_ERROR     FOR WWI_AUDIT.INTERFACE_ERROR
/

/* Cross-schema synonyms inside the ERP. WWI_PROC and WWI_FIN were split from
   one schema in 2007 and the application code still references the old
   unqualified names. */
CREATE OR REPLACE SYNONYM WWI_PROC.PAYMENT_TERMS  FOR WWI_FIN.PAYMENT_TERMS
/
CREATE OR REPLACE SYNONYM WWI_PROC.SUPP_MASTER    FOR WWI_MDM.SUPP_MASTER
/
CREATE OR REPLACE SYNONYM WWI_FIN.SUPP_MASTER     FOR WWI_MDM.SUPP_MASTER
/
CREATE OR REPLACE SYNONYM WWI_FIN.PURCHASE_ORDER_HDR FOR WWI_PROC.PURCHASE_ORDER_HDR
/
