/* =====================================================================
 * Object       : TABLE WWI_MDM.SUPP_MASTER
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 27
 * Depends on   : oracle/ddl/03_create_schemas.sql, WWI_REF.COUNTRY_REF, WWI_FIN.PAYMENT_TERMS
 * Called by    : PKG_SUPPLIER_MASTER, V_SUPPLIER_EXTRACT, SSIS EXT_ORA_SupplierMaster
 *
 * Supplier master. Approval workflow state lives in APPROVAL_STATUS_CD, but a
 * supplier is only really usable when HOLD_ALL_FLG = 'N' and at least one
 * active SUPP_BANK_ACCOUNT row exists - a rule enforced in PL/SQL, not here.
 * The 1099 columns are NA-only; the EU rows carry VAT_REG_NBR and the APAC rows
 * carry a local business-registration number in the same TAX_ID_NBR column.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_SUPP_MASTER
    START WITH 900001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_MDM.SUPP_MASTER
(
    SUPP_ID                 NUMBER(12)      NOT NULL,
    SUPP_NBR                VARCHAR2(12)    NOT NULL,
    LEGACY_VENDOR_CD        VARCHAR2(8),
    SUPP_NAME               VARCHAR2(120)   NOT NULL,
    SUPP_NAME_NORM          VARCHAR2(120),
    SUPP_TYPE_CD            VARCHAR2(4)     NOT NULL,
    SUPP_STATUS_CD          VARCHAR2(2)     DEFAULT 'AC' NOT NULL,
    APPROVAL_STATUS_CD      VARCHAR2(4)     DEFAULT 'PEND' NOT NULL,
    APPROVED_BY_CD          VARCHAR2(8),
    APPROVED_DT             DATE,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    COUNTRY_CD              VARCHAR2(2)     NOT NULL,
    DEFAULT_CURR_CD         VARCHAR2(3)     NOT NULL,
    PAYMENT_TERMS_CD        VARCHAR2(8),
    PAYMENT_METHOD_CD       VARCHAR2(6)     DEFAULT 'EFT' NOT NULL,
    TAX_ID_NBR              VARCHAR2(24),
    VAT_REG_NBR             VARCHAR2(24),
    W9_ON_FILE_FLG          VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    FORM_1099_FLG           VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    FORM_1099_BOX_CD        VARCHAR2(4),
    WITHHOLDING_FLG         VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    DIVERSITY_CLASS_CD      VARCHAR2(6),
    SMALL_BUSINESS_FLG      VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    HOLD_ALL_FLG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    HOLD_REASON_CD          VARCHAR2(4),
    PREFERRED_SUPPLIER_FLG  VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    STRATEGIC_TIER_CD       VARCHAR2(2),
    LEAD_TIME_DAYS          NUMBER(4),
    MIN_ORDER_AMT           NUMBER(15,5),
    MIN_ORDER_CURR_CD       VARCHAR2(3),
    LAST_PO_DT              DATE,
    LAST_INVOICE_DT         DATE,
    AUDIT_NOTES_TXT         VARCHAR2(2000),
    DELETED_FLG             VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_SUPP_MASTER PRIMARY KEY (SUPP_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_SUPP_MASTER_NBR UNIQUE (SUPP_NBR) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_SUPP_MASTER_TYPE CHECK (SUPP_TYPE_CD IN ('GOOD', 'SERV', 'BOTH', 'INTC', 'ONET')),
    CONSTRAINT CK_SUPP_MASTER_STATUS CHECK (SUPP_STATUS_CD IN ('AC', 'IN', 'BL', 'PD')),
    CONSTRAINT CK_SUPP_MASTER_APPR CHECK (APPROVAL_STATUS_CD IN ('PEND', 'APPR', 'REJT', 'EXPD')),
    CONSTRAINT CK_SUPP_MASTER_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_SUPP_MASTER_FLAGS CHECK (
        W9_ON_FILE_FLG IN ('Y', 'N') AND FORM_1099_FLG IN ('Y', 'N')
        AND WITHHOLDING_FLG IN ('Y', 'N') AND SMALL_BUSINESS_FLG IN ('Y', 'N')
        AND HOLD_ALL_FLG IN ('Y', 'N') AND PREFERRED_SUPPLIER_FLG IN ('Y', 'N')
        AND DELETED_FLG IN ('Y', 'N')),
    CONSTRAINT CK_SUPP_MASTER_1099 CHECK (FORM_1099_FLG = 'N' OR FORM_1099_BOX_CD IS NOT NULL),
    CONSTRAINT CK_SUPP_MASTER_HOLD CHECK (HOLD_ALL_FLG = 'N' OR HOLD_REASON_CD IS NOT NULL)
)
TABLESPACE WWI_DATA
PCTFREE 15
/

CREATE INDEX WWI_MDM.IX_SUPP_MASTER_NAME_UPPER
    ON WWI_MDM.SUPP_MASTER (UPPER(SUPP_NAME)) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_MDM.IX_SUPP_MASTER_STATUS
    ON WWI_MDM.SUPP_MASTER (SUPP_STATUS_CD, APPROVAL_STATUS_CD, REGION_CD) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_MDM.IX_SUPP_MASTER_UPDATED
    ON WWI_MDM.SUPP_MASTER (UPDATED_DT) TABLESPACE WWI_IDX
/

COMMENT ON COLUMN WWI_MDM.SUPP_MASTER.TAX_ID_NBR IS
    'NA = EIN, EU = national tax id, APAC = business registration number.'
/
COMMENT ON COLUMN WWI_MDM.SUPP_MASTER.STRATEGIC_TIER_CD IS
    'T1/T2/T3 sourcing tier. Null for the majority of one-time suppliers.'
/
