/* =====================================================================
 * Object       : TABLE WWI_MDM.CUST_SEGMENT_ASSIGN
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 26
 * Depends on   : WWI_MDM.CUST_MASTER
 * Called by    : PKG_CUSTOMER_MASTER, C360 segmentation packages
 *
 * Marketing/analytical segment assignment. Segment code sets differ by region:
 * NA uses the 2016 five-tier model (T1..T5), EU uses the older PLATINUM/GOLD/
 * SILVER/BRONZE labels the 2011 loyalty scheme introduced, APAC uses a
 * numeric band. The column is a single VARCHAR2 holding all three vocabularies.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_CUST_SEGMENT_ASSIGN
    START WITH 600001 INCREMENT BY 1 CACHE 50 NOCYCLE
/

CREATE TABLE WWI_MDM.CUST_SEGMENT_ASSIGN
(
    SEGMENT_ASSIGN_ID       NUMBER(12)      NOT NULL,
    CUST_ID                 NUMBER(12)      NOT NULL,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    SEGMENT_MODEL_CD        VARCHAR2(10)    NOT NULL,
    SEGMENT_CD              VARCHAR2(12)    NOT NULL,
    SEGMENT_SCORE           NUMBER(9,4),
    RANK_IN_MODEL_NBR       NUMBER(8),
    ASSIGN_RUN_ID           NUMBER(12),
    ASSIGN_METHOD_CD        VARCHAR2(4)     DEFAULT 'BTCH' NOT NULL,
    OVERRIDE_FLG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    OVERRIDE_REASON_TXT     VARCHAR2(400),
    EFFECTIVE_DT            DATE            DEFAULT SYSDATE NOT NULL,
    EXPIRY_DT               DATE,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_CUST_SEGMENT_ASSIGN PRIMARY KEY (SEGMENT_ASSIGN_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_CUST_SEG_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_CUST_SEG_MODEL CHECK (
        SEGMENT_MODEL_CD IN ('NA_TIER5', 'EU_LOYALTY', 'AP_BAND', 'GLOBAL_ABC')),
    CONSTRAINT CK_CUST_SEG_METHOD CHECK (ASSIGN_METHOD_CD IN ('BTCH', 'MAN', 'MIGR')),
    CONSTRAINT CK_CUST_SEG_OVERRIDE CHECK (
        OVERRIDE_FLG IN ('Y', 'N') AND (OVERRIDE_FLG = 'N' OR OVERRIDE_REASON_TXT IS NOT NULL))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_MDM.CUST_SEGMENT_ASSIGN ADD CONSTRAINT FK_CUST_SEG_CUST
    FOREIGN KEY (CUST_ID) REFERENCES WWI_MDM.CUST_MASTER (CUST_ID)
/

CREATE INDEX WWI_MDM.IX_CUST_SEG_MODEL
    ON WWI_MDM.CUST_SEGMENT_ASSIGN (SEGMENT_MODEL_CD, SEGMENT_CD, EFFECTIVE_DT) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_MDM.IX_CUST_SEG_CUST
    ON WWI_MDM.CUST_SEGMENT_ASSIGN (CUST_ID, EFFECTIVE_DT DESC) TABLESPACE WWI_IDX
/
