/* =====================================================================
 * Object       : TABLE WWI_PROC.GOODS_RETURN_LINE
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 51
 * Depends on   : WWI_PROC.GOODS_RETURN_HDR, WWI_PROC.PO_RECEIPT_LINE
 * Called by    : PKG_RECEIPTS, inventory adjustment interface
 *
 * Return lines. DISPOSITION_CD records what physically happened to the goods
 * (returned, scrapped on site, held pending supplier instruction); scrapped
 * lines still expect a credit, which is why AP and inventory disagree on the
 * value of the return until the credit lands.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_GOODS_RETURN_LINE
    START WITH 300001 INCREMENT BY 1 CACHE 50 NOCYCLE
/

CREATE TABLE WWI_PROC.GOODS_RETURN_LINE
(
    RETURN_LINE_ID          NUMBER(12)      NOT NULL,
    RETURN_ID               NUMBER(12)      NOT NULL,
    LINE_NBR                NUMBER(5)       NOT NULL,
    RECEIPT_LINE_ID         NUMBER(12),
    PO_LINE_ID              NUMBER(12),
    PRODUCT_ID              NUMBER(12),
    RETURN_QTY              NUMBER(14,4)    NOT NULL,
    UOM_CD                  VARCHAR2(4)     NOT NULL,
    UNIT_COST               NUMBER(15,5),
    LINE_CREDIT_AMT         NUMBER(15,5),
    LINE_CURR_CD            VARCHAR2(3),
    LOT_NBR                 VARCHAR2(30),
    DISPOSITION_CD          VARCHAR2(4)     DEFAULT 'RTV' NOT NULL,
    DEFECT_CODE_CD          VARCHAR2(6),
    DEFECT_NOTES_TXT        VARCHAR2(1000),
    INVENTORY_ADJUSTED_FLG  VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CREDIT_RECEIVED_FLG     VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CREDIT_RECEIVED_DT      DATE,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_GOODS_RETURN_LINE PRIMARY KEY (RETURN_LINE_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_GOODS_RETURN_LINE UNIQUE (RETURN_ID, LINE_NBR) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_RETURN_LINE_QTY CHECK (RETURN_QTY > 0),
    CONSTRAINT CK_RETURN_LINE_DISP CHECK (DISPOSITION_CD IN ('RTV', 'SCRP', 'HOLD', 'REWK')),
    CONSTRAINT CK_RETURN_LINE_FLAGS CHECK (
        INVENTORY_ADJUSTED_FLG IN ('Y', 'N') AND CREDIT_RECEIVED_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_PROC.GOODS_RETURN_LINE ADD CONSTRAINT FK_RETURN_LINE_HDR
    FOREIGN KEY (RETURN_ID) REFERENCES WWI_PROC.GOODS_RETURN_HDR (RETURN_ID)
/

ALTER TABLE WWI_PROC.GOODS_RETURN_LINE ADD CONSTRAINT FK_RETURN_LINE_PO_LINE
    FOREIGN KEY (PO_LINE_ID) REFERENCES WWI_PROC.PURCHASE_ORDER_LINE (PO_LINE_ID)
/

CREATE INDEX WWI_PROC.IX_RETURN_LINE_PRODUCT
    ON WWI_PROC.GOODS_RETURN_LINE (PRODUCT_ID, DISPOSITION_CD) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_PROC.IX_RETURN_LINE_RECEIPT
    ON WWI_PROC.GOODS_RETURN_LINE (RECEIPT_LINE_ID) TABLESPACE WWI_IDX
/
