/* =====================================================================
 * Object       : TABLE WWI_FIN.TAX_JURISDICTION
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 64
 * Depends on   : WWI_REF.COUNTRY_REF
 * Called by    : PKG_TAX_CALC, PKG_AP_INVOICE
 *
 * Tax jurisdictions. A single table carries three genuinely different regimes:
 * NA state/county/city sales-and-use jurisdictions that stack, EU member-state
 * VAT regimes that do not, and APAC national GST/consumption-tax regimes with a
 * single rate per country. The stacking rule is implied by
 * JURISDICTION_LEVEL_CD and applied only in the NA branch of PKG_TAX_CALC.
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_TAX_JURISDICTION
    START WITH 3001 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE TABLE WWI_FIN.TAX_JURISDICTION
(
    TAX_JURISDICTION_ID     NUMBER(12)      NOT NULL,
    JURISDICTION_CD         VARCHAR2(12)    NOT NULL,
    JURISDICTION_NAME       VARCHAR2(120)   NOT NULL,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    COUNTRY_CD              VARCHAR2(2)     NOT NULL,
    STATE_PROV_CD           VARCHAR2(6),
    COUNTY_TXT              VARCHAR2(60),
    CITY_TXT                VARCHAR2(60),
    POSTAL_FROM_CD          VARCHAR2(12),
    POSTAL_TO_CD            VARCHAR2(12),
    JURISDICTION_LEVEL_CD   VARCHAR2(6)     NOT NULL,
    TAX_REGIME_CD           VARCHAR2(6)     NOT NULL,
    STACKS_WITH_PARENT_FLG  VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    PARENT_JURISDICTION_CD  VARCHAR2(12),
    REGISTRATION_REQ_FLG    VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    OUR_REGISTRATION_NBR    VARCHAR2(24),
    FILING_FREQUENCY_CD     VARCHAR2(4),
    FILING_DUE_DAY_NBR      NUMBER(2),
    AUTHORITY_NAME          VARCHAR2(120),
    EFFECTIVE_FROM_DT       DATE            NOT NULL,
    EFFECTIVE_TO_DT         DATE,
    ACTIVE_FLG              VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_TAX_JURISDICTION PRIMARY KEY (TAX_JURISDICTION_ID) USING INDEX TABLESPACE WWI_FIN_IDX,
    CONSTRAINT UK_TAX_JURISDICTION_CD UNIQUE (JURISDICTION_CD) USING INDEX TABLESPACE WWI_FIN_IDX,
    CONSTRAINT CK_TAX_JUR_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_TAX_JUR_LEVEL CHECK (
        JURISDICTION_LEVEL_CD IN ('NATL', 'STATE', 'COUNTY', 'CITY', 'SPEC')),
    CONSTRAINT CK_TAX_JUR_REGIME CHECK (
        TAX_REGIME_CD IN ('SALES', 'USE', 'VAT', 'GST', 'CONS', 'WHT')),
    CONSTRAINT CK_TAX_JUR_REGIME_REGION CHECK (
        (REGION_CD = 'NA'   AND TAX_REGIME_CD IN ('SALES', 'USE', 'GST', 'WHT'))
     OR (REGION_CD = 'EU'   AND TAX_REGIME_CD IN ('VAT', 'WHT'))
     OR (REGION_CD = 'APAC' AND TAX_REGIME_CD IN ('GST', 'CONS', 'VAT', 'WHT'))),
    CONSTRAINT CK_TAX_JUR_FLAGS CHECK (
        ACTIVE_FLG IN ('Y', 'N') AND STACKS_WITH_PARENT_FLG IN ('Y', 'N')
        AND REGISTRATION_REQ_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_FIN_DATA
/

CREATE INDEX WWI_FIN.IX_TAX_JUR_GEO
    ON WWI_FIN.TAX_JURISDICTION (COUNTRY_CD, STATE_PROV_CD, JURISDICTION_LEVEL_CD)
    TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_TAX_JUR_POSTAL
    ON WWI_FIN.TAX_JURISDICTION (POSTAL_FROM_CD, POSTAL_TO_CD) TABLESPACE WWI_FIN_IDX
/
