/* =====================================================================
 * Object       : TABLE WWI_FIN.GL_JOURNAL_HDR
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 68
 * Depends on   : WWI_FIN.GL_PERIOD_STATUS, WWI_FIN.GL_ACCOUNT
 * Called by    : PKG_GL_POST, V_GL_JOURNAL_EXTRACT, SSIS EXT_ORA_GLJournal
 *
 * Journal header, range partitioned on ACCOUNTING_DT. Journals arrive from AP,
 * the allocation batch, three feeder interfaces and manual entry, and the
 * source is recorded only in JOURNAL_SOURCE_CD. Reversals point at the
 * original through REVERSAL_OF_JOURNAL_ID with no constraint, so a reversal of
 * a purged journal keeps a dangling id.
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_GL_JOURNAL_HDR
    START WITH 5000001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_FIN.GL_JOURNAL_HDR
(
    JOURNAL_ID              NUMBER(12)      NOT NULL,
    JOURNAL_NBR             VARCHAR2(20)    NOT NULL,
    LEDGER_CD               VARCHAR2(8)     NOT NULL,
    PERIOD_CD               VARCHAR2(7)     NOT NULL,
    ACCOUNTING_DT           DATE            NOT NULL,
    JOURNAL_SOURCE_CD       VARCHAR2(8)     NOT NULL,
    JOURNAL_CATEGORY_CD     VARCHAR2(8)     NOT NULL,
    JOURNAL_DESC            VARCHAR2(240),
    REGION_CD               VARCHAR2(4)     NOT NULL,
    LEGAL_ENTITY_CD         VARCHAR2(6)     NOT NULL,
    JOURNAL_CURR_CD         VARCHAR2(3)     NOT NULL,
    FX_RATE                 NUMBER(18,8),
    FX_RATE_TYPE_CD         VARCHAR2(6),
    FX_RATE_DT              DATE,
    TOTAL_DEBIT_AMT         NUMBER(15,5)    DEFAULT 0 NOT NULL,
    TOTAL_CREDIT_AMT        NUMBER(15,5)    DEFAULT 0 NOT NULL,
    LINE_CNT                NUMBER(6)       DEFAULT 0 NOT NULL,
    POSTING_STATUS_CD       VARCHAR2(4)     DEFAULT 'UNPS' NOT NULL,
    POSTED_DT               DATE,
    POSTED_BY_CD            VARCHAR2(8),
    APPROVED_BY_CD          VARCHAR2(8),
    APPROVED_DT             DATE,
    REVERSAL_FLG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    REVERSAL_OF_JOURNAL_ID  NUMBER(12),
    AUTO_REVERSE_DT         DATE,
    ACCRUAL_FLG             VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    BATCH_NBR               VARCHAR2(20),
    ATTACHMENT_REF_TXT      VARCHAR2(400),
    PREPARER_NOTES_TXT      VARCHAR2(2000),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT CK_GL_JHDR_STATUS CHECK (POSTING_STATUS_CD IN ('UNPS', 'PEND', 'POST', 'ERR', 'REVS')),
    CONSTRAINT CK_GL_JHDR_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_GL_JHDR_SOURCE CHECK (
        JOURNAL_SOURCE_CD IN ('AP', 'PO', 'ALLOC', 'MANUAL', 'FEEDER1', 'FEEDER2', 'FEEDER3', 'FX')),
    CONSTRAINT CK_GL_JHDR_FLAGS CHECK (REVERSAL_FLG IN ('Y', 'N') AND ACCRUAL_FLG IN ('Y', 'N')),
    CONSTRAINT CK_GL_JHDR_BALANCED CHECK (
        POSTING_STATUS_CD <> 'POST' OR TOTAL_DEBIT_AMT = TOTAL_CREDIT_AMT)
)
PARTITION BY RANGE (ACCOUNTING_DT)
(
    PARTITION GL_JHDR_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JHDR_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JHDR_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JHDR_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JHDR_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JHDR_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_FIN_DATA,
    PARTITION GL_JHDR_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_FIN_DATA
)
/

ALTER TABLE WWI_FIN.GL_JOURNAL_HDR ADD CONSTRAINT PK_GL_JOURNAL_HDR
    PRIMARY KEY (JOURNAL_ID) USING INDEX TABLESPACE WWI_FIN_IDX
/

ALTER TABLE WWI_FIN.GL_JOURNAL_HDR ADD CONSTRAINT UK_GL_JOURNAL_NBR
    UNIQUE (LEDGER_CD, JOURNAL_NBR) USING INDEX TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_GL_JHDR_PERIOD
    ON WWI_FIN.GL_JOURNAL_HDR (PERIOD_CD, POSTING_STATUS_CD) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_GL_JHDR_SOURCE
    ON WWI_FIN.GL_JOURNAL_HDR (JOURNAL_SOURCE_CD, ACCOUNTING_DT) LOCAL TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_GL_JHDR_UPDATED
    ON WWI_FIN.GL_JOURNAL_HDR (UPDATED_DT) TABLESPACE WWI_FIN_IDX
/
