/* =====================================================================
 * Object       : TABLE WWI_MDM.PRODUCT_CATEGORY
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 33
 * Depends on   : oracle/ddl/03_create_schemas.sql
 * Called by    : PKG_PRODUCT_MASTER, PRODUCT_MASTER, DIM_Load_StockItem downstream
 *
 * Category master. Self-referencing parent, but only three levels are actually
 * used and the depth is enforced by convention. MERCH_GROUP_CD is the code the
 * buying team uses and does not line up with the category tree.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_PRODUCT_CATEGORY
    START WITH 1001 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE TABLE WWI_MDM.PRODUCT_CATEGORY
(
    PRODUCT_CATEGORY_ID     NUMBER(9)       NOT NULL,
    CATEGORY_CD             VARCHAR2(12)    NOT NULL,
    CATEGORY_NAME           VARCHAR2(80)    NOT NULL,
    PARENT_CATEGORY_ID      NUMBER(9),
    CATEGORY_LEVEL_NBR      NUMBER(1)       DEFAULT 1 NOT NULL,
    MERCH_GROUP_CD          VARCHAR2(8),
    DEFAULT_TAX_CLASS_CD    VARCHAR2(8),
    MARGIN_TARGET_PCT       NUMBER(5,2),
    ACTIVE_FLG              VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    SORT_ORDER_NBR          NUMBER(5),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (PRODUCT_CATEGORY_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_PRODUCT_CATEGORY_CD UNIQUE (CATEGORY_CD) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_PRODUCT_CATEGORY_LVL CHECK (CATEGORY_LEVEL_NBR BETWEEN 1 AND 3),
    CONSTRAINT CK_PRODUCT_CATEGORY_ACT CHECK (ACTIVE_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_MDM.PRODUCT_CATEGORY ADD CONSTRAINT FK_PRODUCT_CATEGORY_PARENT
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES WWI_MDM.PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID)
/

ALTER TABLE WWI_MDM.PRODUCT_MASTER ADD CONSTRAINT FK_PRODUCT_CATEGORY
    FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES WWI_MDM.PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID)
/

CREATE INDEX WWI_MDM.IX_PRODUCT_CATEGORY_PARENT
    ON WWI_MDM.PRODUCT_CATEGORY (PARENT_CATEGORY_ID) TABLESPACE WWI_IDX
/
