/* =====================================================================
 * Object       : TABLE WWI_MDM.PRODUCT_SUBSTITUTE
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 36
 * Depends on   : WWI_MDM.PRODUCT_MASTER
 * Called by    : PKG_PRODUCT_MASTER, order promising, procurement sourcing
 *
 * Substitution rules. Direction matters: A may substitute for B without B
 * substituting for A. Regional availability is a flag triple rather than rows,
 * which is why a substitute valid only in EU still shows on NA pick lists when
 * the caller forgets to filter.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_PRODUCT_SUBSTITUTE
    START WITH 40001 INCREMENT BY 1 CACHE 10 NOCYCLE
/

CREATE TABLE WWI_MDM.PRODUCT_SUBSTITUTE
(
    PRODUCT_SUB_ID          NUMBER(12)      NOT NULL,
    PRODUCT_ID              NUMBER(12)      NOT NULL,
    SUBSTITUTE_PRODUCT_ID   NUMBER(12)      NOT NULL,
    SUB_TYPE_CD             VARCHAR2(4)     DEFAULT 'FULL' NOT NULL,
    PRIORITY_NBR            NUMBER(2)       DEFAULT 1 NOT NULL,
    CONV_QTY                NUMBER(12,4)    DEFAULT 1 NOT NULL,
    AVAILABLE_NA_FLG        VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    AVAILABLE_EU_FLG        VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    AVAILABLE_APAC_FLG      VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    REASON_CD               VARCHAR2(4),
    APPROVED_BY_CD          VARCHAR2(8),
    EFFECTIVE_DT            DATE            DEFAULT SYSDATE NOT NULL,
    END_DT                  DATE,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_PRODUCT_SUBSTITUTE PRIMARY KEY (PRODUCT_SUB_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_PRODUCT_SUB UNIQUE (PRODUCT_ID, SUBSTITUTE_PRODUCT_ID, EFFECTIVE_DT)
        USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_PRODUCT_SUB_SELF CHECK (PRODUCT_ID <> SUBSTITUTE_PRODUCT_ID),
    CONSTRAINT CK_PRODUCT_SUB_TYPE CHECK (SUB_TYPE_CD IN ('FULL', 'PART', 'UPGR', 'TEMP')),
    CONSTRAINT CK_PRODUCT_SUB_FLAGS CHECK (
        AVAILABLE_NA_FLG IN ('Y', 'N') AND AVAILABLE_EU_FLG IN ('Y', 'N')
        AND AVAILABLE_APAC_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_MDM.PRODUCT_SUBSTITUTE ADD CONSTRAINT FK_PRODUCT_SUB_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES WWI_MDM.PRODUCT_MASTER (PRODUCT_ID)
/

ALTER TABLE WWI_MDM.PRODUCT_SUBSTITUTE ADD CONSTRAINT FK_PRODUCT_SUB_SUBSTITUTE
    FOREIGN KEY (SUBSTITUTE_PRODUCT_ID) REFERENCES WWI_MDM.PRODUCT_MASTER (PRODUCT_ID)
/

CREATE INDEX WWI_MDM.IX_PRODUCT_SUB_PRIORITY
    ON WWI_MDM.PRODUCT_SUBSTITUTE (PRODUCT_ID, PRIORITY_NBR) TABLESPACE WWI_IDX
/
