/* =====================================================================
 * Object       : TABLE WWI_FIN.AP_PAYMENT
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 73
 * Depends on   : WWI_FIN.AP_INVOICE_HDR, WWI_MDM.SUPP_BANK_ACCOUNT
 * Called by    : PKG_AP_PAYMENT, V_AP_PAYMENT_EXTRACT, SSIS EXT_ORA_APPayment
 *
 * Payments to suppliers. Payment instruments differ by region and the file
 * format columns reflect that: NA cheque and ACH, EU SEPA credit transfer with
 * an end-to-end id, APAC domestic transfer with a bank-specific batch
 * reference. Voided payments keep their row and their number; the void is a
 * status change, so a naive sum over payments overstates cash out.
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_AP_PAYMENT
    START WITH 3000001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_FIN.AP_PAYMENT
(
    PAYMENT_ID              NUMBER(12)      NOT NULL,
    PAYMENT_NBR             VARCHAR2(20)    NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    SUPP_BANK_ACCOUNT_ID    NUMBER(12),
    PAYMENT_DT              DATE            NOT NULL,
    GL_DATE                 DATE,
    PERIOD_CD               VARCHAR2(7),
    REGION_CD               VARCHAR2(4)     NOT NULL,
    LEGAL_ENTITY_CD         VARCHAR2(6)     NOT NULL,
    PAYMENT_METHOD_CD       VARCHAR2(6)     NOT NULL,
    PAYMENT_CURR_CD         VARCHAR2(3)     NOT NULL,
    PAYMENT_AMT             NUMBER(15,5)    NOT NULL,
    FX_RATE                 NUMBER(18,8),
    ACCOUNTED_AMT           NUMBER(15,5),
    WITHHELD_AMT            NUMBER(15,5)    DEFAULT 0 NOT NULL,
    DISCOUNT_TAKEN_AMT      NUMBER(15,5)    DEFAULT 0 NOT NULL,
    BANK_ACCOUNT_CD         VARCHAR2(12)    NOT NULL,
    PAYMENT_BATCH_NBR       VARCHAR2(20),
    NA_CHECK_NBR            VARCHAR2(12),
    NA_ACH_TRACE_NBR        VARCHAR2(20),
    EU_SEPA_E2E_ID          VARCHAR2(35),
    EU_SEPA_MANDATE_REF     VARCHAR2(35),
    APAC_TRANSFER_REF       VARCHAR2(30),
    PAYMENT_STATUS_CD       VARCHAR2(4)     DEFAULT 'ISSD' NOT NULL,
    CLEARED_DT              DATE,
    VOID_DT                 DATE,
    VOID_REASON_CD          VARCHAR2(4),
    REISSUE_OF_PAYMENT_ID   NUMBER(12),
    POSTED_FLG              VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    JOURNAL_ID              NUMBER(12),
    REMITTANCE_SENT_FLG     VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    REMITTANCE_EMAIL_TXT    VARCHAR2(200),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_AP_PAYMENT PRIMARY KEY (PAYMENT_ID) USING INDEX TABLESPACE WWI_FIN_IDX,
    CONSTRAINT UK_AP_PAYMENT_NBR UNIQUE (BANK_ACCOUNT_CD, PAYMENT_NBR) USING INDEX TABLESPACE WWI_FIN_IDX,
    CONSTRAINT CK_AP_PAY_METHOD CHECK (
        PAYMENT_METHOD_CD IN ('CHECK', 'ACH', 'SEPA', 'WIRE', 'CARD', 'LOCAL')),
    CONSTRAINT CK_AP_PAY_STATUS CHECK (
        PAYMENT_STATUS_CD IN ('ISSD', 'CLRD', 'VOID', 'STOP', 'RETN')),
    CONSTRAINT CK_AP_PAY_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_AP_PAY_METHOD_REGION CHECK (
        (REGION_CD = 'NA'   AND PAYMENT_METHOD_CD IN ('CHECK', 'ACH', 'WIRE', 'CARD'))
     OR (REGION_CD = 'EU'   AND PAYMENT_METHOD_CD IN ('SEPA', 'WIRE', 'CARD'))
     OR (REGION_CD = 'APAC' AND PAYMENT_METHOD_CD IN ('LOCAL', 'WIRE', 'CARD'))),
    CONSTRAINT CK_AP_PAY_VOID CHECK (
        PAYMENT_STATUS_CD <> 'VOID' OR (VOID_DT IS NOT NULL AND VOID_REASON_CD IS NOT NULL)),
    CONSTRAINT CK_AP_PAY_FLAGS CHECK (POSTED_FLG IN ('Y', 'N') AND REMITTANCE_SENT_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_FIN_DATA
/

ALTER TABLE WWI_FIN.AP_PAYMENT ADD CONSTRAINT FK_AP_PAYMENT_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

CREATE INDEX WWI_FIN.IX_AP_PAYMENT_SUPP
    ON WWI_FIN.AP_PAYMENT (SUPP_ID, PAYMENT_DT) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_PAYMENT_BATCH
    ON WWI_FIN.AP_PAYMENT (PAYMENT_BATCH_NBR) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_PAYMENT_STATUS
    ON WWI_FIN.AP_PAYMENT (PAYMENT_STATUS_CD, PAYMENT_DT) TABLESPACE WWI_FIN_IDX
/
