/* =====================================================================
 * Object       : TABLE WWI_FIN.AP_INVOICE_HDR
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 70
 * Depends on   : WWI_MDM.SUPP_MASTER, WWI_FIN.PAYMENT_TERMS, WWI_PROC.PURCHASE_ORDER_HDR
 * Called by    : PKG_AP_INVOICE, V_AP_INVOICE_EXTRACT, SSIS EXT_ORA_APInvoiceHdr
 *
 * AP invoice header, range partitioned on INVOICE_DT. The supplier's own
 * invoice number is unique per supplier only, and only after trimming and
 * upper-casing, which is enforced by a function-based unique index rather than
 * a constraint because the historical rows do not comply.
 *
 * Regional divergence: EU invoices carry the supplier VAT number and a
 * self-billing indicator, NA invoices carry 1099 reportability, APAC invoices
 * carry the GST registration and an e-invoicing reference from the local tax
 * portal.
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_AP_INVOICE_HDR
    START WITH 7000001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_FIN.AP_INVOICE_HDR
(
    INVOICE_ID              NUMBER(12)      NOT NULL,
    INVOICE_NBR             VARCHAR2(30)    NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    SUPP_SITE_CD            VARCHAR2(10),
    INVOICE_TYPE_CD         VARCHAR2(6)     DEFAULT 'STD' NOT NULL,
    INVOICE_DT              DATE            NOT NULL,
    RECEIVED_DT             DATE,
    GL_DATE                 DATE            NOT NULL,
    PERIOD_CD               VARCHAR2(7),
    REGION_CD               VARCHAR2(4)     NOT NULL,
    LEGAL_ENTITY_CD         VARCHAR2(6)     NOT NULL,
    PO_ID                   NUMBER(12),
    INVOICE_CURR_CD         VARCHAR2(3)     NOT NULL,
    FX_RATE                 NUMBER(18,8),
    FX_RATE_DT              DATE,
    GROSS_AMT               NUMBER(15,5)    NOT NULL,
    NET_AMT                 NUMBER(15,5)    NOT NULL,
    TAX_AMT                 NUMBER(15,5)    DEFAULT 0 NOT NULL,
    FREIGHT_AMT             NUMBER(15,5)    DEFAULT 0 NOT NULL,
    DISCOUNT_TAKEN_AMT      NUMBER(15,5)    DEFAULT 0 NOT NULL,
    WITHHELD_AMT            NUMBER(15,5)    DEFAULT 0 NOT NULL,
    PAID_AMT                NUMBER(15,5)    DEFAULT 0 NOT NULL,
    BALANCE_AMT             NUMBER(15,5)    DEFAULT 0 NOT NULL,
    PAYMENT_TERMS_CD        VARCHAR2(8),
    DUE_DT                  DATE,
    DISCOUNT_DUE_DT         DATE,
    INVOICE_STATUS_CD       VARCHAR2(4)     DEFAULT 'ENTR' NOT NULL,
    MATCH_STATUS_CD         VARCHAR2(4)     DEFAULT 'UNMT' NOT NULL,
    APPROVAL_STATUS_CD      VARCHAR2(4)     DEFAULT 'PEND' NOT NULL,
    HOLD_COUNT              NUMBER(3)       DEFAULT 0 NOT NULL,
    EU_SUPPLIER_VAT_NBR     VARCHAR2(24),
    EU_SELF_BILLING_FLG     VARCHAR2(1),
    NA_1099_REPORTABLE_FLG  VARCHAR2(1),
    NA_1099_BOX_CD          VARCHAR2(4),
    APAC_GST_REG_NBR        VARCHAR2(24),
    APAC_EINVOICE_REF       VARCHAR2(40),
    SCANNED_IMAGE_REF       VARCHAR2(200),
    ENTERED_BY_CD           VARCHAR2(8),
    CANCELLED_FLG           VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CANCEL_DT               DATE,
    DESCRIPTION_TXT         VARCHAR2(400),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT CK_AP_HDR_TYPE CHECK (
        INVOICE_TYPE_CD IN ('STD', 'CREDIT', 'DEBIT', 'PREPAY', 'EXPNS', 'INTRCO')),
    CONSTRAINT CK_AP_HDR_STATUS CHECK (
        INVOICE_STATUS_CD IN ('ENTR', 'VALD', 'APPR', 'PART', 'PAID', 'CANC', 'HOLD')),
    CONSTRAINT CK_AP_HDR_MATCH CHECK (MATCH_STATUS_CD IN ('UNMT', 'MTCH', 'PART', 'EXCP', 'NONPO')),
    CONSTRAINT CK_AP_HDR_APPROVAL CHECK (APPROVAL_STATUS_CD IN ('PEND', 'APPR', 'REJT')),
    CONSTRAINT CK_AP_HDR_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_AP_HDR_CREDIT_SIGN CHECK (
        (INVOICE_TYPE_CD = 'CREDIT' AND GROSS_AMT <= 0)
     OR (INVOICE_TYPE_CD <> 'CREDIT')),
    CONSTRAINT CK_AP_HDR_FLAGS CHECK (
        CANCELLED_FLG IN ('Y', 'N')
        AND (EU_SELF_BILLING_FLG IS NULL OR EU_SELF_BILLING_FLG IN ('Y', 'N'))
        AND (NA_1099_REPORTABLE_FLG IS NULL OR NA_1099_REPORTABLE_FLG IN ('Y', 'N'))),
    CONSTRAINT CK_AP_HDR_REGION_FIELDS CHECK (
        (REGION_CD = 'EU'   AND NA_1099_REPORTABLE_FLG IS NULL AND APAC_GST_REG_NBR IS NULL)
     OR (REGION_CD = 'NA'   AND EU_SUPPLIER_VAT_NBR IS NULL AND APAC_GST_REG_NBR IS NULL)
     OR (REGION_CD = 'APAC' AND EU_SUPPLIER_VAT_NBR IS NULL AND NA_1099_REPORTABLE_FLG IS NULL))
)
PARTITION BY RANGE (INVOICE_DT)
(
    PARTITION AP_HDR_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_HDR_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_HDR_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_HDR_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_HDR_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_HDR_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_FIN_DATA,
    PARTITION AP_HDR_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_FIN_DATA
)
/

ALTER TABLE WWI_FIN.AP_INVOICE_HDR ADD CONSTRAINT PK_AP_INVOICE_HDR
    PRIMARY KEY (INVOICE_ID) USING INDEX TABLESPACE WWI_FIN_IDX
/

ALTER TABLE WWI_FIN.AP_INVOICE_HDR ADD CONSTRAINT FK_AP_HDR_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

CREATE UNIQUE INDEX WWI_FIN.UX_AP_HDR_SUPP_INVNBR
    ON WWI_FIN.AP_INVOICE_HDR (SUPP_ID, UPPER(TRIM(INVOICE_NBR))) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_HDR_DUE
    ON WWI_FIN.AP_INVOICE_HDR (DUE_DT, INVOICE_STATUS_CD) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_HDR_PO
    ON WWI_FIN.AP_INVOICE_HDR (PO_ID) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_HDR_UPDATED
    ON WWI_FIN.AP_INVOICE_HDR (UPDATED_DT) TABLESPACE WWI_FIN_IDX
/

COMMENT ON COLUMN WWI_FIN.AP_INVOICE_HDR.HOLD_COUNT IS
    'Count of open holds, maintained by PKG_AP_INVOICE. Not derived from AP_INVOICE_HOLD at read time.'
/
