/* =====================================================================
 * Object       : TABLE WWI_PROC.VENDOR_CONTRACT_LINE
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 53
 * Depends on   : WWI_PROC.VENDOR_CONTRACT, WWI_MDM.PRODUCT_MASTER
 * Called by    : PKG_PURCHASE_ORDER (contract price lookup)
 *
 * Contracted item prices. The price a PO picks up is the contract line price
 * where the order date falls inside the line's own effective window - which is
 * not always the same window as the contract header, because line prices are
 * re-negotiated mid-term.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_VENDOR_CONTRACT_LINE
    START WITH 40001 INCREMENT BY 1 CACHE 50 NOCYCLE
/

CREATE TABLE WWI_PROC.VENDOR_CONTRACT_LINE
(
    CONTRACT_LINE_ID        NUMBER(12)      NOT NULL,
    CONTRACT_ID             NUMBER(12)      NOT NULL,
    LINE_NBR                NUMBER(5)       NOT NULL,
    PRODUCT_ID              NUMBER(12),
    SUPPLIER_ITEM_CD        VARCHAR2(30),
    CATEGORY_CD             VARCHAR2(12),
    ITEM_DESC_TXT           VARCHAR2(400),
    CONTRACT_PRICE          NUMBER(15,5)    NOT NULL,
    PRICE_UOM_CD            VARCHAR2(4)     NOT NULL,
    PRICE_CURR_CD           VARCHAR2(3)     NOT NULL,
    MIN_QTY                 NUMBER(14,4),
    MAX_QTY                 NUMBER(14,4),
    LEAD_TIME_DAYS          NUMBER(4),
    PRICE_EFFECTIVE_DT      DATE            NOT NULL,
    PRICE_END_DT            DATE,
    ESCALATION_INDEX_CD     VARCHAR2(10),
    ESCALATION_CAP_PCT      NUMBER(5,2),
    LINE_STATUS_CD          VARCHAR2(4)     DEFAULT 'ACTV' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_VENDOR_CONTRACT_LINE PRIMARY KEY (CONTRACT_LINE_ID)
        USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_CONTRACT_LINE_NBR UNIQUE (CONTRACT_ID, LINE_NBR) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_CONTRACT_LINE_PRICE CHECK (CONTRACT_PRICE >= 0),
    CONSTRAINT CK_CONTRACT_LINE_QTY CHECK (
        MIN_QTY IS NULL OR MAX_QTY IS NULL OR MAX_QTY >= MIN_QTY),
    CONSTRAINT CK_CONTRACT_LINE_STATUS CHECK (LINE_STATUS_CD IN ('ACTV', 'SUSP', 'EXPD'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_PROC.VENDOR_CONTRACT_LINE ADD CONSTRAINT FK_CONTRACT_LINE_HDR
    FOREIGN KEY (CONTRACT_ID) REFERENCES WWI_PROC.VENDOR_CONTRACT (CONTRACT_ID)
/

ALTER TABLE WWI_PROC.VENDOR_CONTRACT_LINE ADD CONSTRAINT FK_CONTRACT_LINE_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES WWI_MDM.PRODUCT_MASTER (PRODUCT_ID)
/

CREATE INDEX WWI_PROC.IX_CONTRACT_LINE_PRICE_LOOKUP
    ON WWI_PROC.VENDOR_CONTRACT_LINE (PRODUCT_ID, PRICE_EFFECTIVE_DT, PRICE_END_DT)
    TABLESPACE WWI_IDX
/
