/* =====================================================================
 * Object       : TABLE WWI_MDM.SUPP_CONTACT
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 29
 * Depends on   : WWI_MDM.SUPP_MASTER, WWI_MDM.SUPP_ADDRESS
 * Called by    : PKG_SUPPLIER_MASTER, procurement expediting reports
 *
 * Supplier-side people, optionally tied to a site. ESCALATION_LEVEL_NBR drives
 * the expediting chain (1 = first call, 3 = account executive). PORTAL_USER_ID
 * was added when the 2013 supplier portal went in and is null for suppliers who
 * never enrolled, which is most of them.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_SUPP_CONTACT
    START WITH 960001 INCREMENT BY 1 CACHE 20 NOCYCLE
/

CREATE TABLE WWI_MDM.SUPP_CONTACT
(
    SUPP_CONTACT_ID         NUMBER(12)      NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    SUPP_ADDR_ID            NUMBER(12),
    CONTACT_ROLE_CD         VARCHAR2(6)     NOT NULL,
    CONTACT_NAME            VARCHAR2(120)   NOT NULL,
    JOB_TITLE_TXT           VARCHAR2(80),
    EMAIL_ADDR              VARCHAR2(120),
    PHONE_NBR               VARCHAR2(30),
    MOBILE_NBR              VARCHAR2(30),
    LANGUAGE_CD             VARCHAR2(3)     DEFAULT 'ENG' NOT NULL,
    ESCALATION_LEVEL_NBR    NUMBER(1)       DEFAULT 1 NOT NULL,
    PORTAL_USER_ID          VARCHAR2(30),
    PORTAL_ENROLLED_DT      DATE,
    ACTIVE_FLG              VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_SUPP_CONTACT PRIMARY KEY (SUPP_CONTACT_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_SUPP_CONTACT_ROLE CHECK (
        CONTACT_ROLE_CD IN ('SALES', 'AR', 'QUAL', 'LOGIS', 'EXEC')),
    CONSTRAINT CK_SUPP_CONTACT_ESC CHECK (ESCALATION_LEVEL_NBR BETWEEN 1 AND 3),
    CONSTRAINT CK_SUPP_CONTACT_ACTIVE CHECK (ACTIVE_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_MDM.SUPP_CONTACT ADD CONSTRAINT FK_SUPP_CONTACT_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

ALTER TABLE WWI_MDM.SUPP_CONTACT ADD CONSTRAINT FK_SUPP_CONTACT_ADDR
    FOREIGN KEY (SUPP_ADDR_ID) REFERENCES WWI_MDM.SUPP_ADDRESS (SUPP_ADDR_ID)
/

CREATE INDEX WWI_MDM.IX_SUPP_CONTACT_SUPP
    ON WWI_MDM.SUPP_CONTACT (SUPP_ID, CONTACT_ROLE_CD, ESCALATION_LEVEL_NBR) TABLESPACE WWI_IDX
/

CREATE UNIQUE INDEX WWI_MDM.UX_SUPP_CONTACT_PORTAL
    ON WWI_MDM.SUPP_CONTACT (PORTAL_USER_ID) TABLESPACE WWI_IDX
/
