/* =====================================================================
 * Object       : TABLE WWI_PROC.GOODS_RETURN_HDR
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 50
 * Depends on   : WWI_PROC.PO_RECEIPT_HDR, WWI_MDM.SUPP_MASTER
 * Called by    : PKG_RECEIPTS (return path), AP debit-memo creation
 *
 * Return-to-vendor header. A return may or may not generate a debit memo in
 * AP; when it does, DEBIT_MEMO_NBR is filled by PKG_AP_INVOICE and there is no
 * foreign key back to the invoice, only the number.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_GOODS_RETURN_HDR
    START WITH 90001 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE TABLE WWI_PROC.GOODS_RETURN_HDR
(
    RETURN_ID               NUMBER(12)      NOT NULL,
    RETURN_NBR              VARCHAR2(16)    NOT NULL,
    RETURN_DT               DATE            DEFAULT SYSDATE NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    RECEIPT_ID              NUMBER(12),
    WAREHOUSE_CD            VARCHAR2(8)     NOT NULL,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    RETURN_REASON_CD        VARCHAR2(4)     NOT NULL,
    RMA_NBR                 VARCHAR2(30),
    RMA_OBTAINED_DT         DATE,
    CARRIER_CD              VARCHAR2(8),
    SHIPPED_DT              DATE,
    RETURN_STATUS_CD        VARCHAR2(4)     DEFAULT 'DRFT' NOT NULL,
    CREDIT_EXPECTED_AMT     NUMBER(15,5),
    CREDIT_CURR_CD          VARCHAR2(3),
    DEBIT_MEMO_NBR          VARCHAR2(20),
    RESTOCK_FEE_AMT         NUMBER(15,5)    DEFAULT 0 NOT NULL,
    APPROVED_BY_CD          VARCHAR2(8),
    APPROVED_DT             DATE,
    NOTES_TXT               VARCHAR2(1000),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_GOODS_RETURN_HDR PRIMARY KEY (RETURN_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_GOODS_RETURN_NBR UNIQUE (RETURN_NBR) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_RETURN_HDR_REASON CHECK (
        RETURN_REASON_CD IN ('DAMG', 'WRNG', 'QUAL', 'OVER', 'EXPD', 'RECL')),
    CONSTRAINT CK_RETURN_HDR_STATUS CHECK (
        RETURN_STATUS_CD IN ('DRFT', 'APPR', 'SHIP', 'CRED', 'CANC')),
    CONSTRAINT CK_RETURN_HDR_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_PROC.GOODS_RETURN_HDR ADD CONSTRAINT FK_RETURN_HDR_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

ALTER TABLE WWI_PROC.GOODS_RETURN_HDR ADD CONSTRAINT FK_RETURN_HDR_RECEIPT
    FOREIGN KEY (RECEIPT_ID) REFERENCES WWI_PROC.PO_RECEIPT_HDR (RECEIPT_ID)
/

CREATE INDEX WWI_PROC.IX_RETURN_HDR_SUPP
    ON WWI_PROC.GOODS_RETURN_HDR (SUPP_ID, RETURN_DT) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_PROC.IX_RETURN_HDR_STATUS
    ON WWI_PROC.GOODS_RETURN_HDR (RETURN_STATUS_CD, RETURN_DT) TABLESPACE WWI_IDX
/
