/* =====================================================================
 * Object       : TABLE WWI_MDM.PRODUCT_MASTER
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 32
 * Depends on   : WWI_MDM.PRODUCT_CATEGORY, WWI_REF.UOM_REF
 * Called by    : PKG_PRODUCT_MASTER, V_PRODUCT_EXTRACT, SSIS EXT_ORA_ProductMaster
 *
 * Item master for everything the business buys or sells. The WideWorldImporters
 * stock item id is carried as WWI_STOCK_ITEM_ID so the SQL Server OLTP system
 * can be reconciled against the ERP; it is null for purchase-only items.
 * CHILLER_FLG and hazard columns come from the 2009 cold-chain project.
 * UNIT_COST_STD is the standard cost in the item's own costing currency and is
 * NOT the same figure the finance ledger uses - GL uses PRODUCT_COST history.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_PRODUCT_MASTER
    START WITH 10001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_MDM.PRODUCT_MASTER
(
    PRODUCT_ID              NUMBER(12)      NOT NULL,
    ITEM_NBR                VARCHAR2(18)    NOT NULL,
    LEGACY_PART_CD          VARCHAR2(12),
    WWI_STOCK_ITEM_ID       NUMBER(10),
    ITEM_DESC               VARCHAR2(200)   NOT NULL,
    ITEM_DESC_SHORT         VARCHAR2(60),
    PRODUCT_CATEGORY_ID     NUMBER(9),
    BRAND_CD                VARCHAR2(10),
    ITEM_TYPE_CD            VARCHAR2(4)     DEFAULT 'STK' NOT NULL,
    LIFECYCLE_STATUS_CD     VARCHAR2(4)     DEFAULT 'ACT' NOT NULL,
    PRIMARY_UOM_CD          VARCHAR2(4)     NOT NULL,
    PURCHASE_UOM_CD         VARCHAR2(4),
    SELL_UOM_CD             VARCHAR2(4),
    UNIT_COST_STD           NUMBER(15,5),
    COST_CURR_CD            VARCHAR2(3),
    LIST_PRICE_AMT          NUMBER(15,5),
    LIST_PRICE_CURR_CD      VARCHAR2(3),
    TAX_CLASS_CD            VARCHAR2(8),
    COMMODITY_CD            VARCHAR2(12),
    HS_TARIFF_CD            VARCHAR2(12),
    COUNTRY_OF_ORIGIN_CD    VARCHAR2(2),
    UNIT_WEIGHT_KG          NUMBER(12,4),
    UNIT_VOLUME_M3          NUMBER(12,5),
    SHELF_LIFE_DAYS         NUMBER(5),
    CHILLER_FLG             VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    HAZMAT_FLG              VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    HAZMAT_CLASS_CD         VARCHAR2(6),
    SERIALISED_FLG          VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    LOT_CONTROLLED_FLG      VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    REORDER_POINT_QTY       NUMBER(12,3),
    SAFETY_STOCK_QTY        NUMBER(12,3),
    DISCONTINUED_DT         DATE,
    REPLACEMENT_PRODUCT_ID  NUMBER(12),
    ENG_NOTES_TXT           VARCHAR2(2000),
    DELETED_FLG             VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_PRODUCT_MASTER PRIMARY KEY (PRODUCT_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_PRODUCT_MASTER_ITEM UNIQUE (ITEM_NBR) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_PRODUCT_TYPE CHECK (ITEM_TYPE_CD IN ('STK', 'NST', 'SVC', 'KIT', 'PHTM')),
    CONSTRAINT CK_PRODUCT_LIFECYCLE CHECK (
        LIFECYCLE_STATUS_CD IN ('NEW', 'ACT', 'PHSE', 'DISC', 'OBSL')),
    CONSTRAINT CK_PRODUCT_FLAGS CHECK (
        CHILLER_FLG IN ('Y', 'N') AND HAZMAT_FLG IN ('Y', 'N') AND SERIALISED_FLG IN ('Y', 'N')
        AND LOT_CONTROLLED_FLG IN ('Y', 'N') AND DELETED_FLG IN ('Y', 'N')),
    CONSTRAINT CK_PRODUCT_HAZMAT CHECK (HAZMAT_FLG = 'N' OR HAZMAT_CLASS_CD IS NOT NULL),
    CONSTRAINT CK_PRODUCT_DISC CHECK (
        LIFECYCLE_STATUS_CD <> 'DISC' OR DISCONTINUED_DT IS NOT NULL)
)
TABLESPACE WWI_DATA
PCTFREE 10
/

ALTER TABLE WWI_MDM.PRODUCT_MASTER ADD CONSTRAINT FK_PRODUCT_REPLACEMENT
    FOREIGN KEY (REPLACEMENT_PRODUCT_ID) REFERENCES WWI_MDM.PRODUCT_MASTER (PRODUCT_ID)
/

CREATE INDEX WWI_MDM.IX_PRODUCT_CATEGORY
    ON WWI_MDM.PRODUCT_MASTER (PRODUCT_CATEGORY_ID, LIFECYCLE_STATUS_CD) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_MDM.IX_PRODUCT_DESC_UPPER
    ON WWI_MDM.PRODUCT_MASTER (UPPER(ITEM_DESC_SHORT)) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_MDM.IX_PRODUCT_WWI_STOCK
    ON WWI_MDM.PRODUCT_MASTER (WWI_STOCK_ITEM_ID) TABLESPACE WWI_IDX
/

COMMENT ON COLUMN WWI_MDM.PRODUCT_MASTER.WWI_STOCK_ITEM_ID IS
    'Key of the matching row in the WideWorldImporters OLTP StockItems table.'
/
COMMENT ON COLUMN WWI_MDM.PRODUCT_MASTER.ENG_NOTES_TXT IS
    'Free text; the phrase NO-SUBSTITUTE in here is treated as a business rule by procurement.'
/
