/* =====================================================================
 * Object       : TABLE WWI_PROC.PO_RECEIPT_LINE
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 49
 * Depends on   : WWI_PROC.PO_RECEIPT_HDR, WWI_PROC.PURCHASE_ORDER_LINE
 * Called by    : PKG_RECEIPTS (three-way match), V_RECEIPT_EXTRACT
 *
 * Receipt lines, range partitioned on RECEIPT_DT. Over- and under-receipt
 * tolerance is evaluated here and the outcome frozen into TOLERANCE_STATUS_CD;
 * the tolerance percentages themselves are region-specific and live in
 * WWI_REF.CODE_TRANSLATION, so a historical row cannot be re-derived once the
 * tolerance changes.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_PO_RECEIPT_LINE
    START WITH 6000001 INCREMENT BY 1 CACHE 200 NOCYCLE
/

CREATE TABLE WWI_PROC.PO_RECEIPT_LINE
(
    RECEIPT_LINE_ID         NUMBER(12)      NOT NULL,
    RECEIPT_ID              NUMBER(12)      NOT NULL,
    RECEIPT_DT              DATE            NOT NULL,
    LINE_NBR                NUMBER(5)       NOT NULL,
    PO_ID                   NUMBER(12)      NOT NULL,
    PO_LINE_ID              NUMBER(12)      NOT NULL,
    PRODUCT_ID              NUMBER(12),
    RECEIVED_QTY            NUMBER(14,4)    NOT NULL,
    ACCEPTED_QTY            NUMBER(14,4)    DEFAULT 0 NOT NULL,
    REJECTED_QTY            NUMBER(14,4)    DEFAULT 0 NOT NULL,
    UOM_CD                  VARCHAR2(4)     NOT NULL,
    UNIT_COST               NUMBER(15,5),
    EXTENDED_COST           NUMBER(15,5),
    COST_CURR_CD            VARCHAR2(3),
    LOT_NBR                 VARCHAR2(30),
    SERIAL_RANGE_TXT        VARCHAR2(200),
    EXPIRY_DT               DATE,
    PUTAWAY_LOCATION_CD     VARCHAR2(12),
    TOLERANCE_STATUS_CD     VARCHAR2(4)     DEFAULT 'OK' NOT NULL,
    VARIANCE_PCT            NUMBER(7,3),
    REJECT_REASON_CD        VARCHAR2(4),
    INSPECTION_RESULT_CD    VARCHAR2(4),
    MATCHED_INVOICE_LINE_ID NUMBER(12),
    LINE_STATUS_CD          VARCHAR2(4)     DEFAULT 'OPEN' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT CK_RCPT_LINE_QTY CHECK (RECEIVED_QTY <> 0),
    CONSTRAINT CK_RCPT_LINE_SPLIT CHECK (ACCEPTED_QTY >= 0 AND REJECTED_QTY >= 0),
    CONSTRAINT CK_RCPT_LINE_TOL CHECK (TOLERANCE_STATUS_CD IN ('OK', 'OVER', 'UNDR', 'HOLD')),
    CONSTRAINT CK_RCPT_LINE_STATUS CHECK (LINE_STATUS_CD IN ('OPEN', 'MTCH', 'CLSD', 'REVS')),
    CONSTRAINT CK_RCPT_LINE_REJECT CHECK (REJECTED_QTY = 0 OR REJECT_REASON_CD IS NOT NULL)
)
PARTITION BY RANGE (RECEIPT_DT)
(
    PARTITION RCPT_LINE_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION RCPT_LINE_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION RCPT_LINE_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION RCPT_LINE_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION RCPT_LINE_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION RCPT_LINE_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_DATA,
    PARTITION RCPT_LINE_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_DATA
)
/

ALTER TABLE WWI_PROC.PO_RECEIPT_LINE ADD CONSTRAINT PK_PO_RECEIPT_LINE
    PRIMARY KEY (RECEIPT_LINE_ID) USING INDEX TABLESPACE WWI_HIST_IDX
/

ALTER TABLE WWI_PROC.PO_RECEIPT_LINE ADD CONSTRAINT UK_RCPT_LINE_NBR
    UNIQUE (RECEIPT_ID, LINE_NBR) USING INDEX TABLESPACE WWI_HIST_IDX
/

ALTER TABLE WWI_PROC.PO_RECEIPT_LINE ADD CONSTRAINT FK_RCPT_LINE_HDR
    FOREIGN KEY (RECEIPT_ID) REFERENCES WWI_PROC.PO_RECEIPT_HDR (RECEIPT_ID)
/

ALTER TABLE WWI_PROC.PO_RECEIPT_LINE ADD CONSTRAINT FK_RCPT_LINE_PO_LINE
    FOREIGN KEY (PO_LINE_ID) REFERENCES WWI_PROC.PURCHASE_ORDER_LINE (PO_LINE_ID)
/

CREATE INDEX WWI_PROC.IX_RCPT_LINE_PO_LINE
    ON WWI_PROC.PO_RECEIPT_LINE (PO_LINE_ID) TABLESPACE WWI_HIST_IDX
/

CREATE INDEX WWI_PROC.IX_RCPT_LINE_PRODUCT
    ON WWI_PROC.PO_RECEIPT_LINE (PRODUCT_ID, RECEIPT_DT) LOCAL TABLESPACE WWI_HIST_IDX
/

CREATE INDEX WWI_PROC.IX_RCPT_LINE_LOT
    ON WWI_PROC.PO_RECEIPT_LINE (LOT_NBR) TABLESPACE WWI_HIST_IDX
/
