/* =====================================================================
 * Object       : TABLE WWI_FIN.GL_JOURNAL_LINE
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 69
 * Depends on   : WWI_FIN.GL_JOURNAL_HDR, WWI_FIN.GL_ACCOUNT, WWI_FIN.COST_CENTER
 * Called by    : PKG_GL_POST, V_GL_JOURNAL_EXTRACT, trial-balance reporting
 *
 * Journal lines. Debit and credit are separate columns rather than a signed
 * amount, and both are NOT NULL with a zero default, so a line always has one
 * zero side. Entered and accounted amounts are both held; they differ whenever
 * the journal currency is not the ledger currency and the FX rate on the
 * header was overridden by the preparer.
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_GL_JOURNAL_LINE
    START WITH 20000001 INCREMENT BY 1 CACHE 500 NOCYCLE
/

CREATE TABLE WWI_FIN.GL_JOURNAL_LINE
(
    JOURNAL_LINE_ID         NUMBER(12)      NOT NULL,
    JOURNAL_ID              NUMBER(12)      NOT NULL,
    ACCOUNTING_DT           DATE            NOT NULL,
    LINE_NBR                NUMBER(6)       NOT NULL,
    ACCOUNT_CD              VARCHAR2(30)    NOT NULL,
    COST_CENTER_CD          VARCHAR2(10),
    PROJECT_CD              VARCHAR2(12),
    INTERCOMPANY_CD         VARCHAR2(6),
    ENTERED_DEBIT_AMT       NUMBER(15,5)    DEFAULT 0 NOT NULL,
    ENTERED_CREDIT_AMT      NUMBER(15,5)    DEFAULT 0 NOT NULL,
    ENTERED_CURR_CD         VARCHAR2(3)     NOT NULL,
    ACCOUNTED_DEBIT_AMT     NUMBER(15,5)    DEFAULT 0 NOT NULL,
    ACCOUNTED_CREDIT_AMT    NUMBER(15,5)    DEFAULT 0 NOT NULL,
    LEDGER_CURR_CD          VARCHAR2(3)     NOT NULL,
    STAT_QTY                NUMBER(15,5),
    STAT_UOM_CD             VARCHAR2(4),
    LINE_DESC               VARCHAR2(240),
    REFERENCE_1_TXT         VARCHAR2(60),
    REFERENCE_2_TXT         VARCHAR2(60),
    REFERENCE_3_TXT         VARCHAR2(60),
    SOURCE_DOC_TYPE_CD      VARCHAR2(6),
    SOURCE_DOC_ID           NUMBER(12),
    TAX_CODE_CD             VARCHAR2(8),
    RECONCILED_FLG          VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    RECONCILED_DT           DATE,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT CK_GL_JLINE_SIDE CHECK (
        (ENTERED_DEBIT_AMT = 0 AND ENTERED_CREDIT_AMT >= 0)
     OR (ENTERED_CREDIT_AMT = 0 AND ENTERED_DEBIT_AMT >= 0)),
    CONSTRAINT CK_GL_JLINE_RECON CHECK (RECONCILED_FLG IN ('Y', 'N')),
    CONSTRAINT CK_GL_JLINE_DOCTYPE CHECK (
        SOURCE_DOC_TYPE_CD IS NULL
     OR SOURCE_DOC_TYPE_CD IN ('APINV', 'APPAY', 'PO', 'RCPT', 'ALLOC', 'MANL'))
)
PARTITION BY RANGE (ACCOUNTING_DT)
(
    PARTITION GL_JLINE_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JLINE_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JLINE_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JLINE_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JLINE_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION GL_JLINE_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_FIN_DATA,
    PARTITION GL_JLINE_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_FIN_DATA
)
/

ALTER TABLE WWI_FIN.GL_JOURNAL_LINE ADD CONSTRAINT PK_GL_JOURNAL_LINE
    PRIMARY KEY (JOURNAL_LINE_ID) USING INDEX TABLESPACE WWI_FIN_IDX
/

ALTER TABLE WWI_FIN.GL_JOURNAL_LINE ADD CONSTRAINT UK_GL_JLINE_NBR
    UNIQUE (JOURNAL_ID, LINE_NBR) USING INDEX TABLESPACE WWI_FIN_IDX
/

ALTER TABLE WWI_FIN.GL_JOURNAL_LINE ADD CONSTRAINT FK_GL_JLINE_HDR
    FOREIGN KEY (JOURNAL_ID) REFERENCES WWI_FIN.GL_JOURNAL_HDR (JOURNAL_ID)
/

ALTER TABLE WWI_FIN.GL_JOURNAL_LINE ADD CONSTRAINT FK_GL_JLINE_ACCOUNT
    FOREIGN KEY (ACCOUNT_CD) REFERENCES WWI_FIN.GL_ACCOUNT (ACCOUNT_CD)
/

CREATE INDEX WWI_FIN.IX_GL_JLINE_ACCOUNT
    ON WWI_FIN.GL_JOURNAL_LINE (ACCOUNT_CD, ACCOUNTING_DT) LOCAL TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_GL_JLINE_COST_CENTER
    ON WWI_FIN.GL_JOURNAL_LINE (COST_CENTER_CD, ACCOUNTING_DT) LOCAL TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_GL_JLINE_SOURCE_DOC
    ON WWI_FIN.GL_JOURNAL_LINE (SOURCE_DOC_TYPE_CD, SOURCE_DOC_ID) TABLESPACE WWI_FIN_IDX
/

COMMENT ON COLUMN WWI_FIN.GL_JOURNAL_LINE.REFERENCE_3_TXT IS
    'Free text. AP writes the supplier invoice number here; the allocation batch writes the rule set code.'
/
