/* =====================================================================
 * Object       : TABLE WWI_FIN.AP_INVOICE_LINE
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 71
 * Depends on   : WWI_FIN.AP_INVOICE_HDR, WWI_FIN.GL_ACCOUNT, WWI_PROC.PURCHASE_ORDER_LINE
 * Called by    : PKG_AP_INVOICE (distribution and match), V_AP_DISTRIBUTION_EXTRACT
 *
 * Invoice distribution lines. A single table holds item, tax, freight and
 * miscellaneous distributions, distinguished by LINE_TYPE_CD - so any spend
 * query that forgets to filter on line type double counts tax. Prorated tax
 * lines carry a pointer to the item line they were prorated from, held as an
 * id with no foreign key.
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_AP_INVOICE_LINE
    START WITH 15000001 INCREMENT BY 1 CACHE 500 NOCYCLE
/

CREATE TABLE WWI_FIN.AP_INVOICE_LINE
(
    INVOICE_LINE_ID         NUMBER(12)      NOT NULL,
    INVOICE_ID              NUMBER(12)      NOT NULL,
    INVOICE_DT              DATE            NOT NULL,
    LINE_NBR                NUMBER(6)       NOT NULL,
    LINE_TYPE_CD            VARCHAR2(6)     DEFAULT 'ITEM' NOT NULL,
    PO_LINE_ID              NUMBER(12),
    RECEIPT_LINE_ID         NUMBER(12),
    PRODUCT_ID              NUMBER(12),
    ITEM_DESC_TXT           VARCHAR2(400),
    QUANTITY                NUMBER(14,4),
    UOM_CD                  VARCHAR2(4),
    UNIT_PRICE              NUMBER(15,5),
    LINE_AMT                NUMBER(15,5)    NOT NULL,
    LINE_CURR_CD            VARCHAR2(3)     NOT NULL,
    ACCOUNTED_AMT           NUMBER(15,5),
    ACCOUNT_CD              VARCHAR2(30)    NOT NULL,
    COST_CENTER_CD          VARCHAR2(10),
    PROJECT_CD              VARCHAR2(12),
    TAX_CODE_CD             VARCHAR2(8),
    TAX_RATE_PCT            NUMBER(7,5),
    RECOVERABLE_TAX_AMT     NUMBER(15,5),
    NON_RECOVERABLE_TAX_AMT NUMBER(15,5),
    PRORATED_FROM_LINE_ID   NUMBER(12),
    PRICE_VARIANCE_AMT      NUMBER(15,5),
    QTY_VARIANCE_AMT        NUMBER(15,5),
    MATCH_STATUS_CD         VARCHAR2(4)     DEFAULT 'UNMT' NOT NULL,
    ACCRUAL_REVERSED_FLG    VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    POSTED_FLG              VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    JOURNAL_ID              NUMBER(12),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT CK_AP_LINE_TYPE CHECK (
        LINE_TYPE_CD IN ('ITEM', 'TAX', 'FRGHT', 'MISC', 'RETNG', 'WHT')),
    CONSTRAINT CK_AP_LINE_MATCH CHECK (MATCH_STATUS_CD IN ('UNMT', 'MTCH', 'EXCP', 'NA')),
    CONSTRAINT CK_AP_LINE_FLAGS CHECK (
        POSTED_FLG IN ('Y', 'N') AND ACCRUAL_REVERSED_FLG IN ('Y', 'N')),
    CONSTRAINT CK_AP_LINE_TAX_SPLIT CHECK (
        LINE_TYPE_CD <> 'TAX' OR TAX_CODE_CD IS NOT NULL)
)
PARTITION BY RANGE (INVOICE_DT)
(
    PARTITION AP_LINE_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_LINE_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_LINE_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_LINE_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_LINE_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION AP_LINE_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_FIN_DATA,
    PARTITION AP_LINE_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_FIN_DATA
)
/

ALTER TABLE WWI_FIN.AP_INVOICE_LINE ADD CONSTRAINT PK_AP_INVOICE_LINE
    PRIMARY KEY (INVOICE_LINE_ID) USING INDEX TABLESPACE WWI_FIN_IDX
/

ALTER TABLE WWI_FIN.AP_INVOICE_LINE ADD CONSTRAINT UK_AP_LINE_NBR
    UNIQUE (INVOICE_ID, LINE_NBR) USING INDEX TABLESPACE WWI_FIN_IDX
/

ALTER TABLE WWI_FIN.AP_INVOICE_LINE ADD CONSTRAINT FK_AP_LINE_HDR
    FOREIGN KEY (INVOICE_ID) REFERENCES WWI_FIN.AP_INVOICE_HDR (INVOICE_ID)
/

ALTER TABLE WWI_FIN.AP_INVOICE_LINE ADD CONSTRAINT FK_AP_LINE_ACCOUNT
    FOREIGN KEY (ACCOUNT_CD) REFERENCES WWI_FIN.GL_ACCOUNT (ACCOUNT_CD)
/

CREATE INDEX WWI_FIN.IX_AP_LINE_PO_LINE
    ON WWI_FIN.AP_INVOICE_LINE (PO_LINE_ID) TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_LINE_ACCOUNT
    ON WWI_FIN.AP_INVOICE_LINE (ACCOUNT_CD, INVOICE_DT) LOCAL TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_AP_LINE_TYPE
    ON WWI_FIN.AP_INVOICE_LINE (LINE_TYPE_CD, POSTED_FLG) TABLESPACE WWI_FIN_IDX
/
