/* =====================================================================
 * Object       : TABLE WWI_PROC.SUPPLIER_QUOTE
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 43
 * Depends on   : WWI_PROC.SOURCING_EVENT, WWI_MDM.SUPP_MASTER
 * Called by    : PKG_SUPPLIER_PERF, sourcing award analysis
 *
 * A supplier's response header to a sourcing event. Quotes are versioned by
 * REVISION_NBR; only the highest revision is scored, but every revision is
 * kept and the extract that forgets to filter double counts quoted value.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_SUPPLIER_QUOTE
    START WITH 30001 INCREMENT BY 1 CACHE 20 NOCYCLE
/

CREATE TABLE WWI_PROC.SUPPLIER_QUOTE
(
    QUOTE_ID                NUMBER(12)      NOT NULL,
    EVENT_ID                NUMBER(12)      NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    QUOTE_NBR               VARCHAR2(20),
    REVISION_NBR            NUMBER(3)       DEFAULT 1 NOT NULL,
    RECEIVED_DT             DATE            NOT NULL,
    VALID_UNTIL_DT          DATE,
    QUOTE_CURR_CD           VARCHAR2(3)     NOT NULL,
    QUOTE_TOTAL_AMT         NUMBER(15,5),
    FREIGHT_AMT             NUMBER(15,5)    DEFAULT 0 NOT NULL,
    INCOTERM_CD             VARCHAR2(3),
    PAYMENT_TERMS_CD        VARCHAR2(8),
    LEAD_TIME_DAYS          NUMBER(4),
    TECHNICAL_SCORE         NUMBER(5,2),
    COMMERCIAL_SCORE        NUMBER(5,2),
    TOTAL_SCORE             NUMBER(5,2),
    RANK_NBR                NUMBER(3),
    QUOTE_STATUS_CD         VARCHAR2(4)     DEFAULT 'RECV' NOT NULL,
    DISQUALIFY_REASON_CD    VARCHAR2(4),
    NOTES_TXT               VARCHAR2(2000),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_SUPPLIER_QUOTE PRIMARY KEY (QUOTE_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_SUPPLIER_QUOTE UNIQUE (EVENT_ID, SUPP_ID, REVISION_NBR)
        USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_SUPPLIER_QUOTE_STATUS CHECK (
        QUOTE_STATUS_CD IN ('RECV', 'SCOR', 'AWRD', 'LOST', 'DISQ')),
    CONSTRAINT CK_SUPPLIER_QUOTE_DISQ CHECK (
        QUOTE_STATUS_CD <> 'DISQ' OR DISQUALIFY_REASON_CD IS NOT NULL),
    CONSTRAINT CK_SUPPLIER_QUOTE_SCORE CHECK (
        TOTAL_SCORE IS NULL OR TOTAL_SCORE BETWEEN 0 AND 100)
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_PROC.SUPPLIER_QUOTE ADD CONSTRAINT FK_SUPPLIER_QUOTE_EVENT
    FOREIGN KEY (EVENT_ID) REFERENCES WWI_PROC.SOURCING_EVENT (EVENT_ID)
/

ALTER TABLE WWI_PROC.SUPPLIER_QUOTE ADD CONSTRAINT FK_SUPPLIER_QUOTE_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

CREATE INDEX WWI_PROC.IX_SUPPLIER_QUOTE_SUPP
    ON WWI_PROC.SUPPLIER_QUOTE (SUPP_ID, RECEIVED_DT) TABLESPACE WWI_IDX
/
