/* =====================================================================
 * Object       : TABLE WWI_PROC.PURCHASE_ORDER_HDR
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 45
 * Depends on   : WWI_MDM.SUPP_MASTER, WWI_MDM.SUPP_ADDRESS, WWI_FIN.PAYMENT_TERMS
 * Called by    : PKG_PURCHASE_ORDER, V_PURCHASE_ORDER_EXTRACT, SSIS EXT_ORA_PurchaseOrderHdr
 *
 * Purchase order header. Range partitioned on ORDER_DT by calendar year with a
 * PMAX catch-all; the 2019 and earlier partitions sit in WWI_HIST_DATA.
 *
 * Tax treatment diverges by region and is resolved at PO entry, not at
 * invoicing: NA stores a sales-tax rate and a use-tax self-assessment flag, EU
 * stores a VAT code and a reverse-charge flag, APAC stores a GST code plus the
 * withholding indicator used in a few jurisdictions.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_PURCHASE_ORDER_HDR
    START WITH 4000001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_PROC.PURCHASE_ORDER_HDR
(
    PO_ID                   NUMBER(12)      NOT NULL,
    PO_NBR                  VARCHAR2(16)    NOT NULL,
    PO_TYPE_CD              VARCHAR2(4)     DEFAULT 'STD' NOT NULL,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    SUPP_ADDR_ID            NUMBER(12),
    ORDER_DT                DATE            DEFAULT SYSDATE NOT NULL,
    PROMISED_DT             DATE,
    BUYER_CD                VARCHAR2(8)     NOT NULL,
    REQ_ID                  NUMBER(12),
    CONTRACT_ID             NUMBER(12),
    PO_STATUS_CD            VARCHAR2(4)     DEFAULT 'OPEN' NOT NULL,
    APPROVAL_STATUS_CD      VARCHAR2(4)     DEFAULT 'PEND' NOT NULL,
    ORDER_CURR_CD           VARCHAR2(3)     NOT NULL,
    FX_RATE                 NUMBER(18,8),
    FX_RATE_DT              DATE,
    SUBTOTAL_AMT            NUMBER(15,5)    DEFAULT 0 NOT NULL,
    FREIGHT_AMT             NUMBER(15,5)    DEFAULT 0 NOT NULL,
    TAX_AMT                 NUMBER(15,5)    DEFAULT 0 NOT NULL,
    TOTAL_AMT               NUMBER(15,5)    DEFAULT 0 NOT NULL,
    NA_SALES_TAX_RATE       NUMBER(7,5),
    NA_USE_TAX_SELF_FLG     VARCHAR2(1),
    EU_VAT_CD               VARCHAR2(8),
    EU_REVERSE_CHARGE_FLG   VARCHAR2(1),
    APAC_GST_CD             VARCHAR2(8),
    APAC_WHT_FLG            VARCHAR2(1),
    PAYMENT_TERMS_CD        VARCHAR2(8),
    INCOTERM_CD             VARCHAR2(3),
    SHIP_VIA_CD             VARCHAR2(8),
    SHIP_TO_LOCATION_CD     VARCHAR2(10),
    BILL_TO_LOCATION_CD     VARCHAR2(10),
    CANCELLED_FLG           VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CANCEL_REASON_CD        VARCHAR2(4),
    CLOSED_DT               DATE,
    PRINT_COUNT             NUMBER(3)       DEFAULT 0 NOT NULL,
    HEADER_NOTES_TXT        VARCHAR2(2000),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_PURCHASE_ORDER_HDR PRIMARY KEY (PO_ID) USING INDEX TABLESPACE WWI_HIST_IDX,
    CONSTRAINT CK_PO_HDR_TYPE CHECK (PO_TYPE_CD IN ('STD', 'BLKT', 'RELS', 'DROP', 'SERV')),
    CONSTRAINT CK_PO_HDR_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_PO_HDR_STATUS CHECK (
        PO_STATUS_CD IN ('OPEN', 'PART', 'RECV', 'CLSD', 'CANC', 'HOLD')),
    CONSTRAINT CK_PO_HDR_APPROVAL CHECK (APPROVAL_STATUS_CD IN ('PEND', 'APPR', 'REJT')),
    CONSTRAINT CK_PO_HDR_TAX_REGION CHECK (
        (REGION_CD = 'NA'   AND EU_VAT_CD IS NULL AND APAC_GST_CD IS NULL)
     OR (REGION_CD = 'EU'   AND NA_SALES_TAX_RATE IS NULL AND APAC_GST_CD IS NULL)
     OR (REGION_CD = 'APAC' AND NA_SALES_TAX_RATE IS NULL AND EU_VAT_CD IS NULL)),
    CONSTRAINT CK_PO_HDR_FLAGS CHECK (
        CANCELLED_FLG IN ('Y', 'N')
        AND (NA_USE_TAX_SELF_FLG IS NULL OR NA_USE_TAX_SELF_FLG IN ('Y', 'N'))
        AND (EU_REVERSE_CHARGE_FLG IS NULL OR EU_REVERSE_CHARGE_FLG IN ('Y', 'N'))
        AND (APAC_WHT_FLG IS NULL OR APAC_WHT_FLG IN ('Y', 'N')))
)
PARTITION BY RANGE (ORDER_DT)
(
    PARTITION PO_HDR_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_HDR_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_HDR_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_HDR_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_HDR_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_HDR_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_DATA,
    PARTITION PO_HDR_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_DATA
)
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_HDR ADD CONSTRAINT UK_PO_HDR_NBR
    UNIQUE (PO_NBR) USING INDEX TABLESPACE WWI_HIST_IDX
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_HDR ADD CONSTRAINT FK_PO_HDR_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_HDR ADD CONSTRAINT FK_PO_HDR_REQ
    FOREIGN KEY (REQ_ID) REFERENCES WWI_PROC.REQUISITION_HDR (REQ_ID)
/

CREATE INDEX WWI_PROC.IX_PO_HDR_SUPPLIER
    ON WWI_PROC.PURCHASE_ORDER_HDR (SUPP_ID, ORDER_DT) LOCAL TABLESPACE WWI_HIST_IDX
/

CREATE INDEX WWI_PROC.IX_PO_HDR_STATUS
    ON WWI_PROC.PURCHASE_ORDER_HDR (PO_STATUS_CD, REGION_CD) LOCAL TABLESPACE WWI_HIST_IDX
/

CREATE INDEX WWI_PROC.IX_PO_HDR_UPDATED
    ON WWI_PROC.PURCHASE_ORDER_HDR (UPDATED_DT) TABLESPACE WWI_HIST_IDX
/

COMMENT ON COLUMN WWI_PROC.PURCHASE_ORDER_HDR.PRINT_COUNT IS
    'Times the PO was printed or emailed. Used as a proxy for "was it sent".'
/
