/* =====================================================================
 * Object       : TABLE WWI_FIN.TAX_RATE
 * Schema       : WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 65
 * Depends on   : WWI_FIN.TAX_JURISDICTION
 * Called by    : PKG_TAX_CALC, PKG_AP_INVOICE, V_TAX_RATE_CURRENT
 *
 * Effective-dated tax rates per jurisdiction and tax code. Rates are never
 * updated in place, only superseded by a new row - except during the 2020
 * COVID VAT reductions, when a handful of EU rows were edited directly and the
 * history was lost.
 *
 * Reduced and zero rates are separate rows distinguished by RATE_CATEGORY_CD,
 * which carries different values per region (NA: STD/EXEMPT/RESALE, EU:
 * STD/RED1/RED2/ZERO/EXEMPT, APAC: STD/ZERO/INPUT).
 * ===================================================================== */

CREATE SEQUENCE WWI_FIN.SEQ_TAX_RATE
    START WITH 20001 INCREMENT BY 1 CACHE 20 NOCYCLE
/

CREATE TABLE WWI_FIN.TAX_RATE
(
    TAX_RATE_ID             NUMBER(12)      NOT NULL,
    TAX_CODE_CD             VARCHAR2(8)     NOT NULL,
    JURISDICTION_CD         VARCHAR2(12)    NOT NULL,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    TAX_REGIME_CD           VARCHAR2(6)     NOT NULL,
    RATE_CATEGORY_CD        VARCHAR2(8)     DEFAULT 'STD' NOT NULL,
    RATE_PCT                NUMBER(7,5)     NOT NULL,
    COMPOUND_FLG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    COMPOUND_SEQ_NBR        NUMBER(2),
    RECOVERABLE_PCT         NUMBER(5,2)     DEFAULT 100 NOT NULL,
    EFFECTIVE_FROM_DT       DATE            NOT NULL,
    EFFECTIVE_TO_DT         DATE,
    TAX_ACCOUNT_CD          VARCHAR2(30),
    REVERSE_CHARGE_FLG      VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    SELF_ASSESS_FLG         VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    REPORTING_BOX_CD        VARCHAR2(8),
    PRODUCT_CATEGORY_CD     VARCHAR2(12),
    RATE_DESC               VARCHAR2(200),
    LEGISLATION_REF_TXT     VARCHAR2(200),
    ACTIVE_FLG              VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_TAX_RATE PRIMARY KEY (TAX_RATE_ID) USING INDEX TABLESPACE WWI_FIN_IDX,
    CONSTRAINT UK_TAX_RATE_EFF UNIQUE (TAX_CODE_CD, JURISDICTION_CD, RATE_CATEGORY_CD, EFFECTIVE_FROM_DT)
        USING INDEX TABLESPACE WWI_FIN_IDX,
    CONSTRAINT CK_TAX_RATE_PCT CHECK (RATE_PCT >= 0 AND RATE_PCT <= 100),
    CONSTRAINT CK_TAX_RATE_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_TAX_RATE_CATEGORY CHECK (
        (REGION_CD = 'NA'   AND RATE_CATEGORY_CD IN ('STD', 'EXEMPT', 'RESALE'))
     OR (REGION_CD = 'EU'   AND RATE_CATEGORY_CD IN ('STD', 'RED1', 'RED2', 'ZERO', 'EXEMPT'))
     OR (REGION_CD = 'APAC' AND RATE_CATEGORY_CD IN ('STD', 'ZERO', 'INPUT', 'EXEMPT'))),
    CONSTRAINT CK_TAX_RATE_COMPOUND CHECK (
        COMPOUND_FLG IN ('Y', 'N') AND (COMPOUND_FLG = 'N' OR COMPOUND_SEQ_NBR IS NOT NULL)),
    CONSTRAINT CK_TAX_RATE_FLAGS CHECK (
        ACTIVE_FLG IN ('Y', 'N') AND REVERSE_CHARGE_FLG IN ('Y', 'N')
        AND SELF_ASSESS_FLG IN ('Y', 'N')),
    CONSTRAINT CK_TAX_RATE_DATES CHECK (EFFECTIVE_TO_DT IS NULL OR EFFECTIVE_TO_DT > EFFECTIVE_FROM_DT)
)
TABLESPACE WWI_FIN_DATA
/

ALTER TABLE WWI_FIN.TAX_RATE ADD CONSTRAINT FK_TAX_RATE_JURISDICTION
    FOREIGN KEY (JURISDICTION_CD) REFERENCES WWI_FIN.TAX_JURISDICTION (JURISDICTION_CD)
/

CREATE INDEX WWI_FIN.IX_TAX_RATE_LOOKUP
    ON WWI_FIN.TAX_RATE (JURISDICTION_CD, EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
    TABLESPACE WWI_FIN_IDX
/

CREATE INDEX WWI_FIN.IX_TAX_RATE_CODE_ACTIVE
    ON WWI_FIN.TAX_RATE (TAX_CODE_CD, ACTIVE_FLG) TABLESPACE WWI_FIN_IDX
/
