/* =====================================================================
 * Object       : TABLE WWI_PROC.PO_RECEIPT_HDR
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 48
 * Depends on   : WWI_PROC.PURCHASE_ORDER_HDR, WWI_MDM.SUPP_MASTER
 * Called by    : PKG_RECEIPTS, V_RECEIPT_EXTRACT, SSIS EXT_ORA_ReceiptHdr
 *
 * Goods receipt header, one per delivery event per warehouse. A receipt can
 * span more than one PO, which is why the PO reference lives on the line and
 * not here. RECEIPT_METHOD_CD distinguishes the scanner-driven receipts from
 * the ones keyed by hand the morning after.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_PO_RECEIPT_HDR
    START WITH 2000001 INCREMENT BY 1 NOCACHE NOCYCLE ORDER
/

CREATE TABLE WWI_PROC.PO_RECEIPT_HDR
(
    RECEIPT_ID              NUMBER(12)      NOT NULL,
    RECEIPT_NBR             VARCHAR2(16)    NOT NULL,
    RECEIPT_DT              DATE            DEFAULT SYSDATE NOT NULL,
    WAREHOUSE_CD            VARCHAR2(8)     NOT NULL,
    REGION_CD               VARCHAR2(4)     NOT NULL,
    SUPP_ID                 NUMBER(12)      NOT NULL,
    PACKING_SLIP_NBR        VARCHAR2(30),
    CARRIER_CD              VARCHAR2(8),
    TRACKING_NBR            VARCHAR2(40),
    CONTAINER_NBR           VARCHAR2(20),
    RECEIPT_METHOD_CD       VARCHAR2(4)     DEFAULT 'SCAN' NOT NULL,
    RECEIVED_BY_CD          VARCHAR2(8)     NOT NULL,
    INSPECTION_STATUS_CD    VARCHAR2(4)     DEFAULT 'NA' NOT NULL,
    INSPECTED_BY_CD         VARCHAR2(8),
    INSPECTED_DT            DATE,
    TEMPERATURE_C           NUMBER(5,2),
    COLD_CHAIN_BREACH_FLG   VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CUSTOMS_ENTRY_NBR       VARCHAR2(30),
    CUSTOMS_CLEARED_DT      DATE,
    RECEIPT_STATUS_CD       VARCHAR2(4)     DEFAULT 'OPEN' NOT NULL,
    REVERSED_FLG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    REVERSAL_REASON_CD      VARCHAR2(4),
    DOCK_NOTES_TXT          VARCHAR2(1000),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_PO_RECEIPT_HDR PRIMARY KEY (RECEIPT_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_PO_RECEIPT_NBR UNIQUE (RECEIPT_NBR) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_RCPT_HDR_METHOD CHECK (RECEIPT_METHOD_CD IN ('SCAN', 'MAN', 'EDI', 'ASN')),
    CONSTRAINT CK_RCPT_HDR_REGION CHECK (REGION_CD IN ('NA', 'EU', 'APAC')),
    CONSTRAINT CK_RCPT_HDR_INSPECT CHECK (
        INSPECTION_STATUS_CD IN ('NA', 'PEND', 'PASS', 'FAIL', 'PART')),
    CONSTRAINT CK_RCPT_HDR_STATUS CHECK (RECEIPT_STATUS_CD IN ('OPEN', 'CONF', 'REVS')),
    CONSTRAINT CK_RCPT_HDR_FLAGS CHECK (
        COLD_CHAIN_BREACH_FLG IN ('Y', 'N') AND REVERSED_FLG IN ('Y', 'N')),
    CONSTRAINT CK_RCPT_HDR_REVERSAL CHECK (
        REVERSED_FLG = 'N' OR REVERSAL_REASON_CD IS NOT NULL)
)
TABLESPACE WWI_DATA
PCTFREE 10
/

ALTER TABLE WWI_PROC.PO_RECEIPT_HDR ADD CONSTRAINT FK_RCPT_HDR_SUPP
    FOREIGN KEY (SUPP_ID) REFERENCES WWI_MDM.SUPP_MASTER (SUPP_ID)
/

CREATE INDEX WWI_PROC.IX_RCPT_HDR_DT
    ON WWI_PROC.PO_RECEIPT_HDR (RECEIPT_DT, WAREHOUSE_CD) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_PROC.IX_RCPT_HDR_SUPP
    ON WWI_PROC.PO_RECEIPT_HDR (SUPP_ID, RECEIPT_DT) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_PROC.IX_RCPT_HDR_SLIP
    ON WWI_PROC.PO_RECEIPT_HDR (UPPER(PACKING_SLIP_NBR)) TABLESPACE WWI_IDX
/
