/* =====================================================================
 * Object       : TABLE WWI_PROC.PURCHASE_ORDER_LINE
 * Schema       : WWI_PROC (Oracle ERP - WWIGERP)
 * Deploy order : 46
 * Depends on   : WWI_PROC.PURCHASE_ORDER_HDR, WWI_MDM.PRODUCT_MASTER
 * Called by    : PKG_PURCHASE_ORDER, V_PO_LINE_EXTRACT, V_OPEN_PO_BALANCE
 *
 * PO lines, range partitioned on ORDER_DT which is denormalised down from the
 * header so the partition key is local to the line. Received and billed
 * quantities are maintained on the line by the receipt and invoice packages;
 * they drift from the child tables when a receipt is corrected outside
 * PKG_RECEIPTS, which is the single most common data-quality issue downstream.
 * ===================================================================== */

CREATE SEQUENCE WWI_PROC.SEQ_PURCHASE_ORDER_LINE
    START WITH 9000001 INCREMENT BY 1 CACHE 200 NOCYCLE
/

CREATE TABLE WWI_PROC.PURCHASE_ORDER_LINE
(
    PO_LINE_ID              NUMBER(12)      NOT NULL,
    PO_ID                   NUMBER(12)      NOT NULL,
    LINE_NBR                NUMBER(5)       NOT NULL,
    ORDER_DT                DATE            NOT NULL,
    PRODUCT_ID              NUMBER(12),
    SUPPLIER_ITEM_CD        VARCHAR2(30),
    ITEM_DESC_TXT           VARCHAR2(400),
    ORDER_QTY               NUMBER(14,4)    NOT NULL,
    UOM_CD                  VARCHAR2(4)     NOT NULL,
    UNIT_PRICE              NUMBER(15,5)    NOT NULL,
    LINE_AMT                NUMBER(15,5)    NOT NULL,
    DISCOUNT_PCT            NUMBER(5,2)     DEFAULT 0 NOT NULL,
    LINE_CURR_CD            VARCHAR2(3)     NOT NULL,
    TAX_CODE_CD             VARCHAR2(12),
    TAX_RATE_PCT            NUMBER(7,5),
    TAX_AMT                 NUMBER(15,5)    DEFAULT 0 NOT NULL,
    RECEIVED_QTY            NUMBER(14,4)    DEFAULT 0 NOT NULL,
    RETURNED_QTY            NUMBER(14,4)    DEFAULT 0 NOT NULL,
    BILLED_QTY              NUMBER(14,4)    DEFAULT 0 NOT NULL,
    CANCELLED_QTY           NUMBER(14,4)    DEFAULT 0 NOT NULL,
    NEED_BY_DT              DATE,
    PROMISED_DT             DATE,
    LAST_RECEIPT_DT         DATE,
    LINE_STATUS_CD          VARCHAR2(4)     DEFAULT 'OPEN' NOT NULL,
    CLOSE_REASON_CD         VARCHAR2(4),
    GL_ACCOUNT_CD           VARCHAR2(20),
    COST_CENTER_CD          VARCHAR2(10),
    PROJECT_CD              VARCHAR2(12),
    MATCH_TYPE_CD           VARCHAR2(2)     DEFAULT '3W' NOT NULL,
    INSPECTION_REQ_FLG      VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    LINE_NOTES_TXT          VARCHAR2(1000),
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT CK_PO_LINE_QTY CHECK (ORDER_QTY > 0),
    CONSTRAINT CK_PO_LINE_STATUS CHECK (
        LINE_STATUS_CD IN ('OPEN', 'PART', 'RECV', 'CLSD', 'CANC')),
    CONSTRAINT CK_PO_LINE_MATCH CHECK (MATCH_TYPE_CD IN ('2W', '3W', '4W')),
    CONSTRAINT CK_PO_LINE_INSPECT CHECK (INSPECTION_REQ_FLG IN ('Y', 'N')),
    CONSTRAINT CK_PO_LINE_DISCOUNT CHECK (DISCOUNT_PCT BETWEEN 0 AND 100)
)
PARTITION BY RANGE (ORDER_DT)
(
    PARTITION PO_LINE_2019 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_LINE_2020 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_LINE_2021 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_LINE_2022 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_LINE_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_HIST_DATA,
    PARTITION PO_LINE_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')) TABLESPACE WWI_DATA,
    PARTITION PO_LINE_PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE WWI_DATA
)
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_LINE ADD CONSTRAINT PK_PURCHASE_ORDER_LINE
    PRIMARY KEY (PO_LINE_ID) USING INDEX TABLESPACE WWI_HIST_IDX
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_LINE ADD CONSTRAINT UK_PO_LINE_NBR
    UNIQUE (PO_ID, LINE_NBR) USING INDEX TABLESPACE WWI_HIST_IDX
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_LINE ADD CONSTRAINT FK_PO_LINE_HDR
    FOREIGN KEY (PO_ID) REFERENCES WWI_PROC.PURCHASE_ORDER_HDR (PO_ID)
/

ALTER TABLE WWI_PROC.PURCHASE_ORDER_LINE ADD CONSTRAINT FK_PO_LINE_PRODUCT
    FOREIGN KEY (PRODUCT_ID) REFERENCES WWI_MDM.PRODUCT_MASTER (PRODUCT_ID)
/

CREATE INDEX WWI_PROC.IX_PO_LINE_PRODUCT
    ON WWI_PROC.PURCHASE_ORDER_LINE (PRODUCT_ID, ORDER_DT) LOCAL TABLESPACE WWI_HIST_IDX
/

CREATE INDEX WWI_PROC.IX_PO_LINE_OPEN
    ON WWI_PROC.PURCHASE_ORDER_LINE (LINE_STATUS_CD, (ORDER_QTY - RECEIVED_QTY))
    TABLESPACE WWI_HIST_IDX
/

COMMENT ON COLUMN WWI_PROC.PURCHASE_ORDER_LINE.ORDER_DT IS
    'Copied from the header purely to give the line table a local partition key.'
/
