/* =====================================================================
 * Object       : TABLE WWI_MDM.CUST_CLASSIFICATION
 * Schema       : WWI_MDM (Oracle ERP - WWIGERP)
 * Deploy order : 23
 * Depends on   : WWI_MDM.CUST_MASTER
 * Called by    : PKG_CUSTOMER_MASTER, DIM_Load_Customer via the staging estate
 *
 * Industry and regulatory classifications. Three schemes coexist: SIC (kept
 * because two NA reports still group by it), NAICS (the current standard) and
 * the internal WWI scheme. Rows are effective-dated but never deleted, so the
 * extract has to pick the latest EFFECTIVE_DT per scheme.
 * ===================================================================== */

CREATE SEQUENCE WWI_MDM.SEQ_CUST_CLASSIFICATION
    START WITH 300001 INCREMENT BY 1 CACHE 20 NOCYCLE
/

CREATE TABLE WWI_MDM.CUST_CLASSIFICATION
(
    CUST_CLASS_ID           NUMBER(12)      NOT NULL,
    CUST_ID                 NUMBER(12)      NOT NULL,
    CLASS_SCHEME_CD         VARCHAR2(8)     NOT NULL,
    CLASS_CD                VARCHAR2(12)    NOT NULL,
    CLASS_DESC              VARCHAR2(120),
    CLASS_LEVEL_NBR         NUMBER(2)       DEFAULT 1 NOT NULL,
    ASSIGNED_BY_CD          VARCHAR2(8),
    ASSIGN_METHOD_CD        VARCHAR2(4)     DEFAULT 'MAN' NOT NULL,
    CONFIDENCE_PCT          NUMBER(5,2),
    REGULATED_FLG           VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    EFFECTIVE_DT            DATE            DEFAULT SYSDATE NOT NULL,
    EXPIRY_DT               DATE,
    SOURCE_SYS              VARCHAR2(12)    DEFAULT 'ORA_ERP' NOT NULL,
    CREATED_BY              VARCHAR2(30)    DEFAULT USER NOT NULL,
    CREATED_DT              DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY              VARCHAR2(30),
    UPDATED_DT              DATE,
    CONSTRAINT PK_CUST_CLASSIFICATION PRIMARY KEY (CUST_CLASS_ID) USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT UK_CUST_CLASS_SCHEME UNIQUE (CUST_ID, CLASS_SCHEME_CD, CLASS_CD, EFFECTIVE_DT)
        USING INDEX TABLESPACE WWI_IDX,
    CONSTRAINT CK_CUST_CLASS_SCHEME CHECK (CLASS_SCHEME_CD IN ('SIC', 'NAICS', 'WWI', 'UNSPSC')),
    CONSTRAINT CK_CUST_CLASS_METHOD CHECK (ASSIGN_METHOD_CD IN ('MAN', 'AUTO', 'BULK', 'MIGR')),
    CONSTRAINT CK_CUST_CLASS_CONF CHECK (CONFIDENCE_PCT IS NULL OR CONFIDENCE_PCT BETWEEN 0 AND 100),
    CONSTRAINT CK_CUST_CLASS_REG CHECK (REGULATED_FLG IN ('Y', 'N'))
)
TABLESPACE WWI_DATA
/

ALTER TABLE WWI_MDM.CUST_CLASSIFICATION ADD CONSTRAINT FK_CUST_CLASS_CUST
    FOREIGN KEY (CUST_ID) REFERENCES WWI_MDM.CUST_MASTER (CUST_ID)
/

CREATE INDEX WWI_MDM.IX_CUST_CLASS_LOOKUP
    ON WWI_MDM.CUST_CLASSIFICATION (CLASS_SCHEME_CD, CLASS_CD) TABLESPACE WWI_IDX
/

CREATE INDEX WWI_MDM.IX_CUST_CLASS_CURRENT
    ON WWI_MDM.CUST_CLASSIFICATION (CUST_ID, CLASS_SCHEME_CD, EFFECTIVE_DT DESC) TABLESPACE WWI_IDX
/
