"""Steward-maintained grids copied verbatim from sqlserver/reference/ref.usp_Load*.sql.

Every grid is a list of tuples plus a column list so it can be turned into a DataFrame with
``spark.createDataFrame(rows, columns)``. The values are the legacy business content; changing
them is a steward decision, not a code change.
"""

MAINTAINED_BY = "REF_Load"

# ref.usp_LoadRegion
REGION_COLUMNS = [
    "RegionCode", "RegionName", "TaxRegimeCode", "DefaultCurrencyCode", "FiscalCalendarCode",
    "FiscalYearStartMonth", "AddressRuleSetCode", "WeightUomCode", "ConsentModelCode",
    "DefaultRetentionMonths", "DateFormatHint", "DecimalSeparator",
]
REGIONS = [
    ("NA", "North America", "SALESTAX", "USD", "NA_CAL", 7, "NA_USPS", "LB", "OPT_OUT", 84, "MM/DD/YYYY", "."),
    ("EU", "Europe", "VAT", "EUR", "EU_APR", 1, "EU_COUNTRY", "KG", "OPT_IN", 120, "DD/MM/YYYY", ","),
    ("APAC", "Asia Pacific", "GST", "AUD", "APAC_JUL", 4, "APAC_LOCAL", "KG", "OPT_IN", 60, "YYYY-MM-DD", "."),
]

# ref.usp_LoadStatusCode
STATUS_CODE_COLUMNS = [
    "StatusDomainCode", "ConformedStatusCode", "ConformedStatusName", "StatusGroupCode",
    "SortOrder", "IsTerminalStatus",
]
STATUS_CODES = [
    ("ORDER", "DRAFT", "Draft", "OPEN", 10, False),
    ("ORDER", "OPEN", "Open", "OPEN", 20, False),
    ("ORDER", "BACKORDER", "Backordered", "OPEN", 30, False),
    ("ORDER", "PICKING", "Being picked", "OPEN", 40, False),
    ("ORDER", "HOLD", "On hold", "EXCEPTION", 50, False),
    ("ORDER", "SHIPPED", "Shipped", "CLOSED", 60, False),
    ("ORDER", "INVOICED", "Invoiced", "CLOSED", 70, True),
    ("ORDER", "CANCELLED", "Cancelled", "CANCELLED", 80, True),
    ("ORDER", "UNKNOWN", "Unknown order status", "EXCEPTION", 999, False),
    ("INVOICE", "DRAFT", "Draft", "OPEN", 10, False),
    ("INVOICE", "ISSUED", "Issued", "OPEN", 20, False),
    ("INVOICE", "PARTPAID", "Partially paid", "OPEN", 30, False),
    ("INVOICE", "PAID", "Paid", "CLOSED", 40, True),
    ("INVOICE", "CREDITED", "Credited", "CLOSED", 50, True),
    ("INVOICE", "DISPUTED", "Disputed", "EXCEPTION", 60, False),
    ("INVOICE", "WRITEOFF", "Written off", "CLOSED", 70, True),
    ("INVOICE", "CANCELLED", "Cancelled", "CANCELLED", 80, True),
    ("INVOICE", "UNKNOWN", "Unknown invoice status", "EXCEPTION", 999, False),
    ("SHIPMENT", "PLANNED", "Planned", "OPEN", 10, False),
    ("SHIPMENT", "PICKED", "Picked", "OPEN", 20, False),
    ("SHIPMENT", "INTRANSIT", "In transit", "OPEN", 30, False),
    ("SHIPMENT", "DELIVERED", "Delivered", "CLOSED", 40, True),
    ("SHIPMENT", "FAILED", "Delivery failed", "EXCEPTION", 50, False),
    ("SHIPMENT", "RETURNED", "Returned to sender", "CLOSED", 60, True),
    ("SHIPMENT", "CANCELLED", "Cancelled", "CANCELLED", 70, True),
    ("SHIPMENT", "UNKNOWN", "Unknown shipment status", "EXCEPTION", 999, False),
    ("PO", "DRAFT", "Draft", "OPEN", 10, False),
    ("PO", "APPROVED", "Approved", "OPEN", 20, False),
    ("PO", "PARTRECV", "Partially received", "OPEN", 30, False),
    ("PO", "RECEIVED", "Fully received", "CLOSED", 40, False),
    ("PO", "CLOSED", "Closed", "CLOSED", 50, True),
    ("PO", "CANCELLED", "Cancelled", "CANCELLED", 60, True),
    ("PO", "UNKNOWN", "Unknown purchase order status", "EXCEPTION", 999, False),
    ("SUPPLIER", "ACTIVE", "Active", "OPEN", 10, False),
    ("SUPPLIER", "HOLD", "On hold", "EXCEPTION", 20, False),
    ("SUPPLIER", "PENDING", "Pending approval", "OPEN", 30, False),
    ("SUPPLIER", "INACTIVE", "Inactive", "CLOSED", 40, False),
    ("SUPPLIER", "BLOCKED", "Blocked", "EXCEPTION", 50, True),
    ("SUPPLIER", "UNKNOWN", "Unknown supplier status", "EXCEPTION", 999, False),
    ("CUSTOMER", "ACTIVE", "Active", "OPEN", 10, False),
    ("CUSTOMER", "HOLD", "Credit hold", "EXCEPTION", 20, False),
    ("CUSTOMER", "PROSPECT", "Prospect", "OPEN", 30, False),
    ("CUSTOMER", "INACTIVE", "Inactive", "CLOSED", 40, False),
    ("CUSTOMER", "CLOSED", "Account closed", "CLOSED", 50, True),
    ("CUSTOMER", "UNKNOWN", "Unknown customer status", "EXCEPTION", 999, False),
]

# ref.usp_LoadReasonCode
REASON_CODE_COLUMNS = [
    "ReasonDomainCode", "ConformedReasonCode", "ConformedReasonName", "ReasonGroupCode",
    "IsCustomerFault", "IsSupplierFault", "RequiresApproval",
]
REASON_CODES = [
    ("RETURN", "DAMAGED", "Damaged in transit", "QUALITY", False, False, False),
    ("RETURN", "DEFECTIVE", "Defective on arrival", "QUALITY", False, True, False),
    ("RETURN", "WRONGITEM", "Wrong item shipped", "FULFILMENT", False, False, False),
    ("RETURN", "OVERSHIP", "Over-shipment", "FULFILMENT", False, False, False),
    ("RETURN", "NOTNEEDED", "No longer required", "COMMERCIAL", True, False, False),
    ("RETURN", "LATE", "Delivered too late", "FULFILMENT", False, False, False),
    ("RETURN", "EXPIRED", "Past shelf life on arrival", "QUALITY", False, True, True),
    ("RETURN", "UNKNOWN", "Unknown return reason", "EXCEPTION", None, None, True),
    ("CREDIT", "PRICEERR", "Pricing error", "BILLING", False, False, True),
    ("CREDIT", "GOODWILL", "Goodwill gesture", "COMMERCIAL", False, False, True),
    ("CREDIT", "RETURNCR", "Credit against a return", "RETURNS", None, None, False),
    ("CREDIT", "SHORTSHIP", "Short shipment", "FULFILMENT", False, False, False),
    ("CREDIT", "TAXCORR", "Tax correction", "BILLING", False, False, True),
    ("CREDIT", "UNKNOWN", "Unknown credit reason", "EXCEPTION", None, None, True),
    ("HOLD", "CREDIT", "Credit limit exceeded", "FINANCE", True, False, True),
    ("HOLD", "PRICE", "Price awaiting approval", "COMMERCIAL", False, False, True),
    ("HOLD", "QUALITY", "Quality inspection", "QUALITY", False, True, False),
    ("HOLD", "COMPLIANCE", "Compliance review", "COMPLIANCE", None, None, True),
    ("HOLD", "UNKNOWN", "Unknown hold reason", "EXCEPTION", None, None, True),
    ("ADJUSTMENT", "CYCLECOUNT", "Cycle count correction", "INVENTORY", False, False, False),
    ("ADJUSTMENT", "SHRINKAGE", "Shrinkage", "INVENTORY", False, False, True),
    ("ADJUSTMENT", "DAMAGE", "Damaged in the warehouse", "INVENTORY", False, False, False),
    ("ADJUSTMENT", "REVALUE", "Stock revaluation", "FINANCE", False, False, True),
    ("ADJUSTMENT", "UNKNOWN", "Unknown adjustment reason", "EXCEPTION", None, None, True),
    ("REJECT", "QUALITY", "Failed goods-in inspection", "QUALITY", False, True, False),
    ("REJECT", "QUANTITY", "Quantity does not match the order", "FULFILMENT", False, True, False),
    ("REJECT", "DOCUMENT", "Paperwork missing or wrong", "COMPLIANCE", False, True, False),
    ("REJECT", "UNKNOWN", "Unknown rejection reason", "EXCEPTION", None, None, True),
]

# ref.usp_LoadUnitOfMeasure
UOM_COLUMNS = ["UomCode", "UomName", "UomClassCode", "BaseUomCode", "IsBaseUom", "DecimalPrecision"]
UNITS_OF_MEASURE = [
    ("EA", "Each", "COUNT", "EA", True, 0),
    ("PKT", "Packet", "COUNT", "EA", False, 0),
    ("CS", "Case", "COUNT", "EA", False, 0),
    ("PLT", "Pallet", "COUNT", "EA", False, 0),
    ("DOZ", "Dozen", "COUNT", "EA", False, 0),
    ("KG", "Kilogram", "WEIGHT", "KG", True, 3),
    ("G", "Gram", "WEIGHT", "KG", False, 3),
    ("LB", "Pound", "WEIGHT", "KG", False, 4),
    ("OZ", "Ounce", "WEIGHT", "KG", False, 4),
    ("L", "Litre", "VOLUME", "L", True, 3),
    ("ML", "Millilitre", "VOLUME", "L", False, 1),
    ("GAL", "US Gallon", "VOLUME", "L", False, 4),
    ("M", "Metre", "LENGTH", "M", True, 3),
    ("CM", "Centimetre", "LENGTH", "M", False, 1),
    ("IN", "Inch", "LENGTH", "M", False, 4),
    ("FT", "Foot", "LENGTH", "M", False, 4),
]

# ref.usp_LoadUomConversion (standard, non item-specific factors)
UOM_CONVERSION_COLUMNS = ["FromUomCode", "ToUomCode", "ConversionFactor"]
UOM_CONVERSIONS = [
    ("G", "KG", "0.001"), ("KG", "G", "1000"),
    ("LB", "KG", "0.45359237"), ("KG", "LB", "2.20462262"),
    ("OZ", "KG", "0.02834952"), ("KG", "OZ", "35.27396195"),
    ("ML", "L", "0.001"), ("L", "ML", "1000"),
    ("GAL", "L", "3.78541178"), ("L", "GAL", "0.26417205"),
    ("CM", "M", "0.01"), ("M", "CM", "100"),
    ("IN", "M", "0.0254"), ("M", "IN", "39.37007874"),
    ("FT", "M", "0.3048"), ("M", "FT", "3.2808399"),
    ("DOZ", "EA", "12"), ("EA", "DOZ", "0.08333333"),
]

# ref.usp_LoadPostalFormatRule (country rules; region fallbacks are generated at priority 900)
POSTAL_RULE_COLUMNS = [
    "CountryCode", "RuleSetCode", "RulePriority", "StripCharacters", "UpperCaseFlag", "FormatMask",
    "MinimumLength", "MaximumLength", "TruncateToLength", "InsertSeparatorAt", "SeparatorCharacter",
    "RuleNote",
]
POSTAL_RULES = [
    ("US", "NA_USPS", 100, " -", True, "99999", 5, 10, 5, None, None,
     "ZIP5 only; the +4 extension is dropped so the ERP and the OLTP database agree."),
    ("CA", "NA_USPS", 110, "- ", True, "A9A 9A9", 6, 7, None, 3, " ",
     "Six characters with one space inserted after the forward sortation area."),
    ("GB", "EU_COUNTRY", 200, " ", True, "AA9A 9AA", 5, 8, None, None, " ",
     "Variable outward code; the inward code is always the last three characters."),
    ("IE", "EU_COUNTRY", 210, " ", True, "A99 AAAA", 7, 8, None, 3, " ",
     "Eircode; rows created before 2015 have no postal code at all and are allowed through."),
    ("NL", "EU_COUNTRY", 220, " ", True, "9999AA", 6, 7, None, None, None,
     "Four digits and two letters, upper-cased, no separator."),
    ("DE", "EU_COUNTRY", 230, " -", False, "99999", 5, 5, None, None, None, "Five digits."),
    ("FR", "EU_COUNTRY", 240, " -", False, "99999", 5, 5, None, None, None,
     "Five digits; the leading zero is significant and must not be trimmed."),
    ("IT", "EU_COUNTRY", 250, " -", False, "99999", 5, 5, None, None, None, "Five digits."),
    ("ES", "EU_COUNTRY", 260, " -", False, "99999", 5, 5, None, None, None,
     "Five digits; the first two identify the province."),
    ("PL", "EU_COUNTRY", 270, " ", False, "99-999", 5, 6, None, 2, "-",
     "Two digits, a hyphen, three digits."),
    ("JP", "APAC_LOCAL", 300, " ", False, "999-9999", 7, 8, None, 3, "-",
     "Seven digits with a hyphen after the third."),
    ("AU", "APAC_LOCAL", 310, " -", False, "9999", 4, 4, None, None, None, "Four digits."),
    ("NZ", "APAC_LOCAL", 320, " -", False, "9999", 4, 4, None, None, None, "Four digits."),
    ("SG", "APAC_LOCAL", 330, " -", False, "999999", 6, 6, None, None, None, "Six digits."),
    ("CN", "APAC_LOCAL", 340, " -", False, "999999", 6, 6, None, None, None, "Six digits."),
    ("IN", "APAC_LOCAL", 350, " -", False, "999999", 6, 6, None, None, None,
     "Six digit PIN; older rows carry the pre-1972 six digit code unchanged."),
    ("HK", "APAC_LOCAL", 360, " -", True, None, None, None, None, None, None,
     "Hong Kong has no postal code; the column is expected to be empty."),
]
REGION_FALLBACK_PRIORITY = 900
REGION_FALLBACK_NOTE = (
    "Region fallback: no country rule has been written, so the value is only trimmed and upper-cased."
)

# ref.usp_LoadCountry: EU membership history
EU_MEMBERSHIP_COLUMNS = ["CountryCode", "EuAccessionDate", "EuExitDate"]
EU_MEMBERSHIP = [
    ("AT", "1995-01-01", None), ("BE", "1958-01-01", None), ("DE", "1958-01-01", None),
    ("DK", "1973-01-01", None), ("ES", "1986-01-01", None), ("FI", "1995-01-01", None),
    ("FR", "1958-01-01", None), ("IE", "1973-01-01", None), ("IT", "1958-01-01", None),
    ("NL", "1958-01-01", None), ("PL", "2004-05-01", None), ("PT", "1986-01-01", None),
    ("SE", "1995-01-01", None), ("GB", "1973-01-01", "2020-01-31"),
]

# ref.usp_LoadCodeCrosswalk steward grid (CodeDomainCode, SourceSystemCode, SourceCodeValue,
# SourceCodeDescription, ConformedCodeValue, RegionCode, IsDefaultForConformed)
CODE_CROSSWALK_COLUMNS = [
    "CodeDomainCode", "SourceSystemCode", "SourceCodeValue", "SourceCodeDescription",
    "ConformedCodeValue", "RegionCode", "IsDefaultForConformed",
]
CODE_CROSSWALK = [
    ("ORDER", "ORA_ERP", "ENT", "Entered", "OPEN", None, True),
    ("ORDER", "ORA_ERP", "BOOK", "Booked", "OPEN", None, False),
    ("ORDER", "ORA_ERP", "BO", "Backordered", "BACKORDER", None, True),
    ("ORDER", "ORA_ERP", "HOLD", "On hold", "HOLD", None, True),
    ("ORDER", "ORA_ERP", "SHIP", "Shipped", "SHIPPED", None, True),
    ("ORDER", "ORA_ERP", "INV", "Invoiced", "INVOICED", None, True),
    ("ORDER", "ORA_ERP", "CANC", "Cancelled", "CANCELLED", None, True),
    ("ORDER", "WWI_OLTP", "UNDER DEVELOPMENT", "Under development", "DRAFT", None, True),
    ("ORDER", "WWI_OLTP", "OPEN", "Open", "OPEN", None, False),
    ("ORDER", "WWI_OLTP", "BACKORDER", "Backorder", "BACKORDER", None, False),
    ("ORDER", "WWI_OLTP", "PICKING", "Being picked", "PICKING", None, True),
    ("ORDER", "WWI_OLTP", "PICKED", "Picked", "PICKING", None, False),
    ("ORDER", "WWI_OLTP", "INVOICED", "Invoiced", "INVOICED", None, False),
    ("ORDER", "WWI_OLTP", "CANCELLED", "Cancelled", "CANCELLED", None, False),
    ("INVOICE", "ORA_ERP", "DRAFT", "Draft", "DRAFT", None, True),
    ("INVOICE", "ORA_ERP", "APPR", "Approved and issued", "ISSUED", None, True),
    ("INVOICE", "ORA_ERP", "PPAY", "Partially paid", "PARTPAID", None, True),
    ("INVOICE", "ORA_ERP", "PAID", "Paid in full", "PAID", None, True),
    ("INVOICE", "ORA_ERP", "DISP", "In dispute", "DISPUTED", None, True),
    ("INVOICE", "ORA_ERP", "WOFF", "Written off", "WRITEOFF", None, True),
    ("INVOICE", "ORA_ERP", "CANC", "Cancelled", "CANCELLED", None, True),
    ("INVOICE", "WWI_OLTP", "ISSUED", "Issued", "ISSUED", None, False),
    ("INVOICE", "WWI_OLTP", "PART PAID", "Part paid", "PARTPAID", None, False),
    ("INVOICE", "WWI_OLTP", "PAID", "Paid", "PAID", None, False),
    ("INVOICE", "WWI_OLTP", "CREDITED", "Credited", "CREDITED", None, True),
    ("SHIPMENT", "WWI_OLTP", "PLANNED", "Planned", "PLANNED", None, True),
    ("SHIPMENT", "WWI_OLTP", "IN TRANSIT", "In transit", "INTRANSIT", None, True),
    ("SHIPMENT", "WWI_OLTP", "DELIVERED", "Delivered", "DELIVERED", None, True),
    ("SHIPMENT", "WWI_OLTP", "FAILED", "Delivery failed", "FAILED", None, True),
    ("SHIPMENT", "WWI_OLTP", "RTS", "Returned to sender", "RETURNED", None, True),
    ("SHIPMENT", "ORA_ERP", "DLV", "Delivered", "DELIVERED", None, False),
    ("PO", "ORA_ERP", "INCOMPLETE", "Incomplete", "DRAFT", None, True),
    ("PO", "ORA_ERP", "APPR", "Approved", "APPROVED", None, True),
    ("PO", "ORA_ERP", "PREC", "Partially received", "PARTRECV", None, True),
    ("PO", "ORA_ERP", "RECV", "Received", "RECEIVED", None, True),
    ("PO", "ORA_ERP", "CLSD", "Closed", "CLOSED", None, True),
    ("PO", "ORA_ERP", "CANC", "Cancelled", "CANCELLED", None, True),
    ("SUPPLIER", "ORA_ERP", "A", "Active", "ACTIVE", None, True),
    ("SUPPLIER", "ORA_ERP", "I", "Inactive", "INACTIVE", None, True),
    ("SUPPLIER", "ORA_ERP", "H", "On hold", "HOLD", None, True),
    ("SUPPLIER", "ORA_ERP", "P", "Pending approval", "PENDING", None, True),
    ("SUPPLIER", "ORA_ERP", "X", "Blocked", "BLOCKED", None, True),
    ("CUSTOMER", "ORA_ERP", "A", "Active", "ACTIVE", None, True),
    ("CUSTOMER", "ORA_ERP", "I", "Inactive", "INACTIVE", None, True),
    ("CUSTOMER", "ORA_ERP", "H", "Credit hold", "HOLD", None, True),
    ("CUSTOMER", "ORA_ERP", "P", "Prospect", "PROSPECT", None, True),
    ("CUSTOMER", "ORA_ERP", "X", "Account closed", "CLOSED", None, True),
    ("RETURN", "WWI_OLTP", "DAMAGED", "Damaged", "DAMAGED", None, True),
    ("RETURN", "WWI_OLTP", "FAULTY", "Faulty", "DEFECTIVE", None, True),
    ("RETURN", "WWI_OLTP", "WRONG ITEM", "Wrong item", "WRONGITEM", None, True),
    ("RETURN", "WWI_OLTP", "TOO MANY", "Too many delivered", "OVERSHIP", None, True),
    ("RETURN", "WWI_OLTP", "NOT REQUIRED", "No longer required", "NOTNEEDED", None, True),
    ("RETURN", "WWI_OLTP", "LATE", "Arrived late", "LATE", None, True),
    ("RETURN", "ORA_ERP", "RTN-DMG", "Damaged on receipt", "DAMAGED", None, False),
    ("RETURN", "ORA_ERP", "RTN-QLY", "Quality failure", "DEFECTIVE", None, False),
    ("CREDIT", "WWI_OLTP", "PRICE", "Price adjustment", "PRICEERR", None, True),
    ("CREDIT", "WWI_OLTP", "GOODWILL", "Goodwill", "GOODWILL", None, True),
    ("CREDIT", "WWI_OLTP", "RETURN", "Against a return", "RETURNCR", None, True),
    ("CREDIT", "WWI_OLTP", "SHORT", "Short delivery", "SHORTSHIP", None, True),
    ("CREDIT", "ORA_ERP", "CM-TAX", "Tax correction", "TAXCORR", None, True),
    ("HOLD", "ORA_ERP", "CRED", "Credit limit", "CREDIT", None, True),
    ("HOLD", "ORA_ERP", "PRIC", "Price approval", "PRICE", None, True),
    ("HOLD", "ORA_ERP", "QUAL", "Quality inspection", "QUALITY", None, True),
    ("HOLD", "ORA_ERP", "COMP", "Compliance review", "COMPLIANCE", None, True),
    ("ADJUSTMENT", "WWI_OLTP", "STOCKTAKE", "Stocktake correction", "CYCLECOUNT", None, True),
    ("ADJUSTMENT", "WWI_OLTP", "SHRINK", "Shrinkage", "SHRINKAGE", None, True),
    ("ADJUSTMENT", "WWI_OLTP", "DAMAGE", "Damaged in warehouse", "DAMAGE", None, True),
    ("ADJUSTMENT", "ORA_ERP", "REVAL", "Revaluation", "REVALUE", None, True),
    ("REJECT", "ORA_ERP", "REJ-QLY", "Failed inspection", "QUALITY", None, True),
    ("REJECT", "ORA_ERP", "REJ-QTY", "Quantity mismatch", "QUANTITY", None, True),
    ("REJECT", "ORA_ERP", "REJ-DOC", "Documentation", "DOCUMENT", None, True),
    ("REGION", "ORA_ERP", "AMER", "Americas", "NA", None, True),
    ("REGION", "ORA_ERP", "NA", "North America", "NA", None, False),
    ("REGION", "ORA_ERP", "EMEA", "Europe, Middle East and Africa", "EU", None, True),
    ("REGION", "ORA_ERP", "EU", "Europe", "EU", None, False),
    ("REGION", "ORA_ERP", "APJ", "Asia Pacific and Japan", "APAC", None, True),
    ("REGION", "ORA_ERP", "APAC", "Asia Pacific", "APAC", None, False),
    ("COUNTRY", "ORA_ERP", "USA", "United States (ISO3)", "US", None, True),
    ("COUNTRY", "ORA_ERP", "GBR", "United Kingdom (ISO3)", "GB", None, True),
    ("COUNTRY", "ORA_ERP", "UK", "United Kingdom (legacy)", "GB", None, False),
    ("COUNTRY", "ORA_ERP", "DEU", "Germany (ISO3)", "DE", None, True),
    ("COUNTRY", "ORA_ERP", "AUS", "Australia (ISO3)", "AU", None, True),
    ("COUNTRY", "ORA_ERP", "JPN", "Japan (ISO3)", "JP", None, True),
    ("CURRENCY", "WWI_OLTP", "US$", "US dollar", "USD", None, True),
    ("CURRENCY", "WWI_OLTP", "STG", "Pound sterling", "GBP", None, True),
    ("CURRENCY", "ORA_ERP", "DEM", "Deutsche mark (retired)", "EUR", None, False),
    ("UOM", "ORA_ERP", "EACH", "Each", "EA", None, True),
    ("UOM", "ORA_ERP", "CASE", "Case", "CS", None, True),
    ("UOM", "ORA_ERP", "PALLET", "Pallet", "PLT", None, True),
    ("UOM", "ORA_ERP", "KILO", "Kilogram", "KG", None, True),
    ("UOM", "ORA_ERP", "POUND", "Pound", "LB", "NA", True),
    ("UOM", "WWI_OLTP", "PACKET", "Packet", "PKT", None, True),
    ("UOM", "WWI_OLTP", "EACH", "Each", "EA", None, False),
    ("PAYMENT_METHOD", "ORA_ERP", "CHECK", "Check", "CHQ", "NA", True),
    ("PAYMENT_METHOD", "ORA_ERP", "CHEQUE", "Cheque", "CHQ", "EU", False),
    ("PAYMENT_METHOD", "ORA_ERP", "EFT", "Electronic funds transfer", "BANK", None, True),
    ("PAYMENT_METHOD", "ORA_ERP", "DD", "Direct debit", "DDEBIT", "EU", True),
    ("PAYMENT_METHOD", "WWI_OLTP", "CREDIT CARD", "Credit card", "CARD", None, True),
    ("PAYMENT_METHOD", "WWI_OLTP", "CASH", "Cash", "CASH", None, True),
    ("PAYMENT_TERMS", "ORA_ERP", "NET30", "Net 30 days", "NET30", None, True),
    ("PAYMENT_TERMS", "ORA_ERP", "NET60", "Net 60 days", "NET60", None, True),
    ("PAYMENT_TERMS", "ORA_ERP", "2/10NET30", "2 percent 10 days, net 30", "DISC210", None, True),
    ("PAYMENT_TERMS", "ORA_ERP", "EOM", "End of month", "EOM", "EU", True),
    ("PAYMENT_TERMS", "WWI_OLTP", "7 DAYS", "Seven days", "NET07", None, True),
    ("PAYMENT_TERMS", "WWI_OLTP", "30 DAYS", "Thirty days", "NET30", None, False),
    ("TRANSACTION_TYPE", "WWI_OLTP", "STOCK ISSUE", "Stock issue", "SALE", None, True),
    ("TRANSACTION_TYPE", "WWI_OLTP", "STOCK RECEIPT", "Stock receipt", "PURCH", None, True),
    ("TRANSACTION_TYPE", "WWI_OLTP", "ADJUSTMENT", "Adjustment", "ADJ", None, True),
    ("TRANSACTION_TYPE", "WWI_OLTP", "CUSTOMER RETURN", "Customer return", "RET", None, True),
    ("TRANSACTION_TYPE", "ORA_ERP", "MISC ISSUE", "Miscellaneous issue", "ADJ", None, False),
    ("SALES_CHANNEL", "WWI_OLTP", "DIR", "Direct sales force", "DIRECT", "NA", True),
    ("SALES_CHANNEL", "WWI_OLTP", "DIST", "Distributor", "PARTNER", "APAC", False),
    ("SALES_CHANNEL", "WWI_OLTP", "WEB", "Web store", "ONLINE", None, True),
    ("SALES_CHANNEL", "WWI_OLTP", "PHONE", "Telesales", "TELE", None, True),
    ("SALES_CHANNEL", "ORA_ERP", "WHSL", "Wholesale", "PARTNER", None, False),
    ("LOYALTY_TIER", "WWI_OLTP", "BRONZE", "Bronze", "TIER1", None, True),
    ("LOYALTY_TIER", "WWI_OLTP", "SILVER", "Silver", "TIER2", None, True),
    ("LOYALTY_TIER", "WWI_OLTP", "GOLD", "Gold", "TIER3", None, True),
    ("LOYALTY_TIER", "WWI_OLTP", "PLATINUM", "Platinum", "TIER4", None, True),
    ("CARRIER", "WWI_OLTP", "FEDEX", "FedEx", "FDX", "NA", True),
    ("CARRIER", "WWI_OLTP", "UPS", "United Parcel Service", "UPS", "NA", True),
    ("CARRIER", "WWI_OLTP", "DHL", "DHL", "DHL", "EU", True),
    ("CARRIER", "WWI_OLTP", "OWN FLEET", "Own fleet", "OWN", None, True),
    ("CARRIER", "ORA_ERP", "TOLL", "Toll Group", "TOLL", "APAC", True),
    ("COST_CENTER", "ORA_ERP", "1000", "Corporate", "CORP", None, True),
    ("COST_CENTER", "ORA_ERP", "2000", "Sales", "SALES", None, True),
    ("COST_CENTER", "ORA_ERP", "3000", "Warehouse operations", "OPS", None, True),
    ("COST_CENTER", "ORA_ERP", "4000", "Logistics", "LOGI", None, True),
    ("COST_CENTER", "ORA_ERP", "9999", "Suspense", "SUSP", None, True),
]

STATUS_DOMAINS = ("ORDER", "INVOICE", "SHIPMENT", "PO", "SUPPLIER", "CUSTOMER")
REASON_DOMAINS = ("RETURN", "CREDIT", "HOLD", "ADJUSTMENT", "REJECT")

# ref.usp_ReportUnmappedCodes: (CodeDomainCode, SourceSystemCode, legacy raw object, column)
UNMAPPED_CODE_SOURCES = [
    ("CUSTOMER", "ORA_ERP", "raw.OracleCustomerMaster", "CUST_STATUS_CD"),
    ("SUPPLIER", "ORA_ERP", "raw.OracleSupplierMaster", "SUPP_STATUS_CD"),
    ("PO", "ORA_ERP", "raw.OraclePurchaseOrderHdr", "PO_STATUS_CD"),
    ("INVOICE", "ORA_ERP", "raw.OracleApInvoiceHdr", "INVOICE_STATUS_CD"),
    ("HOLD", "ORA_ERP", "raw.OracleApInvoiceHdr", "HOLD_REASON_CD"),
    ("REJECT", "ORA_ERP", "raw.OracleReceiptLine", "REJECT_REASON_CD"),
    ("UOM", "ORA_ERP", "raw.OracleProductMaster", "BASE_UOM_CD"),
    ("REGION", "ORA_ERP", "raw.OracleGeography", "REGION_CD"),
    ("ORDER", "WWI_OLTP", "raw.SqlOrder", "OrderStatusCode"),
    ("SHIPMENT", "WWI_OLTP", "raw.SqlShipment", "ShipmentStatusCode"),
    ("RETURN", "WWI_OLTP", "raw.SqlReturnLine", "ReturnReasonCode"),
    ("CREDIT", "WWI_OLTP", "raw.SqlCreditNote", "CreditReasonCode"),
    ("ADJUSTMENT", "WWI_OLTP", "raw.SqlStockMovement", "MovementReasonCode"),
    ("TRANSACTION_TYPE", "WWI_OLTP", "raw.SqlStockMovement", "TransactionTypeName"),
]
