"""Verbatim copy of the 29 rules seeded by sqlserver/control/05_seed_data_quality_rules.sql.

RuleExpression text is the legacy T-SQL predicate exactly as seeded (only the T-SQL
'' quote escaping is undone), so notebooks, tests and the mapping document quote the
rule the business signed off. Spark-executable translations are produced at run time by
``dq_quality.rules.translateRuleExpression``; this module never edits the text.
The runtime source of truth is ``etl.data_quality_rule``; this list backs the unit tests
and is the Rule Engine fallback when that control table has no active rows.
"""

LEGACY_RULE_COLUMNS = ("RuleCode", "RuleGroupCode", "ObjectName", "RuleName", "RuleExpression",
                       "DimensionCode", "SeverityCode", "ThresholdValue", "RegionCode",
                       "SourceSystemCode")

LEGACY_RULES = [
    ('CUST_NULL_NAME', 'CUSTOMER', 'stg.Customer',
     'Customer name must be present',
     "CustomerName IS NULL OR LTRIM(RTRIM(CustomerName)) = N''",
     'Completeness', 'FAIL', 0, None, None),
    ('CUST_DUP_BKEY', 'CUSTOMER', 'stg.Customer',
     'Business key must be unique in the batch',
     'CustomerBusinessKey IN (SELECT CustomerBusinessKey FROM stg.Customer GROUP BY CustomerBusinessKey HAVING COUNT_BIG(*) > 1)',
     'Uniqueness', 'FAIL', 0, None, None),
    ('CUST_NO_CATEGORY', 'CUSTOMER', 'stg.Customer',
     'Category must resolve to the conformed set',
     'CustomerCategoryCode IS NULL',
     'Validity', 'WARN', 250, None, None),
    ('CUST_BAD_POSTCODE_NA', 'CUSTOMER', 'stg.Customer',
     'US and CA postal codes must match the country format',
     "CountryCode IN (N'US', N'CA') AND PostalCodeIsValid = 0",
     'Validity', 'WARN', 50, 'NA', None),
    ('CUST_BAD_POSTCODE_EU', 'CUSTOMER', 'stg.Customer',
     'EU postal codes must match the country format',
     "RegionCode = N'EU' AND PostalCodeIsValid = 0",
     'Validity', 'WARN', 400, 'EU', None),
    ('CUST_BAD_POSTCODE_AP', 'CUSTOMER', 'stg.Customer',
     'APAC postal codes must match the country format',
     "RegionCode = N'APAC' AND PostalCodeIsValid = 0",
     'Validity', 'WARN', 2000, 'APAC', None),
    ('CUST_FUTURE_OPENED', 'CUSTOMER', 'stg.Customer',
     'Account opened date cannot be in the future',
     'AccountOpenedDate > CAST(SYSUTCDATETIME() AS DATE)',
     'Validity', 'FAIL', 0, None, 'ORA_ERP'),
    ('SUPP_NULL_NAME', 'SUPPLIER', 'stg.Supplier',
     'Supplier name must be present',
     "SupplierName IS NULL OR LTRIM(RTRIM(SupplierName)) = N''",
     'Completeness', 'FAIL', 0, None, None),
    ('SUPP_NO_TAXID_EU', 'SUPPLIER', 'stg.Supplier',
     'EU suppliers must carry a VAT registration',
     "RegionCode = N'EU' AND (TaxRegistrationNumber IS NULL OR LEN(TaxRegistrationNumber) < 8)",
     'Completeness', 'FAIL', 5, 'EU', None),
    ('SUPP_NO_PAYMENT_TERM', 'SUPPLIER', 'stg.Supplier',
     'Payment terms must resolve',
     'PaymentTermsCode IS NULL',
     'Validity', 'WARN', 25, None, None),
    ('OL_NEG_QTY', 'ORDERLINE', 'stg.OrderLine',
     'Ordered quantity must be positive',
     'Quantity <= 0',
     'Validity', 'FAIL', 0, None, None),
    ('OL_NEG_PRICE', 'ORDERLINE', 'stg.OrderLine',
     'Unit price must not be negative',
     'UnitPrice < 0',
     'Validity', 'FAIL', 0, None, None),
    ('OL_ORPHAN_ORDER', 'ORDERLINE', 'stg.OrderLine',
     'Every line must have a header',
     'NOT EXISTS (SELECT 1 FROM stg.[Order] AS o WHERE o.OrderBusinessKey = stg.OrderLine.OrderBusinessKey)',
     'Integrity', 'FAIL', 0, None, None),
    ('OL_DISCOUNT_RANGE', 'ORDERLINE', 'stg.OrderLine',
     'Discount percentage must be between 0 and 90',
     'DiscountPercentage < 0 OR DiscountPercentage > 90',
     'Validity', 'WARN', 10, None, None),
    ('OL_EXTENDED_MISMATCH', 'ORDERLINE', 'stg.OrderLine',
     'Extended amount must agree with quantity times net price',
     'ABS(ExtendedAmount - (Quantity * UnitPrice * (1 - DiscountPercentage / 100.0))) > 0.01',
     'Accuracy', 'WARN', 100, None, None),
    ('IL_NO_TAX_RATE', 'INVOICE', 'stg.InvoiceLine',
     'Tax rate must resolve from the jurisdiction',
     'TaxRate IS NULL',
     'Completeness', 'FAIL', 0, None, None),
    ('IL_TAX_MISMATCH_NA', 'INVOICE', 'stg.InvoiceLine',
     'NA sales tax must agree with the rate applied',
     "RegionCode = N'NA' AND ABS(TaxAmount - (ExtendedAmount * TaxRate / 100.0)) > 0.02",
     'Accuracy', 'FAIL', 0, 'NA', None),
    ('IL_TAX_MISMATCH_EU', 'INVOICE', 'stg.InvoiceLine',
     'EU VAT must agree unless reverse charged',
     "RegionCode = N'EU' AND ReverseChargeFlag = 0 AND ABS(TaxAmount - (ExtendedAmount * TaxRate / 100.0)) > 0.02",
     'Accuracy', 'WARN', 75, 'EU', None),
    ('IL_MARGIN_NEGATIVE', 'INVOICE', 'stg.InvoiceLine',
     'Margin below cost needs review',
     'ExtendedAmount < CostAmount',
     'Plausibility', 'WARN', 500, None, None),
    ('PAY_UNAPPLIED', 'PAYMENT', 'stg.SupplierPayment',
     'Payments must be applied to an invoice',
     'InvoiceBusinessKey IS NULL',
     'Integrity', 'WARN', 40, None, None),
    ('PAY_FX_MISSING', 'PAYMENT', 'stg.SupplierPayment',
     'Non-USD payments need an FX rate for the value date',
     "CurrencyCode <> N'USD' AND FxRateToUsd IS NULL",
     'Completeness', 'FAIL', 0, None, None),
    ('PAY_FUTURE_DATE', 'PAYMENT', 'stg.SupplierPayment',
     'Payment date cannot be in the future',
     'PaymentDate > CAST(SYSUTCDATETIME() AS DATE)',
     'Validity', 'FAIL', 0, None, 'ORA_ERP'),
    ('REF_UNMAPPED_CODE', 'REFERENCE', 'ref.CodeCrosswalk',
     'Source codes must map to the conformed set',
     'ConformedCode IS NULL',
     'Integrity', 'WARN', 30, None, None),
    ('REF_FX_GAP', 'REFERENCE', 'ref.FxRateDaily',
     'FX rates must exist for every trading day in the window',
     'RateToUsd IS NULL',
     'Completeness', 'FAIL', 0, None, None),
    ('REF_TAX_EXPIRED', 'REFERENCE', 'ref.TaxJurisdiction',
     'An active jurisdiction must not be expired',
     'IsActive = 1 AND EffectiveTo < CAST(SYSUTCDATETIME() AS DATE)',
     'Validity', 'WARN', 5, None, None),
    ('INV_NEG_ONHAND', 'INVENTORY', 'stg.StockHolding',
     'On hand quantity must not be negative',
     'QuantityOnHand < 0',
     'Plausibility', 'WARN', 20, None, None),
    ('MOV_NO_REASON', 'INVENTORY', 'stg.Movement',
     'Adjustments must carry a reason code',
     "MovementTypeCode = N'ADJ' AND ReasonCode IS NULL",
     'Completeness', 'WARN', 15, None, None),
    ('FILE_SHORT_ROW', 'FILE', 'err.RejectedFileRow',
     'Delimited rows must have the expected column count',
     "RejectReasonCode = N'COLUMN_COUNT'",
     'Validity', 'WARN', 100, None, None),
    ('FILE_BAD_ENCODING', 'FILE', 'err.RejectedFileRow',
     'Inbound files must decode cleanly',
     "RejectReasonCode = N'ENCODING'",
     'Validity', 'FAIL', 0, None, None),
]
