/* =====================================================================
 * Object       : Seed data - WWI_AUDIT.EXTRACT_CONTROL
 * Schema       : WWI_REF / WWI_AUDIT / WWI_FIN (Oracle ERP - WWIGERP)
 * Deploy order : 203
 * Depends on   : oracle/tables/WWI_AUDIT.EXTRACT_CONTROL.sql
 * Called by    : run once per environment, after the reference content
 *
 * The source-side registration of every extract the downstream staging loads
 * run against this ERP, seeded in the state a fresh environment starts in:
 * no watermarks taken, status NEW.
 *
 * These rows are the Oracle-side counterpart of the SQL Server batch and
 * watermark control framework in sqlserver/control. Both sides keep their own
 * high-water mark and they are updated independently, which is why a failed
 * load leaves them disagreeing.
 *
 * Seeded IDs stay below 10001, where SEQ_EXTRACT_CONTROL starts.
 * ===================================================================== */

SET DEFINE OFF

INSERT ALL
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (101, 'EXT_ORA_CUSTOMER_MASTER', 'WWI_MDM', 'CUST_MASTER',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 120, NULL, 'Rows with a null UPDATED_DT are only picked up by a full reload.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (102, 'EXT_ORA_CUSTOMER_ADDRESS', 'WWI_MDM', 'CUST_ADDRESS',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 120, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (103, 'EXT_ORA_SUPPLIER_MASTER', 'WWI_MDM', 'SUPP_MASTER',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 120, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (104, 'EXT_ORA_SUPPLIER_BANK', 'WWI_MDM', 'SUPP_BANK_ACCOUNT',
            'SQLSERVER_STAGING', 'FULL', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'N', 'N',
            NULL, NULL, 'W', 240, NULL,
            'Disabled: the extract role has no privilege on this table by design.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (105, 'EXT_ORA_PRODUCT_MASTER', 'WWI_MDM', 'PROD_MASTER',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 120, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (106, 'EXT_ORA_PURCHASE_ORDER_HDR', 'WWI_PROC', 'PURCHASE_ORDER_HDR',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'H', 60, NULL, 'Partition-pruned by ORDER_DT; the watermark is on UPDATED_DT.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (107, 'EXT_ORA_PURCHASE_ORDER_LINE', 'WWI_PROC', 'PURCHASE_ORDER_LINE',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'H', 60, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (108, 'EXT_ORA_PO_RECEIPT_LINE', 'WWI_PROC', 'PO_RECEIPT_LINE',
            'SQLSERVER_STAGING', 'INCR', 'RECEIPT_LINE_ID', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'H', 60, NULL, 'Id-driven because receipt lines are never updated after insert.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (109, 'EXT_ORA_VENDOR_CONTRACT', 'WWI_PROC', 'VENDOR_CONTRACT',
            'SQLSERVER_STAGING', 'FULL', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'W', 240, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (110, 'EXT_ORA_AP_INVOICE_HDR', 'WWI_FIN', 'AP_INVOICE_HDR',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 180, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (111, 'EXT_ORA_AP_INVOICE_LINE', 'WWI_FIN', 'AP_INVOICE_LINE',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 180, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (112, 'EXT_ORA_AP_PAYMENT', 'WWI_FIN', 'AP_PAYMENT',
            'SQLSERVER_STAGING', 'INCR', 'UPDATED_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 180, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (113, 'EXT_ORA_GL_JOURNAL_LINE', 'WWI_FIN', 'GL_JOURNAL_LINE',
            'SQLSERVER_STAGING', 'INCR', 'JOURNAL_LINE_ID', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 240, NULL, 'Both a timestamp and an id watermark are maintained for this one.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (114, 'EXT_ORA_GL_ACCOUNT', 'WWI_FIN', 'GL_ACCOUNT',
            'SQLSERVER_STAGING', 'FULL', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'W', 120, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (115, 'EXT_ORA_COST_CENTER', 'WWI_FIN', 'COST_CENTER',
            'SQLSERVER_STAGING', 'FULL', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'W', 120, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (116, 'EXT_ORA_TAX_RATE', 'WWI_FIN', 'TAX_RATE',
            'SQLSERVER_STAGING', 'FULL', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'W', 120, NULL, 'Effective-dated; the consumer keeps all versions.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (117, 'EXT_ORA_FX_RATE_DAILY', 'WWI_REF', 'FX_RATE_DAILY',
            'SQLSERVER_STAGING', 'INCR', 'RATE_DT', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'D', 60, NULL, 'APAC has no weekend rows, so a Monday extract sees a three-day gap.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (118, 'EXT_ORA_REFERENCE_CODES', 'WWI_REF', 'STATUS_CODE_REF',
            'SQLSERVER_STAGING', 'FULL', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'W', 60, NULL, NULL)
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (119, 'EXT_ORA_CHANGE_LOG_CDC', 'WWI_AUDIT', 'CHANGE_LOG',
            'SQLSERVER_STAGING', 'CDC', 'CHANGE_TS', NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'H', 30, NULL,
            'Only covers the tables that have a trigger; the EU instance has fewer.')
    INTO WWI_AUDIT.EXTRACT_CONTROL
        (EXTRACT_CONTROL_ID, EXTRACT_NAME, SOURCE_SCHEMA_NAME, SOURCE_OBJECT_NAME,
         CONSUMER_SYSTEM_CD, LOAD_TYPE_CD, WATERMARK_COLUMN_NAME, LAST_WATERMARK_TS,
         LAST_WATERMARK_ID, LAST_EXTRACT_START_TS, LAST_EXTRACT_END_TS, LAST_ROW_COUNT,
         LAST_STATUS_CD, LAST_ERROR_TXT, CONSECUTIVE_FAILURE_CNT, ENABLED_FLG, LOCK_FLG,
         LOCKED_BY_TXT, LOCKED_TS, EXPECTED_FREQUENCY_CD, SLA_MINUTES, REGION_CD, NOTES_TXT)
    VALUES (120, 'EXT_ORA_SUPPLIER_SCORECARD', 'WWI_PROC', 'SUPPLIER_SCORECARD',
            'SQLSERVER_STAGING', 'SNAPSHOT', NULL, NULL,
            NULL, NULL, NULL, NULL,
            'NEW', NULL, 0, 'Y', 'N',
            NULL, NULL, 'M', 240, NULL, 'Period basis differs per region, so a monthly run is partly empty.')
SELECT * FROM DUAL
/

COMMIT
/

SET DEFINE ON
